Polyrific-Inc/OpenCatapult

- docs/dev/create-plugin.md
- docs/dev/index.md
- docs/guide/data-models.md
- docs/guide/engine-registration.md
- docs/guide/external-services.md
- docs/guide/job-definitions.md
- docs/guide/job-queues.md
- docs/guide/plugins.md
- docs/guide/project-members.md
- docs/guide/project.md
- docs/guide/users.md
- docs/toc.md
Add skeleton for guidance contents.
> Add skeleton for guidance contents

- docs/cli/account.md
- docs/cli/cli.md
- docs/cli/config.md
- docs/cli/engine.md
- docs/cli/job.md
- docs/cli/member.md
- docs/cli/model.md
- docs/cli/plugin.md
- docs/cli/project.md
- docs/cli/property.md
- docs/cli/queue.md
- docs/cli/service.md
- docs/cli/task.md
Update cli docs options to use bullet points
> Update cli docs

- cli.appveyor.yml
- src/CLI/Polyrific.Catapult.Cli/Polyrific.Catapult.Cli.csproj
Add `appveyor` yaml file for CLI project.
> Add appveyor yaml for CLI

- Polyrific.Catapult.Engine.sln
- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/PushTask.cs
- src/Plugins/GeneratorProvider/AspNetCoreMvc/src/CodeGeneratorProvider.cs
- src/Plugins/Polyrific.Catapult.Plugins.Abstraction/Configs/CloneTaskConfig.cs
- src/Plugins/Polyrific.Catapult.Plugins.Abstraction/Configs/PushTaskConfig.cs
- src/Plugins/Polyrific.Catapult.Plugins.Abstraction/IBuildProvider.cs
- src/Plugins/Polyrific.Catapult.Plugins.Abstraction/ICodeGeneratorProvider.cs
- src/Plugins/Polyrific.Catapult.Plugins.Abstraction/ICodeRepositoryProvider.cs
- src/Plugins/Polyrific.Catapult.Plugins.Abstraction/IDeployProvider.cs
- src/Plugins/Polyrific.Catapult.Plugins.Abstraction/Polyrific.Catapult.Plugins.Abstraction.csproj
- src/Plugins/RepositoryProvider/GitHubRepositoryProvider/plugin.yml
- src/Plugins/RepositoryProvider/GitHubRepositoryProvider/src/GitHubRepositoryProvider/CodeRepository.cs
- src/Plugins/RepositoryProvider/GitHubRepositoryProvider/src/GitHubRepositoryProvider/CodeRepositoryConfig.cs
- src/Plugins/RepositoryProvider/GitHubRepositoryProvider/src/GitHubRepositoryProvider/CodeRepositoryProvider.cs
- src/Plugins/RepositoryProvider/GitHubRepositoryProvider/src/GitHubRepositoryProvider/GitHubRepositoryProvider.csproj
- src/Plugins/RepositoryProvider/GitHubRepositoryProvider/src/GitHubRepositoryProvider/Helpers/ConversionHelper.cs
- src/Plugins/RepositoryProvider/GitHubRepositoryProvider/src/GitHubRepositoryProvider/ICodeRepository.cs
- tests/Polyrific.Catapult.Engine.UnitTests/Core/JobTasks/Utilities/FakeBuildProvider.cs
- tests/Polyrific.Catapult.Engine.UnitTests/Core/JobTasks/Utilities/FakeCodeGeneratorProvider.cs
- tests/Polyrific.Catapult.Engine.UnitTests/Core/JobTasks/Utilities/FakeCodeRepositoryProvider.cs
- tests/Polyrific.Catapult.Engine.UnitTests/Core/JobTasks/Utilities/FakeDeployProvider.cs
Implement `GitHubRepositoryProvider` plugin.
> Implement GitHubRepositoryProvider

- Polyrific.Catapult.Engine.sln
- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/BuildTask.cs
- src/Plugins/BuildProvider/DotNetCoreBuildProvider/plugin.yml
- src/Plugins/BuildProvider/DotNetCoreBuildProvider/src/DotNetCoreBuildProvider/BuildProvider.cs
- src/Plugins/BuildProvider/DotNetCoreBuildProvider/src/DotNetCoreBuildProvider/Builder.cs
- src/Plugins/BuildProvider/DotNetCoreBuildProvider/src/DotNetCoreBuildProvider/DotNetCoreBuildProvider.csproj
- src/Plugins/BuildProvider/DotNetCoreBuildProvider/src/DotNetCoreBuildProvider/Helpers/CommandHelper.cs
- src/Plugins/BuildProvider/DotNetCoreBuildProvider/src/DotNetCoreBuildProvider/IBuilder.cs
- src/Plugins/Polyrific.Catapult.Plugins.Abstraction/Configs/BuildTaskConfig.cs
- src/Plugins/Polyrific.Catapult.Plugins.Abstraction/IBuildProvider.cs
- tests/Polyrific.Catapult.Engine.UnitTests/Core/JobTasks/Utilities/FakeBuildProvider.cs
Add `DotNetCoreBuildProvider` plugin.
> Add DotNetCoreBuildProvider plugin

- src/Engine/Polyrific.Catapult.Engine.Core/CatapultEngineConfig.cs
- src/Engine/Polyrific.Catapult.Engine.Core/Polyrific.Catapult.Engine.Core.csproj
- src/Engine/Polyrific.Catapult.Engine.Infrastructure/Polyrific.Catapult.Engine.Infrastructure.csproj
- src/Plugins/BuildProvider/DotNetCoreBuildProvider/src/DotNetCoreBuildProvider/DotNetCoreBuildProvider.csproj
- src/Plugins/GeneratorProvider/AspNetCoreMvc/src/AspNetCoreMvc.csproj
- src/Plugins/GeneratorProvider/AspNetCoreMvc/tests/AspNetCoreMvc.Tests/AspNetCoreMvc.Tests.csproj
- src/Plugins/Polyrific.Catapult.Plugins.Abstraction/Polyrific.Catapult.Plugins.Abstraction.csproj
- src/Plugins/RepositoryProvider/GitHubRepositoryProvider/src/GitHubRepositoryProvider/GitHubRepositoryProvider.csproj
- src/Shared/Polyrific.Catapult.Shared.ApiClient/Polyrific.Catapult.Shared.ApiClient.csproj
- src/Shared/Polyrific.Catapult.Shared.Common/FileHelper.cs
- src/Shared/Polyrific.Catapult.Shared.Common/LocalTextWriter.cs
- src/Shared/Polyrific.Catapult.Shared.Common/Polyrific.Catapult.Shared.Common.csproj
- src/Shared/Polyrific.Catapult.Shared.Dto/Polyrific.Catapult.Shared.Dto.csproj
- src/Shared/Polyrific.Catapult.Shared.Service/Polyrific.Catapult.Shared.Service.csproj
- tests/Polyrific.Catapult.Engine.UnitTests/Polyrific.Catapult.Engine.UnitTests.csproj
Change libraries to target `netstandard2.0` instead of `netcoreapp2.1`.
> Change libraries to target netstandard2.0

- Polyrific.Catapult.Api.sln
- src/API/Polyrific.Catapult.Api.Core/Security/ISecretVault.cs
- src/API/Polyrific.Catapult.Api.Core/Services/ExternalServiceService.cs
- src/API/Polyrific.Catapult.Api.Infrastructure/Polyrific.Catapult.Api.Infrastructure.csproj
- src/API/Polyrific.Catapult.Api.Infrastructure/SecretVaultInjection.cs
- src/API/Polyrific.Catapult.Api.SecretVault/Polyrific.Catapult.Api.SecretVault.csproj
- src/API/Polyrific.Catapult.Api.SecretVault/SecretVault.cs
- src/API/Polyrific.Catapult.Api.SecretVault/SecretVaultInjection.cs
- tests/Polyrific.Catapult.Api.UnitTests/Core/Services/ExternalServiceServiceTests.cs
Move the local secret vault interface and implementation into `.Api` namespace
> Move local secret vault to API

- src/Plugins/GeneratorProvider/AspNetCoreMvc/tests/AspNetCoreMvc.Tests.csproj
Remove accidentally added folder reference in csproj
> Remove deleted folder reference from AspNetCoreMvc.Tests.csproj

- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/DeployTask.cs
- src/Plugins/DeployProvider/AzureAppService/src/AzureAppService.csproj
- src/Plugins/DeployProvider/AzureAppService/src/AzureAppServiceConfig.cs
- src/Plugins/DeployProvider/AzureAppService/src/AzureAutomation.cs
- src/Plugins/DeployProvider/AzureAppService/src/DeployProvider.cs
- src/Plugins/DeployProvider/AzureAppService/src/Helpers/CommandHelper.cs
- src/Plugins/DeployProvider/AzureAppService/src/IAzureAutomation.cs
- src/Plugins/Polyrific.Catapult.Plugins.Abstraction/Configs/DeployTaskConfig.cs
- src/Plugins/Polyrific.Catapult.Plugins.Abstraction/IDeployProvider.cs
- tests/Polyrific.Catapult.Engine.UnitTests/Core/JobTasks/Utilities/FakeDeployProvider.cs
> Add AzureAppService plugin

- src/API/Polyrific.Catapult.Api.Core/Entities/PluginAdditionalConfig.cs
- src/API/Polyrific.Catapult.Api.Core/Exceptions/PluginNotFoundException.cs
- src/API/Polyrific.Catapult.Api.Core/Repositories/IPluginAdditionalConfigRepository.cs
- src/API/Polyrific.Catapult.Api.Core/Services/IPluginAdditionalConfigService.cs
- src/API/Polyrific.Catapult.Api.Core/Services/PluginAdditionalConfigService.cs
- src/API/Polyrific.Catapult.Api.Core/Specifications/PluginAdditionalConfigFilterSpecification.cs
- src/API/Polyrific.Catapult.Api.Data/CatapultDbContext.cs
- src/API/Polyrific.Catapult.Api.Data/EntityConfigs/PluginAdditionalConfigConfig.cs
- src/API/Polyrific.Catapult.Api.Data/Migrations/20180924063858_AddPluginAdditionalConfigs.Designer.cs
- src/API/Polyrific.Catapult.Api.Data/Migrations/20180924063858_AddPluginAdditionalConfigs.cs
- src/API/Polyrific.Catapult.Api.Data/PluginAdditionalConfigRepository.cs
- src/API/Polyrific.Catapult.Api.Infrastructure/RepositoryInjection.cs
- src/API/Polyrific.Catapult.Api/AutoMapperProfiles/PluginAdditionalConfigAutoMapperProfile.cs
- src/API/Polyrific.Catapult.Api/Controllers/PluginController.cs
- src/API/Polyrific.Catapult.Api/ServiceInjection.cs
- src/Plugins/HostingProvider/AzureAppService/plugin.yml
- src/Shared/Polyrific.Catapult.Shared.Dto/Plugin/NewPluginDto.cs
- src/Shared/Polyrific.Catapult.Shared.Dto/Plugin/PluginAdditionalConfigDto.cs
- src/Shared/Polyrific.Catapult.Shared.Dto/Plugin/PluginDto.cs
- tests/Polyrific.Catapult.Api.UnitTests/Core/Services/PluginAdditionalConfigServiceTests.cs
Add plugin additional configs.
> Add plugin additional configs

- src/CLI/Polyrific.Catapult.Cli/Commands/Plugin/ListCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Task/AddCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Task/GetCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Task/UpdateCommand.cs
Add allowed values for newly added Task Type and Plugin Type
> add allowed values for task and plugin type

- src/Engine/Polyrific.Catapult.Engine.Core/CatapultEngine.cs
- src/Engine/Polyrific.Catapult.Engine.Core/CatapultEngineConfig.cs
- src/Engine/Polyrific.Catapult.Engine.Core/ICatapultEngineConfig.cs
- src/Engine/Polyrific.Catapult.Engine.Core/ITaskRunner.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/BaseJobTask.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/BuildTask.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/IJobTask.cs
- src/Engine/Polyrific.Catapult.Engine.Core/TaskRunner.cs
- src/Plugins/BuildProvider/DotNetCore/src/BuildProvider.cs
- src/Plugins/BuildProvider/DotNetCore/src/Builder.cs
- src/Plugins/BuildProvider/DotNetCore/src/Helpers/CommandHelper.cs
- src/Plugins/BuildProvider/DotNetCore/src/IBuilder.cs
- src/Plugins/BuildProvider/DotNetCore/tests/BuildProviderTests.cs
- src/Plugins/BuildProvider/DotNetCore/tests/DotNetCore.Tests.csproj
- src/Plugins/Polyrific.Catapult.Plugins.Abstraction/IBuildProvider.cs
- tests/Polyrific.Catapult.Engine.UnitTests/Core/CatapultEngineTests.cs
- tests/Polyrific.Catapult.Engine.UnitTests/Core/JobTasks/BuildTaskTests.cs
- tests/Polyrific.Catapult.Engine.UnitTests/Core/JobTasks/DeployTaskTests.cs
- tests/Polyrific.Catapult.Engine.UnitTests/Core/JobTasks/GenerateTaskTests.cs
- tests/Polyrific.Catapult.Engine.UnitTests/Core/JobTasks/PushTaskTests.cs
- tests/Polyrific.Catapult.Engine.UnitTests/Core/JobTasks/Utilities/FakeBuildProvider.cs
- tests/Polyrific.Catapult.Engine.UnitTests/Core/TaskRunnerTests.cs
Fix `DotNetCore` build provider plugin.
> Fix DotNetCore build provider plugin

- appveyor/plugin-aspnetcoremvc.appveyor.yml
Add appveyor yaml for `AspNetCoreMvc` plugin.
> Add appveyor yaml for AspNetCoreMvc plugin

- appveyor/plugin-aspnetcoremvc.appveyor.yml
- appveyor/plugin-dotnetcore.appveyor.yml
Add `Polyrific.Catapult.Plugins.Abstraction` as trigger to the plugins CI.
> Add Plugins.Abstraction as trigger to the plugins ci

- src/Engine/Polyrific.Catapult.Engine.Core/EngineCoreInjection.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/CloneTask.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/DeployDbTask.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/MergeTask.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/PublishArtifactTask.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/TestTask.cs
Fix task injection which caused exception in early engine invocation.
> Fix task injection

- src/API/Polyrific.Catapult.Api.Core/Security/ISecretVault.cs
- src/API/Polyrific.Catapult.Api.Core/Services/JobDefinitionService.cs
- src/API/Polyrific.Catapult.Api.SecretVault/SecretVault.cs
- tests/Polyrific.Catapult.Api.UnitTests/Core/Services/JobDefinitionServiceTests.cs
- Encrypt the secret additional config value when saving JobTaskDefinition
- Decrypt the encrypted addtional config value when retrieving JobTaskDefinition
> Encrypt the secret additional config before save

- src/Plugins/HostingProvider/AzureAppService/src/AzureAutomation.cs
- src/Plugins/HostingProvider/AzureAppService/src/AzureUtils.cs
- src/Plugins/HostingProvider/AzureAppService/src/HostingProvider.cs
- src/Plugins/HostingProvider/AzureAppService/src/IAzureUtils.cs
- src/Plugins/HostingProvider/AzureAppService/src/IMsDeployUtils.cs
- src/Plugins/HostingProvider/AzureAppService/src/MsDeployUtils.cs
- src/Plugins/HostingProvider/AzureAppService/tests/AzureAppService.Tests.csproj
- src/Plugins/HostingProvider/AzureAppService/tests/HostingProviderTests.cs
- Refactor AzureAppService plugin so it can be unittested
- Implement unit test
> Fix AzureAppService plugin

- src/Plugins/TestProvider/DotNetCoreTest/tests/TestProviderTests.cs
fix error in TestProvider unit test
> fix error in TestProvider unit test

- src/API/Polyrific.Catapult.Api.Data/EntityConfigs/ExternalServicePropertyConfig.cs
- src/API/Polyrific.Catapult.Api.Data/EntityConfigs/ExternalServiceTypeConfig.cs
- src/API/Polyrific.Catapult.Api.Data/Migrations/20180928040651_AzureAppServiceSeed.Designer.cs
- src/API/Polyrific.Catapult.Api.Data/Migrations/20180928040651_AzureAppServiceSeed.cs
Add seed data for `AzureAppService` external service type and properties
> Add seed data for azure app service properties

- src/CLI/Polyrific.Catapult.Cli/Templates/sample.yaml
Modify the predefined project template to show job task definition to deployment
> Modify project template sample.yaml

- src/CLI/Polyrific.Catapult.Cli/Extensions/CatapultCliExtensions.cs
Add indentation when displaying item list in CLI
Issue: #57
> Add indentation when displaying items in CLI

- appveyor/plugin-entityframeworkcore.appveyor.yml
Add appveyor yaml for EF Core plugin.
> Add appveyor yaml for EF Core plugin

- appveyor/plugin-azureappservice.appveyor.yml
Add appveyor yaml for Azure App Service plugin.
> Add appveyor yaml for Azure App Service plugin

- appveyor/plugin-dotnetcoretest.appveyor.yml
Add appveyor yaml for DotNetCore Test plugin.
> Add appveyor yaml for DotNetCore Test plugin

- src/CLI/Polyrific.Catapult.Cli/Commands/Account/SetRoleCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/AccountCommand.cs
- tests/Polyrific.Catapult.Cli.UnitTests/Commands/AccountCommandTests.cs
Implement the CLI command to set user's role
> Implement account set role command

- src/Engine/Polyrific.Catapult.Engine.Core/CatapultEngine.cs
Update job queue status when error occured, or when job is completed
> Engine: Update job queue status

- src/Engine/Polyrific.Catapult.Engine.Core/Exceptions/ExternalServiceNotFoundException.cs
- src/Engine/Polyrific.Catapult.Engine.Core/Exceptions/InvalidExternalServiceTypeException.cs
- src/Engine/Polyrific.Catapult.Engine.Core/Exceptions/UnavailableExternalServiceException.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/BaseJobTask.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/BuildTask.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/CloneTask.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/DeployDbTask.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/DeployTask.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/GenerateTask.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/IJobTask.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/MergeTask.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/PublishArtifactTask.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/PushTask.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/TestTask.cs
- src/Engine/Polyrific.Catapult.Engine.Core/TaskRunner.cs
- src/Engine/Polyrific.Catapult.Engine.Infrastructure/ApiServiceInjection.cs
- src/Plugins/BuildProvider/DotNetCore/src/DotNetCore.csproj
- src/Plugins/DatabaseProvider/EntityFrameworkCore/src/EntityFrameworkCore.csproj
- src/Plugins/HostingProvider/AzureAppService/src/AzureAppService.csproj
- src/Plugins/RepositoryProvider/GitHub/src/GitHub.csproj
- src/Plugins/TestProvider/DotNetCoreTest/src/DotNetCoreTest.csproj
- tests/Polyrific.Catapult.Engine.UnitTests/Core/JobTasks/BuildTaskTests.cs
- tests/Polyrific.Catapult.Engine.UnitTests/Core/JobTasks/DeployTaskTests.cs
- tests/Polyrific.Catapult.Engine.UnitTests/Core/JobTasks/GenerateTaskTests.cs
- tests/Polyrific.Catapult.Engine.UnitTests/Core/JobTasks/PushTaskTests.cs
Implement loading external service in Task
Issue: #78
> Engine: Load external service

- src/Engine/Polyrific.Catapult.Engine.Core/CatapultEngine.cs
- src/Engine/Polyrific.Catapult.Engine.Core/ITaskRunner.cs
- src/Engine/Polyrific.Catapult.Engine.Core/TaskRunner.cs
- tests/Polyrific.Catapult.Engine.UnitTests/Core/CatapultEngineTests.cs
- tests/Polyrific.Catapult.Engine.UnitTests/Core/TaskRunnerTests.cs
Update job task status for each task completed
> Engine update task status

- Polyrific.Catapult.Engine.sln
- src/API/Polyrific.Catapult.Api/Hubs/JobQueueHub.cs
- src/CLI/Polyrific.Catapult.Cli/JobQueueLogListener/SignalRJobQueueLogListener.cs
- src/Engine/Polyrific.Catapult.Engine.Core/CatapultEngine.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobLogger/IJobLogWriter.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobLogger/JobLogger.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobLogger/JobLoggerProvider.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobLogger/JobLoggerScope.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobLogger/JobScope.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobLogger/TaskScope.cs
- src/Engine/Polyrific.Catapult.Engine.Core/TaskRunner.cs
- src/Engine/Polyrific.Catapult.Engine.Infrastructure/LoggerInjection.cs
- src/Engine/Polyrific.Catapult.Engine.Infrastructure/Polyrific.Catapult.Engine.Infrastructure.csproj
- src/Engine/Polyrific.Catapult.Engine.SignalRLogger/Polyrific.Catapult.Engine.SignalRLogger.csproj
- src/Engine/Polyrific.Catapult.Engine.SignalRLogger/SignalRClientOption.cs
- src/Engine/Polyrific.Catapult.Engine.SignalRLogger/SignalRJobLogWriter.cs
- src/Engine/Polyrific.Catapult.Engine.SignalRLogger/SignalRLogWriterExtensions.cs
- src/Engine/Polyrific.Catapult.Engine/Program.cs
- src/Plugins/GeneratorProvider/AspNetCoreMvc/src/CodeGeneratorProvider.cs
- src/Shared/Polyrific.Catapult.Shared.Common/LocalTextWriter.cs
- tests/Polyrific.Catapult.Engine.UnitTests/Core/CatapultEngineTests.cs
- tests/Polyrific.Catapult.Engine.UnitTests/Core/TaskRunnerTests.cs
Invoke signalR hub for each engine's log related to a job.
Issue #77
> Implement signalR log writer in engine

- src/API/Polyrific.Catapult.Api/Controllers/AccountController.cs
- src/Shared/Polyrific.Catapult.Shared.Common/Interface/INotificationSender.cs
- src/Shared/Polyrific.Catapult.Shared.Common/Notification/NotificationProvider.cs
- src/Shared/Polyrific.Catapult.Shared.Common/Polyrific.Catapult.Shared.Common.csproj
- src/Shared/Polyrific.Catapult.Shared.SmtpEmailNotification/SmtpEmailSender.cs
Add loggin when sending notification and when sending notification failed.
issue: #82
> Add logging in notification provider

- src/API/Polyrific.Catapult.Api.Core/Services/IUserService.cs
- src/API/Polyrific.Catapult.Api.Core/Services/UserService.cs
- src/API/Polyrific.Catapult.Api/Controllers/AccountController.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Account/RegisterCommand.cs
- src/Shared/Polyrific.Catapult.Shared.Common/Notification/MessageParameter.cs
- src/Shared/Polyrific.Catapult.Shared.Common/Notification/Template/RegistrationCompleted.html
- src/Shared/Polyrific.Catapult.Shared.Common/Notification/Template/SmtpEmail/RegistrationCompleted.html
- src/Shared/Polyrific.Catapult.Shared.Dto/User/RegisterUserDto.cs
- tests/Polyrific.Catapult.Cli.UnitTests/Commands/AccountCommandTests.cs
Adjust the user registration process so that it is by invitation from administrator
Issue: #84
> Adjust user registration process

- src/CLI/Polyrific.Catapult.Cli/Commands/Account/ActivateCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Account/ListCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Account/Password/ResetCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Account/Password/ResetTokenCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Account/Password/UpdateCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Account/RegisterCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Account/RemoveCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Account/SetRoleCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Account/SuspendCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Account/UpdateCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/BaseCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/CurrentUserCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/LoginCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/LogoutCommand.cs
- tests/Polyrific.Catapult.Cli.UnitTests/Commands/AccountCommandTests.cs
- tests/Polyrific.Catapult.Cli.UnitTests/Commands/LoginCommandTests.cs
- tests/Polyrific.Catapult.Cli.UnitTests/Commands/LogoutCommandTests.cs
Add intro messages for:
- login, logout, and currentuser commands
- accounts commands
- https://github.com/Polyrific-Inc/OpenCatapult/issues/91
> Add intro messages

- src/Engine/Polyrific.Catapult.Engine.SignalRLogger/SignalRJobLogWriter.cs
Make the SignalR connect only when it's about to send message. This will fix the issue when the API has not been configured, and the signalR tries to connect to the dummy address
- #97
> Change the signalR connection to be connected when it's about to be used

- src/API/Polyrific.Catapult.Api.Core/Services/UserService.cs
- tests/Polyrific.Catapult.Api.UnitTests/Core/Services/UserServiceTests.cs
- tests/Polyrific.Catapult.Api.UnitTests/Polyrific.Catapult.Api.UnitTests.csproj
Fix the password generator so that it always satisfy the asp net core password policy
- #102
> Fix password generator to always comply with password policy

- src/API/Polyrific.Catapult.Api.Core/Entities/User.cs
- src/API/Polyrific.Catapult.Api.Data/Identity/ApplicationRole.cs
- src/API/Polyrific.Catapult.Api.Data/Identity/ApplicationUser.cs
- src/API/Polyrific.Catapult.Api.Data/Identity/ApplicationUserRole.cs
- src/API/Polyrific.Catapult.Api.Data/Identity/IdentityAutoMapperProfile.cs
- src/API/Polyrific.Catapult.Api.Data/Identity/IdentityEntityConfigs.cs
- src/API/Polyrific.Catapult.Api.Data/UserRepository.cs
- src/Shared/Polyrific.Catapult.Shared.Dto/User/UserDto.cs
Include user role when running `account list` command
- #95
> Include user role when retrieving users

- src/CLI/Polyrific.Catapult.Cli/Commands/Account/RemoveCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Config/RemoveCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Engine/RemoveCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Job/RemoveCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Member/RemoveCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Model/RemoveCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Plugin/RemoveCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Project/RemoveCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Property/RemoveCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Service/RemoveCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Extensions/ConsoleExtension.cs
- tests/Polyrific.Catapult.Cli.UnitTests/Commands/AccountCommandTests.cs
- tests/Polyrific.Catapult.Cli.UnitTests/Commands/ConfigCommandTests.cs
- tests/Polyrific.Catapult.Cli.UnitTests/Commands/EngineCommandTests.cs
- tests/Polyrific.Catapult.Cli.UnitTests/Commands/JobCommandTests.cs
- tests/Polyrific.Catapult.Cli.UnitTests/Commands/MemberCommandTests.cs
- tests/Polyrific.Catapult.Cli.UnitTests/Commands/ModelCommandTests.cs
- tests/Polyrific.Catapult.Cli.UnitTests/Commands/PluginCommandTests.cs
- tests/Polyrific.Catapult.Cli.UnitTests/Commands/ProjectCommandTests.cs
- tests/Polyrific.Catapult.Cli.UnitTests/Commands/PropertyCommandTests.cs
- tests/Polyrific.Catapult.Cli.UnitTests/Commands/ServiceCommandTests.cs
- tests/Polyrific.Catapult.Cli.UnitTests/Commands/Utilities/FakeTextReader.cs
- tests/Polyrific.Catapult.Cli.UnitTests/Commands/Utilities/TestConsole.cs
show confirmation prompt in CLI when user trying to delete entities
- #101
> Add confirmation step when trying to delete entities

- src/CLI/Polyrific.Catapult.Cli/Commands/Project/ArchiveCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Project/CloneCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Project/CreateCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Project/ExportCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Project/ListCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Project/RemoveCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Project/RestoreCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Project/UpdateCommand.cs
- tests/Polyrific.Catapult.Cli.UnitTests/Commands/ProjectCommandTests.cs
Add intro message to project commands
- https://github.com/Polyrific-Inc/OpenCatapult/issues/91
> Add intro message to project commands

- appveyor/api.appveyor.yml
- src/API/Polyrific.Catapult.Api.Core/Polyrific.Catapult.Api.Core.csproj
- src/API/Polyrific.Catapult.Api.Core/Services/JobDefinitionService.cs
- src/API/Polyrific.Catapult.Api.Core/Services/PluginService.cs
- src/API/Polyrific.Catapult.Api.Data/Polyrific.Catapult.Api.Data.csproj
- src/API/Polyrific.Catapult.Api.Infrastructure/Polyrific.Catapult.Api.Infrastructure.csproj
- src/API/Polyrific.Catapult.Api.SecretVault/Polyrific.Catapult.Api.SecretVault.csproj
- src/API/Polyrific.Catapult.Api/Polyrific.Catapult.Api.csproj
- src/Shared/Polyrific.Catapult.Shared.Dto/Constants/DataDelimiter.cs
- tests/Polyrific.Catapult.Api.UnitTests/Polyrific.Catapult.Api.UnitTests.csproj
- Modify some projects to target `netstandard2.0`
- Upgrade nuget packages to latest stable version
- Update api.appveyor.yml
> Upgrade api libraries

- src/CLI/Polyrific.Catapult.Cli.Infrastructure/Polyrific.Catapult.Cli.Infrastructure.csproj
- src/CLI/Polyrific.Catapult.Cli/Polyrific.Catapult.Cli.csproj
- Change library to target `netstandard2.0`
- Upgrade nuget packages
> Upgrade CLI

- src/API/Polyrific.Catapult.Api/Controllers/AccountController.cs
- src/API/Polyrific.Catapult.Api/Controllers/CatapultEngineController.cs
- src/API/Polyrific.Catapult.Api/Controllers/ExternalServiceController.cs
- src/API/Polyrific.Catapult.Api/Controllers/ExternalServiceTypeController.cs
- src/API/Polyrific.Catapult.Api/Controllers/HealthController.cs
- src/API/Polyrific.Catapult.Api/Controllers/JobDefinitionController.cs
- src/API/Polyrific.Catapult.Api/Controllers/JobQueueController.cs
- src/API/Polyrific.Catapult.Api/Controllers/PluginController.cs
- src/API/Polyrific.Catapult.Api/Controllers/ProjectController.cs
- src/API/Polyrific.Catapult.Api/Controllers/ProjectDataModelController.cs
- src/API/Polyrific.Catapult.Api/Controllers/ProjectMemberController.cs
- src/API/Polyrific.Catapult.Api/Controllers/TokenController.cs
Add log in API endpoint for tracebility
- #93
> Add logging for each API endpoint

- src/API/Polyrific.Catapult.Api.Core/Services/IProjectService.cs
- src/API/Polyrific.Catapult.Api.Core/Services/ProjectService.cs
- src/API/Polyrific.Catapult.Api/Controllers/ProjectController.cs
- tests/Polyrific.Catapult.Api.UnitTests/Core/Services/ProjectServiceTests.cs
Fix clone project where it does not show in the list because it does not have a default owner
- #108
> Set default owner member when cloning project

- src/API/Polyrific.Catapult.Api/AutoMapperProfiles/ProjectAutoMapperProfile.cs
- src/Shared/Polyrific.Catapult.Shared.Dto/Project/ProjectDto.cs
Show project status when displaying a project, e.g. in `project list` command
- #106
> Show project status when displaying a project

- src/CLI/Polyrific.Catapult.Cli/Commands/Member/AddCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Member/ListCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Member/RemoveCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Member/UpdateCommand.cs
- tests/Polyrific.Catapult.Cli.UnitTests/Commands/MemberCommandTests.cs
Add intro message to member commands.
- https://github.com/Polyrific-Inc/OpenCatapult/issues/91
> Add intro message to member commands

- appveyor/api.appveyor.yml
- appveyor/cli.appveyor.yml
- appveyor/engine.appveyor.yml
- appveyor/plugin-aspnetcoremvc.appveyor.yml
- appveyor/plugin-azureappservice.appveyor.yml
- appveyor/plugin-dotnetcore.appveyor.yml
- appveyor/plugin-dotnetcoretest.appveyor.yml
- appveyor/plugin-entityframeworkcore.appveyor.yml
- appveyor/plugin-github.appveyor.yml
- src/API/Polyrific.Catapult.Api/Controllers/JobQueueController.cs
- src/API/Polyrific.Catapult.Api/Controllers/VersionController.cs
- src/API/Polyrific.Catapult.Api/Polyrific.Catapult.Api.csproj
- src/CLI/Polyrific.Catapult.Cli/Polyrific.Catapult.Cli.csproj
- src/Engine/Polyrific.Catapult.Engine/Polyrific.Catapult.Engine.csproj
- src/Plugins/BuildProvider/DotNetCore/src/DotNetCore.csproj
- src/Plugins/DatabaseProvider/EntityFrameworkCore/src/EntityFrameworkCore.csproj
- src/Plugins/GeneratorProvider/AspNetCoreMvc/src/AspNetCoreMvc.csproj
- src/Plugins/HostingProvider/AzureAppService/src/AzureAppService.csproj
- src/Plugins/RepositoryProvider/GitHub/src/GitHub.csproj
- src/Plugins/TestProvider/DotNetCoreTest/src/DotNetCoreTest.csproj
Add API endpoint to check version. It will display application version which is configured by build server. It will always display the same value in local dev.
> Add endpoint to check version

- src/CLI/Polyrific.Catapult.Cli.Infrastructure/ApiServiceInjection.cs
- src/CLI/Polyrific.Catapult.Cli/CommandRegistration.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/VersionCommand.cs
- src/Shared/Polyrific.Catapult.Shared.ApiClient/ApiClient.cs
- src/Shared/Polyrific.Catapult.Shared.ApiClient/VersionService.cs
- src/Shared/Polyrific.Catapult.Shared.Service/IVersionService.cs
- tests/Polyrific.Catapult.Cli.UnitTests/Commands/VersionCommandTest.cs
Add command to check version of the components.
> Add command to check version

- src/CLI/Polyrific.Catapult.Cli/Commands/Model/AddCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Model/ListCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Model/RemoveCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Model/UpdateCommand.cs
- tests/Polyrific.Catapult.Cli.UnitTests/Commands/ModelCommandTests.cs
Add intro message to Model commands
> Add intro message to Model commands

- src/API/Polyrific.Catapult.Api/Controllers/VersionController.cs
- src/API/Polyrific.Catapult.Api/SerilogRequestLogger.cs
- src/API/Polyrific.Catapult.Api/Startup.cs
Add user to the log so we can trace the requestor.
> Add user to the log

- src/API/Polyrific.Catapult.Api.Data/EntityConfigs/PluginAdditionalConfigConfig.cs
- src/API/Polyrific.Catapult.Api.Data/Migrations/20181022024505_AddGeneratorAdditionalConfig.Designer.cs
- src/API/Polyrific.Catapult.Api.Data/Migrations/20181022024505_AddGeneratorAdditionalConfig.cs
- src/Plugins/GeneratorProvider/AspNetCoreMvc/plugin.yml
- src/Plugins/GeneratorProvider/AspNetCoreMvc/src/Helpers/ProjectHelper.cs
- src/Plugins/GeneratorProvider/AspNetCoreMvc/src/ProjectGenerators/CoreProjectGenerator.cs
- src/Plugins/GeneratorProvider/AspNetCoreMvc/src/ProjectGenerators/DataProjectGenerator.cs
- src/Plugins/GeneratorProvider/AspNetCoreMvc/src/ProjectGenerators/MainProjectGenerator.cs
> Add adminemail additional config

- src/API/Polyrific.Catapult.Api.Core/Entities/ProjectMember.cs
- src/API/Polyrific.Catapult.Api.Core/Specifications/ProjectMemberFilterSpecification.cs
- src/API/Polyrific.Catapult.Api.Data/BaseRepository.cs
- src/API/Polyrific.Catapult.Api.Data/EntityConfigs/ProjectMemberConfig.cs
- src/API/Polyrific.Catapult.Api.Data/ProjectMemberRepository.cs
- src/API/Polyrific.Catapult.Api/AutoMapperProfiles/ProjectMemberAutoMapperProfile.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Member/ListCommand.cs
- src/Shared/Polyrific.Catapult.Shared.Dto/ProjectMember/ProjectMemberDto.cs
Show username and role name in member list command instead of only Ids
-  #115
> Show username and role name in member list command

- src/API/Polyrific.Catapult.Api.Core/Services/IProjectService.cs
- src/API/Polyrific.Catapult.Api.Core/Services/ProjectService.cs
- src/API/Polyrific.Catapult.Api/Controllers/ProjectController.cs
- src/API/Polyrific.Catapult.Api/Controllers/VersionController.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Project/ListCommand.cs
- src/Shared/Polyrific.Catapult.Shared.ApiClient/ProjectService.cs
- src/Shared/Polyrific.Catapult.Shared.Service/IProjectService.cs
- tests/Polyrific.Catapult.Cli.UnitTests/Commands/ProjectCommandTests.cs
Add option to get all project for admin in `project list` command
- #122
> Add option to allow get all project for admin

- src/API/Polyrific.Catapult.Api.Core/Services/JobQueueService.cs
- src/API/Polyrific.Catapult.Api.Core/Specifications/JobQueueFilterSpecification.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Queue/RestartCommand.cs
- src/Engine/Polyrific.Catapult.Engine.Core/CatapultEngine.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/PushTask.cs
- src/Engine/Polyrific.Catapult.Engine.Core/TaskRunner.cs
- src/Engine/Polyrific.Catapult.Engine.Core/TaskRunnerResult.cs
- tests/Polyrific.Catapult.Engine.UnitTests/Core/TaskRunnerTests.cs
Fix the CLI, API, and Engine for merging PR flow:
> Fix engine merge

- src/CLI/Polyrific.Catapult.Cli/Commands/Plugin/GetCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Plugin/ListCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Plugin/RegisterCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Plugin/RemoveCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Property/AddCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Property/ListCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Property/RemoveCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Property/UpdateCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Queue/AddCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Queue/GetCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Queue/ListCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Queue/RestartCommand.cs
- tests/Polyrific.Catapult.Cli.UnitTests/Commands/PluginCommandTests.cs
- tests/Polyrific.Catapult.Cli.UnitTests/Commands/PropertyCommandTests.cs
- tests/Polyrific.Catapult.Cli.UnitTests/Commands/QueueCommandTests.cs
Add intro message to plugin, property and queue commands
- #91
> add intro message to plugin, property, and queue commands

- src/CLI/Polyrific.Catapult.Cli/Commands/BaseCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Program.cs
- src/Engine/Polyrific.Catapult.Engine/Commands/BaseCommand.cs
- src/Engine/Polyrific.Catapult.Engine/Program.cs
For consistency, I change the command to return "0" if success, and "1" when failed.
> Fix return value for CLI and Engine commands

- src/CLI/Polyrific.Catapult.Cli/Commands/Engine/ActivateCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Engine/GetCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Engine/ListCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Engine/RegisterCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Engine/RemoveCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Engine/SuspendCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Engine/TokenCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Job/AddCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Job/ListCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Job/RemoveCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Service/AddCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Service/GetCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Service/ListCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Service/RemoveCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Service/UpdateCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Task/AddCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Task/GetCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Task/ListCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Task/UpdateCommand.cs
- tests/Polyrific.Catapult.Cli.UnitTests/Commands/EngineCommandTests.cs
- tests/Polyrific.Catapult.Cli.UnitTests/Commands/JobCommandTests.cs
- tests/Polyrific.Catapult.Cli.UnitTests/Commands/ServiceCommandTests.cs
- tests/Polyrific.Catapult.Cli.UnitTests/Commands/TaskCommandTest.cs
Add intro messages in engine, job, service, and task command.
- #91
> Add intro messages in remaining commands

- src/CLI/Polyrific.Catapult.Cli/Commands/Task/AddCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Task/RemoveCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Task/UpdateCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/TaskCommand.cs
- tests/Polyrific.Catapult.Cli.UnitTests/Commands/TaskCommandTest.cs
During testing I found the need to sometimes remove the task. This PR implement the command to remove a task of a job definition
> Implement task remove command

- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/BaseJobTask.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/GenerateTask.cs
- src/Plugins/GeneratorProvider/AspNetCoreMvc/src/Helpers/ProjectHelper.cs
- src/Plugins/GeneratorProvider/AspNetCoreMvc/src/ProjectGenerators/CoreProjectGenerator.cs
- src/Plugins/GeneratorProvider/AspNetCoreMvc/src/ProjectGenerators/DataProjectGenerator.cs
- src/Plugins/GeneratorProvider/AspNetCoreMvc/src/ProjectGenerators/InfrastructureProjectGenerator.cs
- src/Plugins/GeneratorProvider/AspNetCoreMvc/src/ProjectGenerators/MainProjectGenerator.cs
Allow the generator to remove the files related to model that has been deleted/renamed
> Generator: allow delete/rename model

- src/API/Polyrific.Catapult.Api.Core/Services/CatapultEngineService.cs
- src/API/Polyrific.Catapult.Api.Core/Services/ICatapultEngineService.cs
- src/API/Polyrific.Catapult.Api/Controllers/JobQueueController.cs
- tests/Polyrific.Catapult.Api.UnitTests/Core/Services/CatapultEngineServiceTests.cs
Update Engine's Last Seen value when checking for job queue.
- https://github.com/Polyrific-Inc/OpenCatapult/issues/150
> Update Engine's Last Seen value

- src/Shared/Polyrific.Catapult.Shared.ApiClient/ApiClient.cs
Show descriptive error message when the CLI/Engine is getting http error from the API
- #140
> Show descriptive error message upon getting http error from API

- src/CLI/Polyrific.Catapult.Cli/Commands/Service/AddCommand.cs
Modify the wording in `service add --help`
- #143
> Modify wording in add service help

- src/CLI/Polyrific.Catapult.Cli/Commands/Job/UpdateCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/JobCommand.cs
- tests/Polyrific.Catapult.Cli.UnitTests/Commands/JobCommandTests.cs
Add update job command to rename the job definition name
- #145
> Add update job command

- builds/build-api.ps1
- builds/build-cli.ps1
- builds/build-engine.ps1
- builds/build-prerequisites.ps1
- builds/dotnet-install.ps1
Add build scripts for:
Note: a build script which combines all scripts will be added later
> Add buid scripts

- builds/build-api.ps1
- builds/build-cli.ps1
- builds/build-engine.ps1
Update build scripts to `publish` the projects instead of `build`.
> Update build scripts to publish the projects

- src/API/Polyrific.Catapult.Api.Core/Services/UserService.cs
- src/API/Polyrific.Catapult.Api/Controllers/AccountController.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Account/Password/ResetCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Account/Password/ResetTokenCommand.cs
- src/Shared/Polyrific.Catapult.Shared.ApiClient/AccountService.cs
- src/Shared/Polyrific.Catapult.Shared.Dto/User/ResetPasswordDto.cs
- src/Shared/Polyrific.Catapult.Shared.Service/IAccountService.cs
- tests/Polyrific.Catapult.Api.UnitTests/Controllers/AccountControllerTests.cs
- tests/Polyrific.Catapult.Cli.UnitTests/Commands/AccountCommandTests.cs
Fix error unauthorized in reset password
- #170
> Fix reset password unauthorized

- .dockerignore
- Polyrific.Catapult.Api.sln
- docker-compose.dcproj
- docker-compose.override.yml
- docker-compose.yml
- src/API/Polyrific.Catapult.Api/Dockerfile
- src/API/Polyrific.Catapult.Api/Polyrific.Catapult.Api.csproj
Add docker support for API service.
> Add docker support for API

- src/API/Polyrific.Catapult.Api/Controllers/ExternalServiceController.cs
- src/API/Polyrific.Catapult.Api/Controllers/ProjectController.cs
- src/API/Polyrific.Catapult.Api/Controllers/ProjectMemberController.cs
- tests/Polyrific.Catapult.Api.UnitTests/Controllers/CatapultEngineControllerTests.cs
- tests/Polyrific.Catapult.Api.UnitTests/Controllers/ExternalServiceControllerTests.cs.cs
- tests/Polyrific.Catapult.Api.UnitTests/Controllers/ExternalServiceTypeControllerTests.cs
- tests/Polyrific.Catapult.Api.UnitTests/Controllers/HealthControllerTests.cs
- tests/Polyrific.Catapult.Api.UnitTests/Controllers/JobDefinitionControllerTests.cs
- tests/Polyrific.Catapult.Api.UnitTests/Controllers/JobQueueControllerTests.cs
- tests/Polyrific.Catapult.Api.UnitTests/Controllers/PluginControllerTests.cs
- tests/Polyrific.Catapult.Api.UnitTests/Controllers/ProjectControllerTests.cs
- tests/Polyrific.Catapult.Api.UnitTests/Controllers/ProjectDataModelControllerTests.cs
- tests/Polyrific.Catapult.Api.UnitTests/Controllers/ProjectMemberControllerTests.cs
- tests/Polyrific.Catapult.Api.UnitTests/Controllers/TokenControllerTests.cs
- tests/Polyrific.Catapult.Api.UnitTests/Controllers/VersionControllerTests.cs
- tests/Polyrific.Catapult.Api.UnitTests/Utilities/AutoMapperUtils.cs
Implement all controllers' unit test
- #162
> Implement controller unit test

- src/API/Polyrific.Catapult.Api.Core/Services/ProjectDataModelService.cs
- Add default label when adding property
- Include the `RelatedProjectDataModel` when getting property
> Fix data model property

- src/Plugins/GeneratorProvider/AspNetCoreMvc/src/ProjectGenerators/CoreProjectGenerator.cs
- src/Plugins/GeneratorProvider/AspNetCoreMvc/src/ProjectGenerators/MainProjectGenerator.cs
Fix the AspNetCoreMvc plugin not generating the service interface code, making the generated code error when build
- #179
> Fix generator does not generate service interface code

- src/CLI/Polyrific.Catapult.Cli/Commands/Task/AddCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Task/UpdateCommand.cs
- src/Plugins/RepositoryProvider/GitHub/src/CodeRepositoryProvider.cs
- src/Plugins/RepositoryProvider/GitHub/tests/CodeRepositoryProviderTests.cs
Fix unhandled exception on github plugin occured when all optional config is not set
- #180
> Fix unhandled exception on github plugin

- src/Engine/Polyrific.Catapult.Engine.Core/JobLogger/JobLogger.cs
Write exception detail into the log that is sent to signalR hub
- #181
> Write exception detail into signalR log

- src/API/Polyrific.Catapult.Api.Data/EntityConfigs/ExternalServicePropertyConfig.cs
- src/API/Polyrific.Catapult.Api.Data/Migrations/20181112040758_FixExternalServiceProperty.Designer.cs
- src/API/Polyrific.Catapult.Api.Data/Migrations/20181112040758_FixExternalServiceProperty.cs
- src/API/Polyrific.Catapult.Api.SecretVault/SecretVault.cs
- src/Shared/Polyrific.Catapult.Shared.Common/LocalTextWriter.cs
- Fix an error that occured when the external service cannot get the service vault file
- Fix external service properties seed
> Fixes in external service

- src/Plugins/GeneratorProvider/AspNetCoreMvc/src/CodeGenerator.cs
- src/Plugins/GeneratorProvider/AspNetCoreMvc/src/Helpers/ProjectHelper.cs
- src/Plugins/GeneratorProvider/AspNetCoreMvc/src/ProjectGenerators/CoreProjectGenerator.cs
- src/Plugins/GeneratorProvider/AspNetCoreMvc/src/ProjectGenerators/DataProjectGenerator.cs
- src/Plugins/GeneratorProvider/AspNetCoreMvc/src/ProjectGenerators/MainProjectGenerator.cs
- Fix error that occured when there's "space" character in the working folder path
- Fix error that occured when there's custom User model in the project model definition
> Fix generator for sample project

- src/Plugins/RepositoryProvider/GitHub/src/CodeRepositoryProvider.cs
- src/Plugins/RepositoryProvider/GitHub/src/GitAutomation.cs
Fix error in Push when target branch and/or working branch are not specified.
> Fix github plugin when target/working branch are not specified

- src/CLI/Polyrific.Catapult.Cli/Commands/Project/CreateCommand.cs
- src/Plugins/BuildProvider/DotNetCore/src/BuildProvider.cs
- src/Plugins/BuildProvider/DotNetCore/src/Builder.cs
- src/Plugins/DatabaseProvider/EntityFrameworkCore/src/DatabaseProvider.cs
- Fix build process failed because publish folder not found
- Fix error when build path have spaces
- Fix error when the additional config is set to null/empty
- Fix Create Project saving null/empty additional config (CLI)
> Fix build plugin

- src/Plugins/Polyrific.Catapult.Plugins.Abstraction/Polyrific.Catapult.Plugins.Abstraction.nuspec
> Fix included files in nuspec

- src/Plugins/GeneratorProvider/AspNetCoreMvc/src/ProjectGenerators/MainProjectGenerator.cs
Override the generated home page from `dotnet new` with the opencatapult home page
> Update generated home page

- src/CLI/Polyrific.Catapult.Cli/Templates/sample.yaml
Update the `sample.yaml` template based on latest changes in the code.
Note: we should add a note in the docs to have user update the Repository config for task Clone, Push, and Merge, since the one in the template is dummy.
> Update sample template based on latest changes

- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/BaseJobTask.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/BuildTask.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/GenerateTask.cs
- src/Engine/Polyrific.Catapult.Engine.Core/PluginManager.cs
- src/Plugins/BuildProvider/Polyrific.Catapult.Plugins.DotNetCore/src/Program.cs
- src/Plugins/GeneratorProvider/Polyrific.Catapult.Plugins.AspNetCoreMvc/src/Program.cs
- src/Plugins/Polyrific.Catapult.Plugins.Core/BuildTaskProvider.cs
- src/Plugins/Polyrific.Catapult.Plugins.Core/GenerateTaskProvider.cs
- src/Plugins/Polyrific.Catapult.Plugins.Core/TaskProvider.cs
> Add debugging capability to plugin & fix plugin args

- src/API/Polyrific.Catapult.Api/Controllers/PluginController.cs
- src/API/Polyrific.Catapult.Api/Identity/AuthorizePolicy.cs
- src/API/Polyrific.Catapult.Api/Startup.cs
- src/Engine/Polyrific.Catapult.Engine.Core/IPluginManager.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/BaseJobTask.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/BuildTask.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/CloneTask.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/DeployDbTask.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/DeployTask.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/GenerateTask.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/IJobTask.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/MergeTask.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/PublishArtifactTask.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/PushTask.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/TestTask.cs
- src/Engine/Polyrific.Catapult.Engine.Core/PluginManager.cs
- src/Engine/Polyrific.Catapult.Engine.Core/TaskRunner.cs
- src/Engine/Polyrific.Catapult.Engine.Infrastructure/ApiServiceInjection.cs
- tests/Polyrific.Catapult.Engine.UnitTests/Core/JobTasks/BuildTaskTests.cs
- tests/Polyrific.Catapult.Engine.UnitTests/Core/JobTasks/CloneTaskTests.cs
- tests/Polyrific.Catapult.Engine.UnitTests/Core/JobTasks/DeployDbTaskTests.cs
- tests/Polyrific.Catapult.Engine.UnitTests/Core/JobTasks/DeployTaskTests.cs
- tests/Polyrific.Catapult.Engine.UnitTests/Core/JobTasks/GenerateTaskTests.cs
- tests/Polyrific.Catapult.Engine.UnitTests/Core/JobTasks/MergeTaskTests.cs
- tests/Polyrific.Catapult.Engine.UnitTests/Core/JobTasks/PublishArtifactTaskTests.cs
- tests/Polyrific.Catapult.Engine.UnitTests/Core/JobTasks/PushTaskTests.cs
- tests/Polyrific.Catapult.Engine.UnitTests/Core/JobTasks/TestTaskTests.cs
In plugin v2, we need to show the arguments passed into the plugin, while also hide the secret information
> Hide secret values when showing plugin command arguments

- src/Engine/Polyrific.Catapult.Engine.Core/IPluginManager.cs
- src/Engine/Polyrific.Catapult.Engine.Core/IPluginProcess.cs
- src/Engine/Polyrific.Catapult.Engine.Core/PluginManager.cs
- src/Engine/Polyrific.Catapult.Engine.Core/PluginProcess.cs
- src/Engine/Polyrific.Catapult.Engine/Program.cs
- src/Plugins/BuildProvider/Polyrific.Catapult.Plugins.DotNetCore/tests/BuildProviderTests.cs
- tests/Polyrific.Catapult.Engine.UnitTests/Core/PluginManagerTests.cs
Implement unit test for method `RefreshPlugins` and `InvokeTaskProvider`
> Plugin manager unit test

- builds/build-engine.ps1
Update `build-engine.ps1` to use the new plugin names.
> Update plugin names in build script

- src/Plugins/Polyrific.Catapult.Plugins.Core/Polyrific.Catapult.Plugins.Core.csproj
- src/Plugins/Polyrific.Catapult.Plugins.Core/Polyrific.Catapult.Plugins.Core.nuspec
- src/Shared/Polyrific.Catapult.Shared.Dto/Polyrific.Catapult.Shared.Dto.csproj
Add `net461` as target framework for the following projects:
- Polyrific.Catapult.Plugins.Core
- Polyrific.Catapult.Shared.Dto
> Add target framework for NuGet package

- src/API/Polyrific.Catapult.Api.Core/Entities/ProjectDataModel.cs
- src/API/Polyrific.Catapult.Api.Core/Entities/ProjectDataModelProperty.cs
- src/API/Polyrific.Catapult.Api.Core/Services/IProjectDataModelService.cs
- src/API/Polyrific.Catapult.Api.Core/Services/ProjectDataModelService.cs
- src/API/Polyrific.Catapult.Api.Data/Migrations/20181211071906_AddIsManagedAndSelectKey.Designer.cs
- src/API/Polyrific.Catapult.Api.Data/Migrations/20181211071906_AddIsManagedAndSelectKey.cs
- src/API/Polyrific.Catapult.Api/Controllers/ProjectDataModelController.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Model/AddCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Model/UpdateCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Property/AddCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Property/UpdateCommand.cs
- src/Shared/Polyrific.Catapult.Shared.Dto/ProjectDataModel/CreateProjectDataModelDto.cs
- src/Shared/Polyrific.Catapult.Shared.Dto/ProjectDataModel/CreateProjectDataModelPropertyDto.cs
- src/Shared/Polyrific.Catapult.Shared.Dto/ProjectDataModel/ProjectDataModelDto.cs
- src/Shared/Polyrific.Catapult.Shared.Dto/ProjectDataModel/ProjectDataModelPropertyDto.cs
- src/Shared/Polyrific.Catapult.Shared.Dto/ProjectDataModel/UpdateProjectDataModelDto.cs
- src/Shared/Polyrific.Catapult.Shared.Dto/ProjectDataModel/UpdateProjectDataModelPropertyDto.cs
- tests/Polyrific.Catapult.Api.UnitTests/Controllers/ProjectDataModelControllerTests.cs
- tests/Polyrific.Catapult.Api.UnitTests/Core/Services/ProjectDataModelServiceTests.cs
Add IsManaged and SelectKey to model and property. It'll be used in the AspNetWeb generator.
> Add ismanaged and selectkey to model

- src/API/Polyrific.Catapult.Api.Core/Entities/PluginAdditionalConfig.cs
- src/API/Polyrific.Catapult.Api.Data/Migrations/20181213143610_AdditionalConfigAllowedValues.Designer.cs
- src/API/Polyrific.Catapult.Api.Data/Migrations/20181213143610_AdditionalConfigAllowedValues.cs
- src/API/Polyrific.Catapult.Api/AutoMapperProfiles/PluginAdditionalConfigAutoMapperProfile.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Project/CreateCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Task/AddCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Task/UpdateCommand.cs
- src/Shared/Polyrific.Catapult.Shared.Dto/Constants/PluginAdditionalConfigType.cs
- src/Shared/Polyrific.Catapult.Shared.Dto/Plugin/PluginAdditionalConfigDto.cs
- Validate the additional config against the type (string, number, boolean)
- Add allowed values to the additional config and validate it in the CLI
> Add validation for additional config type and allowed values

- src/Engine/Polyrific.Catapult.Engine.Core/IPluginProcess.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/BuildTask.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/CloneTask.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/DeployDbTask.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/DeployTask.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/GenerateTask.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/MergeTask.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/PublishArtifactTask.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/PushTask.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/TestTask.cs
- src/Engine/Polyrific.Catapult.Engine.Core/PluginManager.cs
- src/Engine/Polyrific.Catapult.Engine.Core/PluginProcess.cs
- src/Plugins/Polyrific.Catapult.Plugins.Core/BuildProvider.cs
- src/Plugins/Polyrific.Catapult.Plugins.Core/CodeGeneratorProvider.cs
- src/Plugins/Polyrific.Catapult.Plugins.Core/DatabaseProvider.cs
- src/Plugins/Polyrific.Catapult.Plugins.Core/HostingProvider.cs
- src/Plugins/Polyrific.Catapult.Plugins.Core/RepositoryProvider.cs
- src/Plugins/Polyrific.Catapult.Plugins.Core/StorageProvider.cs
- src/Plugins/Polyrific.Catapult.Plugins.Core/TestProvider.cs
- tests/Polyrific.Catapult.Engine.UnitTests/Core/PluginManagerTests.cs
Catch the unhandled exception error message thrown inside the plugin, so the task can be marked as failed
> Catch unhandled exception error happened in the plugin

- src/Engine/Polyrific.Catapult.Engine/Commands/Config/SetCommand.cs
Truncate/mask authorization token in engine log
> Truncate/mask AuthorizationToken engine config

- src/API/Polyrific.Catapult.Api.Core/Repositories/IJobTaskDefinitionRepository.cs
- src/API/Polyrific.Catapult.Api.Core/Services/JobDefinitionService.cs
- src/API/Polyrific.Catapult.Api.Data/JobTaskDefinitionRepository.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Project/CreateCommand.cs
- tests/Polyrific.Catapult.Api.UnitTests/Core/Services/JobDefinitionServiceTests.cs
Set default task sequence when adding task(s)
> set default sequence when adding task

- src/CLI/Polyrific.Catapult.Cli/Commands/Config/GetCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Config/ImportCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Config/RemoveCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Config/SetCommand.cs
- src/Engine/Polyrific.Catapult.Engine/Commands/Config/GetCommand.cs
- src/Engine/Polyrific.Catapult.Engine/Commands/Config/ImportCommand.cs
- src/Engine/Polyrific.Catapult.Engine/Commands/Config/RemoveCommand.cs
- src/Engine/Polyrific.Catapult.Engine/Commands/Config/SetCommand.cs
Fix config command that occasionally does not save to the file correctly
> Fix engine/cli config not set properly

- builds/build-api.ps1
- builds/build-cli.ps1
- builds/build-engine.ps1
- src/API/Polyrific.Catapult.Api/Polyrific.Catapult.Api.csproj
Fix paths to be compatible for Win, Mac, and Linux environments.
> Fix build scripts for xplat compat

- src/Plugins/GeneratorProvider/Polyrific.Catapult.Plugins.AspNetCoreMvc/src/ProjectGenerators/MainProjectGenerator.cs
Fix error in generator when running in linux environment due to invalid folder path
- #237
> fix path for _layout.cshtml

- src/Engine/Polyrific.Catapult.Engine.SignalRLogger/SignalRJobLogWriter.cs
There's an occasional error occured when the engine tries to send message to signalR and the connection has expired. This PR will try to start a new connection and retry when the error occured (There's currently no API to check the connection status)
> Fix error in signalR connection

- src/CLI/Polyrific.Catapult.Cli/Commands/Project/CreateCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Queue/RestartCommand.cs
- tests/Polyrific.Catapult.Cli.UnitTests/Commands/QueueCommandTests.cs
- Allow setting task's additional configs in project template yaml file.
- Allow input queue code on `queue restart` command
> Allow project template to set task additional config

- src/Engine/Polyrific.Catapult.Engine.Core/TaskRunner.cs
Set the task result return value as the job task status remark
- Related issue: #240
> Set task remark from result return value

- src/Plugins/HostingProvider/Polyrific.Catapult.Plugins.AzureAppService/src/KuduDeployUtils.cs
- src/Plugins/HostingProvider/Polyrific.Catapult.Plugins.AzureAppService/src/ProgressableStreamContent.cs
- Log error message when deploy failed
- Fix failed to deploy when the package file is too large
> Fix error occured when uploading large package

- src/CLI/Polyrific.Catapult.Cli/Commands/Service/AddCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Service/GetCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Service/ListCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Extensions/CatapultCliExtensions.cs
Rename the `Service.Config` into `Service.Properties` in CLI
- #248
> Implement name dictionary for external service config

- src/Plugins/HostingProvider/Polyrific.Catapult.Plugins.AzureAppService/src/AzureAutomation.cs
- src/Plugins/HostingProvider/Polyrific.Catapult.Plugins.AzureAppService/src/AzureUtils.cs
- Only perform retry when error occured related to connection
- Fix issue where the provider hangs when an error occured
- #252
> Prevent hosting provider hang

- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/PushTask.cs
- src/Engine/Polyrific.Catapult.Engine.Core/TaskRunner.cs
- src/Engine/Polyrific.Catapult.Engine.Core/TaskRunnerResult.cs
- src/Plugins/Polyrific.Catapult.Plugins.Core/RepositoryProvider.cs
- src/Plugins/RepositoryProvider/Polyrific.Catapult.Plugins.GitHub/src/Program.cs
- src/Plugins/RepositoryProvider/Polyrific.Catapult.Plugins.GitHub/tests/CodeRepositoryProviderTests.cs
Show Repository Url and PR Url for Success and Pending task, respectively:
- #251
> Show PR Url for pending repo task

- tests/Polyrific.Catapult.Engine.UnitTests/Core/PluginManagerTests.cs
Add unit test for .exe plugin in engine
- #220
> Add unit test for .exe plugin

- builds/build-prerequisites.ps1
Check whether the local machine have sql server installed. If it's installed but the service stopped, ask the if she wants to start it.
- #263
> Check for sql server instance in local machine

- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/BuildTask.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/CloneTask.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/DeployDbTask.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/DeployTask.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/GenerateTask.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/MergeTask.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/PublishArtifactTask.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/PushTask.cs
- src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/TestTask.cs
- src/Engine/Polyrific.Catapult.Engine.Core/TaskRunner.cs
- src/Engine/Polyrific.Catapult.Engine.Core/TaskRunnerResult.cs
- src/Plugins/DatabaseProvider/Polyrific.Catapult.Plugins.EntityFrameworkCore/src/Polyrific.Catapult.Plugins.EntityFrameworkCore.csproj
- src/Plugins/DatabaseProvider/Polyrific.Catapult.Plugins.EntityFrameworkCore/src/Program.cs
- src/Plugins/DatabaseProvider/Polyrific.Catapult.Plugins.EntityFrameworkCore/tests/DatabaseProviderTests.cs
- tests/Polyrific.Catapult.Engine.UnitTests/Core/JobTasks/BuildTaskTests.cs
- tests/Polyrific.Catapult.Engine.UnitTests/Core/JobTasks/CloneTaskTests.cs
- tests/Polyrific.Catapult.Engine.UnitTests/Core/JobTasks/DeployDbTaskTests.cs
- tests/Polyrific.Catapult.Engine.UnitTests/Core/JobTasks/DeployTaskTests.cs
- tests/Polyrific.Catapult.Engine.UnitTests/Core/JobTasks/GenerateTaskTests.cs
- tests/Polyrific.Catapult.Engine.UnitTests/Core/JobTasks/MergeTaskTests.cs
- tests/Polyrific.Catapult.Engine.UnitTests/Core/JobTasks/PublishArtifactTaskTests.cs
- tests/Polyrific.Catapult.Engine.UnitTests/Core/JobTasks/PushTaskTests.cs
- tests/Polyrific.Catapult.Engine.UnitTests/Core/JobTasks/TestTaskTests.cs
Add additional explanation in the job task remark to make the context more clear
> Improve job task remark when success

- src/API/Polyrific.Catapult.Api/Polyrific.Catapult.Api.csproj
- src/CLI/Polyrific.Catapult.Cli/Polyrific.Catapult.Cli.csproj
- src/Engine/Polyrific.Catapult.Engine/Polyrific.Catapult.Engine.csproj
- src/Plugins/BuildProvider/Polyrific.Catapult.Plugins.DotNetCore/plugin.yml
- src/Plugins/DatabaseProvider/Polyrific.Catapult.Plugins.EntityFrameworkCore/plugin.yml
- src/Plugins/GeneratorProvider/Polyrific.Catapult.Plugins.AspNetCoreMvc/plugin.yml
- src/Plugins/HostingProvider/Polyrific.Catapult.Plugins.AzureAppService/plugin.yml
- src/Plugins/Polyrific.Catapult.Plugins.Core/Polyrific.Catapult.Plugins.Core.nuspec
- src/Plugins/RepositoryProvider/Polyrific.Catapult.Plugins.GitHub/plugin.yml
- src/Plugins/TestProvider/Polyrific.Catapult.Plugins.DotNetCoreTest/plugin.yml
- src/Shared/Polyrific.Catapult.Shared.Dto/Polyrific.Catapult.Shared.Dto.csproj
Change component version to `1.0.0-beta1`.
> Change component version to `1.0.0-beta1`

- src/Plugins/RepositoryProvider/Polyrific.Catapult.Plugins.GitHub/src/GitAutomation.cs
- src/Plugins/RepositoryProvider/Polyrific.Catapult.Plugins.GitHub/src/GitAutomationConfig.cs
- src/Plugins/RepositoryProvider/Polyrific.Catapult.Plugins.GitHub/src/GitHubUtils.cs
- src/Plugins/RepositoryProvider/Polyrific.Catapult.Plugins.GitHub/src/IGitAutomation.cs
- src/Plugins/RepositoryProvider/Polyrific.Catapult.Plugins.GitHub/src/IGitHubUtils.cs
- src/Plugins/RepositoryProvider/Polyrific.Catapult.Plugins.GitHub/src/Program.cs
Create repository automatically if it's not exists in Clone or Push task of GitHub repository plugin
- #269
> Create repository in GitHub plugin

- builds/build-all.ps1
- builds/build-prerequisites.ps1
Create a single build script that shall run API, CLI, and Engine.
- #273
> Create single build script to run all builds

- src/Plugins/GeneratorProvider/Polyrific.Catapult.Plugins.AspNetCoreMvc/src/ProjectGenerators/DataProjectGenerator.cs
When generating sample project, the migrated database create two table user: `users` and `user`. We need to modify the EntityConfigs for model that are related to user table, so that it uses the identity model `ApplicationUser`
> generator: Fix migration script include two user table

- builds/build-prerequisites.ps1
When the windows powershell require the administrator privilege, ask the user whether to exit the process, or continue without doing the action that require the admin.
- #304
> Show prompt to continue or exit when needing admin in build prerequisites

- src/Plugins/RepositoryProvider/Polyrific.Catapult.Plugins.GitHub/src/GitHubUtils.cs
Fix error in repository provider that occurs when trying to create a repository for the user, instead of an organization
> Fix create repository for user instead of org

- builds/build-all.ps1
- builds/build-api.ps1
- builds/build-cli.ps1
- builds/build-engine.ps1
Some little improvements on build scripts:
- re-arrange message order
- give color to some messages
- rename methods with approved verbs
> Some little improvements on build scripts

- docs/task-providers/hosting-provider.md
Add AllowAutomaticRename  additional config into AzureAppService provider documentation
> docs: update hosting provider additional config

- src/API/Polyrific.Catapult.Api.Core/AutoMapperProfiles/ProjectTemplateAutoMapperProfile.cs
- src/API/Polyrific.Catapult.Api.Core/Entities/Project.cs
- src/API/Polyrific.Catapult.Api.Core/Entities/ProjectTemplate.cs
- src/API/Polyrific.Catapult.Api.Core/Services/IProjectService.cs
- src/API/Polyrific.Catapult.Api.Core/Services/ProjectService.cs
- src/API/Polyrific.Catapult.Api.Data/Migrations/20190213052546_AddProjectDisplayName.Designer.cs
- src/API/Polyrific.Catapult.Api.Data/Migrations/20190213052546_AddProjectDisplayName.cs
- src/API/Polyrific.Catapult.Api.Data/Migrations/20190213052633_RemoveProjectConfigString.Designer.cs
- src/API/Polyrific.Catapult.Api.Data/Migrations/20190213052633_RemoveProjectConfigString.cs
- src/API/Polyrific.Catapult.Api/AutoMapperProfiles/ProjectAutoMapperProfile.cs
- src/API/Polyrific.Catapult.Api/Controllers/ProjectController.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Project/CreateCommand.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Project/UpdateCommand.cs
- src/Shared/Polyrific.Catapult.Shared.Dto/Project/NewProjectDto.cs
- src/Shared/Polyrific.Catapult.Shared.Dto/Project/ProjectDto.cs
- src/Shared/Polyrific.Catapult.Shared.Dto/Project/UpdateProjectDto.cs
- tests/Polyrific.Catapult.Api.UnitTests/Controllers/ProjectControllerTests.cs
- tests/Polyrific.Catapult.Api.UnitTests/Core/Services/ProjectServiceTests.cs
- Add DisplayName property in project
- Remove ConfigString property in project
- Update CLI to reflect changes in API
> Modify project fields

- src/Web/opencatapultweb/src/app/app.module.ts
- src/Web/opencatapultweb/src/app/core/models/project-dto.ts
- src/Web/opencatapultweb/src/app/core/services/api.service.ts
- src/Web/opencatapultweb/src/app/core/services/project.service.ts
- src/Web/opencatapultweb/src/app/login/login.component.css
- src/Web/opencatapultweb/src/app/login/login.component.html
- src/Web/opencatapultweb/src/app/project/components/project-info-form/project-info-form.component.css
- src/Web/opencatapultweb/src/app/project/components/project-info-form/project-info-form.component.html
- src/Web/opencatapultweb/src/app/project/components/project-info-form/project-info-form.component.spec.ts
- src/Web/opencatapultweb/src/app/project/components/project-info-form/project-info-form.component.ts
- src/Web/opencatapultweb/src/app/project/project-detail/project-detail.component.html
- src/Web/opencatapultweb/src/app/project/project-info/project-info.component.css
- src/Web/opencatapultweb/src/app/project/project-info/project-info.component.html
- src/Web/opencatapultweb/src/app/project/project-info/project-info.component.ts
- src/Web/opencatapultweb/src/app/project/project.module.ts
- src/Web/opencatapultweb/src/app/project/project/project.component.css
- src/Web/opencatapultweb/src/app/project/project/project.component.html
- src/Web/opencatapultweb/src/styles.css
Implement project info update page
- #320
> Project info web ui

- src/CLI/Polyrific.Catapult.Cli/Commands/Queue/LogCommand.cs
Add `--wait` option to the `queue log` command to wait for the log stream to coming through.
- Related Issues: https://github.com/Polyrific-Inc/OpenCatapult/issues/318
> Add wait option for queue log command

- src/Web/opencatapultweb/src/app/core/interceptors/jwt.interceptor.ts
- src/Web/opencatapultweb/src/app/core/services/project.service.ts
- src/Web/opencatapultweb/src/app/project/project-detail/project-detail.component.html
- src/Web/opencatapultweb/src/app/project/project-detail/project-detail.component.ts
- src/Web/opencatapultweb/src/app/project/project-new/project-new.component.ts
- src/Web/opencatapultweb/src/app/project/project.module.ts
- src/Web/opencatapultweb/src/app/shared/components/confirmation-with-input-dialog/confirmation-with-input-dialog.component.html
- src/Web/opencatapultweb/src/app/shared/components/confirmation-with-input-dialog/confirmation-with-input-dialog.component.spec.ts
- src/Web/opencatapultweb/src/app/shared/components/confirmation-with-input-dialog/confirmation-with-input-dialog.component.ts
- src/Web/opencatapultweb/src/app/shared/index.ts
- src/Web/opencatapultweb/src/app/shared/shared.module.ts
Implement the web ui for deleting a project
> Implement delete project web ui

- src/Web/opencatapultweb/e2e/src/app.e2e-spec.ts
Fix the end to end test so it all passed
- Related Issues: #320 
- Related Work Items:
- Other links:
> Fix end to end test in web ui

- src/Web/opencatapultweb/src/app/project/project-info/project-info.component.html
- src/Web/opencatapultweb/src/app/project/project-info/project-info.component.ts
- src/Web/opencatapultweb/src/environments/environment.prod.ts
I got some errors when running `npm run build-prod` because of incomplete properties in some objects. This PR adds those missing properties.
> Add more properties to prevent build error

- src/Web/opencatapultweb/src/app/core/services/project.service.ts
- src/Web/opencatapultweb/src/app/project/project-archive-detail/project-archive-detail.component.html
- src/Web/opencatapultweb/src/app/project/project-archive-detail/project-archive-detail.component.spec.ts
- src/Web/opencatapultweb/src/app/project/project-archive-detail/project-archive-detail.component.ts
- src/Web/opencatapultweb/src/app/project/project-detail/project-detail.component.html
- src/Web/opencatapultweb/src/app/project/project-detail/project-detail.component.ts
- src/Web/opencatapultweb/src/app/project/project-info/project-info.component.ts
- src/Web/opencatapultweb/src/app/project/project-routing.module.ts
- src/Web/opencatapultweb/src/app/project/project.module.ts
- src/Web/opencatapultweb/src/app/project/project/project.component.html
- src/Web/opencatapultweb/src/app/shared/components/confirmation-dialog/confirmation-dialog.component.html
- src/Web/opencatapultweb/src/app/shared/components/confirmation-dialog/confirmation-dialog.component.spec.ts
- src/Web/opencatapultweb/src/app/shared/components/confirmation-dialog/confirmation-dialog.component.ts
- src/Web/opencatapultweb/src/app/shared/components/confirmation-with-input-dialog/confirmation-with-input-dialog.component.ts
- src/Web/opencatapultweb/src/app/shared/index.ts
- src/Web/opencatapultweb/src/app/shared/shared.module.ts
Implement the archive and restore project feature in web ui
> Implement archive/restore project web ui

- src/Web/opencatapultweb/src/app/project/project-archive-detail/project-archive-detail.component.spec.ts
Fix error when running `ng test`
> Fix ng test error thrown in project archive detail

- src/Web/opencatapultweb/src/environments/environment.prod.ts
- src/Web/opencatapultweb/src/environments/environment.ts
Add `version` field to `environment.ts` to be used as application version. The value will be updated by CI to match with the build number.
> Add version field to environment.ts

- .gitignore
- src/API/Polyrific.Catapult.Api/appsettings.Development.json
Add environment settings to the `.gitignore`. This is done as preparation to make changes for https://github.com/Polyrific-Inc/OpenCatapult/issues/326.
> Add environment settings to gitignore

- builds/build-api.ps1
Instead of directly modifying `appsettings.json`, this PR makes the `build-api.ps1` script to add connection string to `appsettings.{env}.json`. It is safer for dev because the env appsettings will not be committed into source control.
- Related Issues: https://github.com/Polyrific-Inc/OpenCatapult/issues/326
> Add connection string to appsettings env

- src/Web/opencatapultweb/src/app/core/constants/project-member-roles.ts
- src/Web/opencatapultweb/src/app/core/core.module.ts
- src/Web/opencatapultweb/src/app/core/index.ts
- src/Web/opencatapultweb/src/app/core/models/account/user-dto.ts
- src/Web/opencatapultweb/src/app/core/models/member/project-member-dto.ts
- src/Web/opencatapultweb/src/app/core/models/member/update-project-member-dto.ts
- src/Web/opencatapultweb/src/app/core/services/account.service.spec.ts
- src/Web/opencatapultweb/src/app/core/services/account.service.ts
- src/Web/opencatapultweb/src/app/core/services/member.service.spec.ts
- src/Web/opencatapultweb/src/app/core/services/member.service.ts
- src/Web/opencatapultweb/src/app/project/job-queue/job-queue-list/job-queue-list.component.css
- src/Web/opencatapultweb/src/app/project/member/components/member-info-dialog/member-info-dialog.component.html
- src/Web/opencatapultweb/src/app/project/member/components/member-info-dialog/member-info-dialog.component.spec.ts
- src/Web/opencatapultweb/src/app/project/member/components/member-info-dialog/member-info-dialog.component.ts
- src/Web/opencatapultweb/src/app/project/member/components/member-new-dialog/member-new-dialog.component.css
- src/Web/opencatapultweb/src/app/project/member/components/member-new-dialog/member-new-dialog.component.html
- src/Web/opencatapultweb/src/app/project/member/components/member-new-dialog/member-new-dialog.component.spec.ts
- src/Web/opencatapultweb/src/app/project/member/components/member-new-dialog/member-new-dialog.component.ts
- src/Web/opencatapultweb/src/app/project/member/member.module.ts
- src/Web/opencatapultweb/src/app/project/member/member/member.component.css
- src/Web/opencatapultweb/src/app/project/member/member/member.component.html
- src/Web/opencatapultweb/src/app/project/member/member/member.component.spec.ts
- src/Web/opencatapultweb/src/app/project/member/member/member.component.ts
Implement project member web ui
> Project member web ui

- src/Web/opencatapultweb/src/app/core/core.module.ts
- src/Web/opencatapultweb/src/app/core/enums/engine-status.ts
- src/Web/opencatapultweb/src/app/core/index.ts
- src/Web/opencatapultweb/src/app/core/models/engine/engine-dto.ts
- src/Web/opencatapultweb/src/app/core/models/engine/engine-token-request-dto.ts
- src/Web/opencatapultweb/src/app/core/models/engine/engine-token-response-dto.ts
- src/Web/opencatapultweb/src/app/core/models/engine/register-engine-dto.ts
- src/Web/opencatapultweb/src/app/core/services/api.service.ts
- src/Web/opencatapultweb/src/app/core/services/engine.service.spec.ts
- src/Web/opencatapultweb/src/app/core/services/engine.service.ts
- src/Web/opencatapultweb/src/app/engine/components/engine-register-dialog/engine-register-dialog.component.html
- src/Web/opencatapultweb/src/app/engine/components/engine-register-dialog/engine-register-dialog.component.spec.ts
- src/Web/opencatapultweb/src/app/engine/components/engine-register-dialog/engine-register-dialog.component.ts
- src/Web/opencatapultweb/src/app/engine/components/engine-token-dialog/engine-token-dialog.component.css
- src/Web/opencatapultweb/src/app/engine/components/engine-token-dialog/engine-token-dialog.component.html
- src/Web/opencatapultweb/src/app/engine/components/engine-token-dialog/engine-token-dialog.component.spec.ts
- src/Web/opencatapultweb/src/app/engine/components/engine-token-dialog/engine-token-dialog.component.ts
- src/Web/opencatapultweb/src/app/engine/engine.module.ts
- src/Web/opencatapultweb/src/app/engine/engine/engine.component.css
- src/Web/opencatapultweb/src/app/engine/engine/engine.component.html
- src/Web/opencatapultweb/src/app/engine/engine/engine.component.ts
> Implement engine web ui

- src/Web/opencatapultweb/src/app/core/core.module.ts
- src/Web/opencatapultweb/src/app/core/index.ts
- src/Web/opencatapultweb/src/app/core/models/task-provider/register-task-provider-dto.ts
- src/Web/opencatapultweb/src/app/core/services/task-provider.service.ts
- src/Web/opencatapultweb/src/app/core/services/yaml.service.spec.ts
- src/Web/opencatapultweb/src/app/core/services/yaml.service.ts
- src/Web/opencatapultweb/src/app/project/job-definition/components/job-task-definition-form/job-task-definition-form.component.ts
- src/Web/opencatapultweb/src/app/project/project-new/project-new.component.ts
- src/Web/opencatapultweb/src/app/task-provider/components/task-provider-info-dialog/task-provider-info-dialog.component.css
- src/Web/opencatapultweb/src/app/task-provider/components/task-provider-info-dialog/task-provider-info-dialog.component.html
- src/Web/opencatapultweb/src/app/task-provider/components/task-provider-info-dialog/task-provider-info-dialog.component.spec.ts
- src/Web/opencatapultweb/src/app/task-provider/components/task-provider-info-dialog/task-provider-info-dialog.component.ts
- src/Web/opencatapultweb/src/app/task-provider/components/task-provider-register-dialog/task-provider-register-dialog.component.css
- src/Web/opencatapultweb/src/app/task-provider/components/task-provider-register-dialog/task-provider-register-dialog.component.html
- src/Web/opencatapultweb/src/app/task-provider/components/task-provider-register-dialog/task-provider-register-dialog.component.spec.ts
- src/Web/opencatapultweb/src/app/task-provider/components/task-provider-register-dialog/task-provider-register-dialog.component.ts
- src/Web/opencatapultweb/src/app/task-provider/task-provider.module.ts
- src/Web/opencatapultweb/src/app/task-provider/task-provider/task-provider.component.css
- src/Web/opencatapultweb/src/app/task-provider/task-provider/task-provider.component.html
- src/Web/opencatapultweb/src/app/task-provider/task-provider/task-provider.component.ts
- src/Web/opencatapultweb/src/styles.css
Implement task provider web ui
> Implement task provider web ui

- src/Web/opencatapultweb/src/app/account/account.module.ts
- src/Web/opencatapultweb/src/app/account/account/account.component.css
- src/Web/opencatapultweb/src/app/account/account/account.component.html
- src/Web/opencatapultweb/src/app/account/account/account.component.spec.ts
- src/Web/opencatapultweb/src/app/account/account/account.component.ts
- src/Web/opencatapultweb/src/app/account/components/user-info-dialog/user-info-dialog.component.html
- src/Web/opencatapultweb/src/app/account/components/user-info-dialog/user-info-dialog.component.spec.ts
- src/Web/opencatapultweb/src/app/account/components/user-info-dialog/user-info-dialog.component.ts
- src/Web/opencatapultweb/src/app/account/components/user-register-dialog/user-register-dialog.component.html
- src/Web/opencatapultweb/src/app/account/components/user-register-dialog/user-register-dialog.component.spec.ts
- src/Web/opencatapultweb/src/app/account/components/user-register-dialog/user-register-dialog.component.ts
- src/Web/opencatapultweb/src/app/account/components/user-set-role-dialog/user-set-role-dialog.component.html
- src/Web/opencatapultweb/src/app/account/components/user-set-role-dialog/user-set-role-dialog.component.spec.ts
- src/Web/opencatapultweb/src/app/account/components/user-set-role-dialog/user-set-role-dialog.component.ts
- src/Web/opencatapultweb/src/app/core/constants/user-roles.ts
- src/Web/opencatapultweb/src/app/core/enums/user-role.ts
- src/Web/opencatapultweb/src/app/core/enums/user-status.ts
- src/Web/opencatapultweb/src/app/core/index.ts
- src/Web/opencatapultweb/src/app/core/models/account/register-user-dto.ts
- src/Web/opencatapultweb/src/app/core/models/account/reset-password-dto.ts
- src/Web/opencatapultweb/src/app/core/models/account/set-user-role-dto.ts
- src/Web/opencatapultweb/src/app/core/models/account/update-password-dto.ts
- src/Web/opencatapultweb/src/app/core/models/account/update-user-dto.ts
- src/Web/opencatapultweb/src/app/core/services/account.service.ts
- src/Web/opencatapultweb/src/app/core/services/api.service.ts
Implement the account admin page web ui
> Implement account web ui

- src/Web/opencatapultweb/src/app/app-routing.module.ts
- src/Web/opencatapultweb/src/app/app.module.ts
- src/Web/opencatapultweb/src/app/core/services/account.service.ts
- src/Web/opencatapultweb/src/app/core/services/api.service.ts
- src/Web/opencatapultweb/src/app/header/header.component.css
- src/Web/opencatapultweb/src/app/header/header.component.html
- src/Web/opencatapultweb/src/app/user-profile/components/user-profile-info/user-profile-info.component.css
- src/Web/opencatapultweb/src/app/user-profile/components/user-profile-info/user-profile-info.component.html
- src/Web/opencatapultweb/src/app/user-profile/components/user-profile-info/user-profile-info.component.spec.ts
- src/Web/opencatapultweb/src/app/user-profile/components/user-profile-info/user-profile-info.component.ts
- src/Web/opencatapultweb/src/app/user-profile/components/user-profile-password/user-profile-password.component.css
- src/Web/opencatapultweb/src/app/user-profile/components/user-profile-password/user-profile-password.component.html
- src/Web/opencatapultweb/src/app/user-profile/components/user-profile-password/user-profile-password.component.spec.ts
- src/Web/opencatapultweb/src/app/user-profile/components/user-profile-password/user-profile-password.component.ts
- src/Web/opencatapultweb/src/app/user-profile/user-profile-routing.module.ts
- src/Web/opencatapultweb/src/app/user-profile/user-profile.module.ts
- src/Web/opencatapultweb/src/app/user-profile/user-profile/user-profile.component.css
- src/Web/opencatapultweb/src/app/user-profile/user-profile/user-profile.component.html
- src/Web/opencatapultweb/src/app/user-profile/user-profile/user-profile.component.spec.ts
- src/Web/opencatapultweb/src/app/user-profile/user-profile/user-profile.component.ts
> Implement user profile web ui

- src/Web/opencatapultweb/src/app/project/project/project.component.css
- src/Web/opencatapultweb/src/app/project/project/project.component.html
- src/Web/opencatapultweb/src/app/project/project/project.component.ts
Remove the scroll in projects menu
> Web UI: Remove scroll in projects menu

- src/Web/opencatapultweb/src/app/core/core.module.ts
- src/Web/opencatapultweb/src/app/core/index.ts
- src/Web/opencatapultweb/src/app/core/services/project-history.service.spec.ts
- src/Web/opencatapultweb/src/app/core/services/project-history.service.ts
- src/Web/opencatapultweb/src/app/project/project-dashboard/project-dashboard.component.css
- src/Web/opencatapultweb/src/app/project/project-dashboard/project-dashboard.component.html
- src/Web/opencatapultweb/src/app/project/project-dashboard/project-dashboard.component.spec.ts
- src/Web/opencatapultweb/src/app/project/project-dashboard/project-dashboard.component.ts
- src/Web/opencatapultweb/src/app/project/project-detail/project-detail.component.ts
- src/Web/opencatapultweb/src/app/project/project-routing.module.ts
- src/Web/opencatapultweb/src/app/project/project.module.ts
- src/Web/opencatapultweb/src/app/project/project/project.component.html
- src/Web/opencatapultweb/src/app/project/project/project.component.ts
Implement project dashboard web ui
> Project dashboard web ui

- src/Web/opencatapultweb/src/app/core/services/project.service.ts
- src/Web/opencatapultweb/src/app/project/project-detail/project-detail.component.html
- src/Web/opencatapultweb/src/app/project/project-detail/project-detail.component.ts
Implement export project web ui
> Implement export project in web ui

- src/Web/opencatapultweb/src/app/core/index.ts
- src/Web/opencatapultweb/src/app/core/models/job-queue/job-queue-dto.ts
- src/Web/opencatapultweb/src/app/core/services/job-queue.service.ts
- src/Web/opencatapultweb/src/app/core/services/signalr.service.ts
- src/Web/opencatapultweb/src/app/project/job-queue/components/job-queue-cancel-dialog/job-queue-cancel-dialog.component.ts
- src/Web/opencatapultweb/src/app/project/job-queue/job-queue-detail/job-queue-detail.component.html
- src/Web/opencatapultweb/src/app/project/job-queue/job-queue-detail/job-queue-detail.component.ts
- src/Web/opencatapultweb/src/app/project/job-queue/job-queue-list/job-queue-list.component.ts
- src/Web/opencatapultweb/src/app/project/job-queue/job-queue-log/job-queue-log.component.html
- src/Web/opencatapultweb/src/app/project/job-queue/job-queue-log/job-queue-log.component.ts
- src/Web/opencatapultweb/src/app/project/job-queue/job-queue-task-log/job-queue-task-log.component.ts
- src/Web/opencatapultweb/src/app/project/job-queue/job-queue/job-queue.component.ts
- src/Web/opencatapultweb/src/app/project/job-queue/services/job-queue-resolver.service.ts
- src/Web/opencatapultweb/src/app/project/project-detail/project-detail.component.ts
Fix job queue log not working properly
> Fix job queue web ui

- builds/build-all.ps1
- builds/build-prerequisites.ps1
- builds/build-web.ps1
Some improvements on the build scripts.
> Some improvements on the build scripts

- builds/build-web.ps1
Add params to `build-web.ps1` so the URL can be modified when running the script.
> Add params to build-web.ps1

- src/API/Polyrific.Catapult.Api/Controllers/TokenController.cs
- src/API/Polyrific.Catapult.Api/Identity/AuthorizationToken.cs
- src/Web/opencatapultweb/src/app/app.module.ts
- src/Web/opencatapultweb/src/app/core/auth/auth.service.ts
- src/Web/opencatapultweb/src/app/core/auth/user.ts
- src/Web/opencatapultweb/src/app/header/header.component.css
- src/Web/opencatapultweb/src/app/header/header.component.html
- src/Web/opencatapultweb/src/app/header/header.component.spec.ts
- src/Web/opencatapultweb/src/app/header/header.component.ts
- src/Web/opencatapultweb/src/app/layouts/home-layout/home-layout.component.spec.ts
Show Greetings and group user menu into dropdown menu
> Show user greeting in navbar web

- src/Web/opencatapultweb/src/app/app.module.ts
- src/Web/opencatapultweb/src/app/header/header.component.css
- src/Web/opencatapultweb/src/app/header/header.component.html
- src/Web/opencatapultweb/src/app/header/header.component.spec.ts
- src/Web/opencatapultweb/src/app/header/header.component.ts
- src/Web/opencatapultweb/src/app/layouts/home-layout/home-layout.component.css
- src/Web/opencatapultweb/src/app/layouts/home-layout/home-layout.component.html
- src/Web/opencatapultweb/src/app/layouts/home-layout/home-layout.component.spec.ts
- src/Web/opencatapultweb/src/app/layouts/home-layout/home-layout.component.ts
Show the menu in the sidenav when the screen is too small to fit all the menus in the header
> Make header menu responsive

- builds/make-release.ps1
Add function to publish web component in the `make-release.ps1` script. This utility script is used by maintainers to create release packages.
> Add function to publish web component

- src/CLI/Polyrific.Catapult.Cli/Commands/Service/AddCommand.cs
Fix issue in CLI when adding external service, then entering incorrect additional config
- Related Issues: #424
> Fix add service issue

- docs/home/start.md
Added how to override connection string information
> Added connection string information to quick start document

- src/API/Polyrific.Catapult.Api/Controllers/TokenController.cs
- src/CLI/Polyrific.Catapult.Cli/Commands/Project/CreateCommand.cs
- src/Shared/Polyrific.Catapult.Shared.ApiClient/TokenService.cs
- src/Shared/Polyrific.Catapult.Shared.Service/ITokenService.cs
- src/Web/opencatapultweb/src/app/core/auth/auth.service.ts
- src/Web/opencatapultweb/src/app/project/project-new/project-new.component.ts
- tests/Polyrific.Catapult.Api.UnitTests/Controllers/TokenControllerTests.cs
- tests/Polyrific.Catapult.Cli.UnitTests/Commands/ProjectCommandTests.cs
Fix issue where the project cannot be retrieved after being created by basic user
- Related Issues: #440
> Refresh token new project

- tests/Polyrific.Catapult.Api.e2eTests/Insert New Users.sql
- tests/Polyrific.Catapult.Api.e2eTests/OpenCatapult.jmx
Update some steps to simplify the Jmeter components and add SQL script to create new users for the testing
> Add sql script to insert new users for testing

- tests/Polyrific.Catapult.Api.e2eTests/OpenCatapult.jmx
- Add mark project as deleting e2e test
- Add Project member e2e test
> Add e2e test for project member endpoints

- tests/Polyrific.Catapult.Api.e2eTests/OpenCatapult.jmx
Add the e2e test scenario for project data model and property endpoints
> Add e2e test for project data model & property endpoints

- tests/Polyrific.Catapult.Api.e2eTests/OpenCatapult.jmx
Create e2e test for job definition endpoints
> Create e2e test for job definition endpoints

- src/API/Polyrific.Catapult.Api.Core/Services/ProjectService.cs
- src/Shared/Polyrific.Catapult.Shared.Common/TextHelper.cs
- src/Web/opencatapultweb/src/app/core/auth/auth.service.ts
- src/Web/opencatapultweb/src/app/core/core.module.ts
- src/Web/opencatapultweb/src/app/core/services/text-helper.service.spec.ts
- src/Web/opencatapultweb/src/app/core/services/text-helper.service.ts
- src/Web/opencatapultweb/src/app/project/components/project-info-form/project-info-form.component.spec.ts
- src/Web/opencatapultweb/src/app/project/components/project-info-form/project-info-form.component.ts
- src/Web/opencatapultweb/src/app/project/project/project.component.css
- src/Web/opencatapultweb/src/app/project/project/project.component.html
- src/Web/opencatapultweb/src/custom-theme.css
- tests/Polyrific.Catapult.Api.UnitTests/Core/Services/ProjectServiceTests.cs
- Show project display name instead of project name in the project list
- Autopopulate project display name
- Related Issues: #442 , #441
> Autopopulate project display name

- src/Web/opencatapultweb/src/app/account/account/account.component.html
- src/Web/opencatapultweb/src/app/engine/engine/engine.component.html
- src/Web/opencatapultweb/src/app/external-service/external-service/external-service.component.html
- src/Web/opencatapultweb/src/app/project/project-dashboard/project-dashboard.component.html
- src/Web/opencatapultweb/src/app/task-provider/task-provider/task-provider.component.html
- src/Web/opencatapultweb/src/app/user-profile/user-profile/user-profile.component.html
- src/Web/opencatapultweb/src/styles.css
Add summarized context in each page header in Web UI
- Related Issues: #444
> Add summarized context and instructions

- src/Web/opencatapultweb/src/app/shared/components/confirmation-with-input-dialog/confirmation-with-input-dialog.component.html
- src/Web/opencatapultweb/src/app/shared/components/confirmation-with-input-dialog/confirmation-with-input-dialog.component.ts
Enable submit behavior in all confirmation popup
- Related Issues: #445
> Enable submit behavior on confirmation popup

- docs/task-providers/generator-provider.md
Fix the login instruction for generated code in Generator Task Provider
> Docs: Fix the login instruction for generated code

- src/Web/opencatapultweb/src/app/project/project-new/project-new.component.html
- src/Web/opencatapultweb/src/app/project/project-new/project-new.component.spec.ts
- src/Web/opencatapultweb/src/styles.css
Add hint to project template fields and add tooltip button for each sample template
- Related Issues: #446
> Add hint to project template in create project form

- src/Web/opencatapultweb/src/app/account/account/account.component.spec.ts
- src/Web/opencatapultweb/src/app/account/account/account.component.ts
- src/Web/opencatapultweb/src/app/engine/engine/engine.component.spec.ts
- src/Web/opencatapultweb/src/app/engine/engine/engine.component.ts
- src/Web/opencatapultweb/src/app/header/header.component.css
- src/Web/opencatapultweb/src/app/header/header.component.html
- src/Web/opencatapultweb/src/app/header/header.component.spec.ts
- src/Web/opencatapultweb/src/app/layouts/home-layout/home-layout.component.spec.ts
- src/Web/opencatapultweb/src/app/project/project-archive-detail/project-archive-detail.component.css
- src/Web/opencatapultweb/src/app/project/project-archive-detail/project-archive-detail.component.html
- src/Web/opencatapultweb/src/app/project/project-archive-detail/project-archive-detail.component.spec.ts
- src/Web/opencatapultweb/src/app/project/project-dashboard/project-dashboard.component.html
- src/Web/opencatapultweb/src/app/project/project-dashboard/project-dashboard.component.spec.ts
- src/Web/opencatapultweb/src/app/project/project-dashboard/project-dashboard.component.ts
- src/Web/opencatapultweb/src/app/project/project-detail/project-detail.component.css
- src/Web/opencatapultweb/src/app/project/project-detail/project-detail.component.html
- src/Web/opencatapultweb/src/app/project/project-detail/project-detail.component.spec.ts
- src/Web/opencatapultweb/src/app/project/project/project.component.css
- src/Web/opencatapultweb/src/app/project/project/project.component.html
- src/Web/opencatapultweb/src/app/task-provider/task-provider/task-provider.component.spec.ts
- src/Web/opencatapultweb/src/app/task-provider/task-provider/task-provider.component.ts
Add quick add menu to web ui and several ui fixes
- Related Issues: #448
> Add quick add menu

- src/Web/opencatapultweb/src/app/account/account/account.component.html
- src/Web/opencatapultweb/src/app/account/account/account.component.ts
- src/Web/opencatapultweb/src/app/app.component.html
- src/Web/opencatapultweb/src/app/app.component.spec.ts
- src/Web/opencatapultweb/src/app/app.component.ts
- src/Web/opencatapultweb/src/app/engine/engine/engine.component.html
- src/Web/opencatapultweb/src/app/engine/engine/engine.component.ts
- src/Web/opencatapultweb/src/app/external-service/external-service.module.ts
- src/Web/opencatapultweb/src/app/external-service/external-service/external-service.component.html
- src/Web/opencatapultweb/src/app/external-service/external-service/external-service.component.ts
- src/Web/opencatapultweb/src/app/project/data-model/data-model/data-model.component.html
- src/Web/opencatapultweb/src/app/project/job-definition/job-definition/job-definition.component.html
- src/Web/opencatapultweb/src/app/project/job-queue/job-queue/job-queue.component.html
- src/Web/opencatapultweb/src/app/project/job-queue/job-queue/job-queue.component.spec.ts
- src/Web/opencatapultweb/src/app/project/member/member/member.component.html
- src/Web/opencatapultweb/src/app/project/member/member/member.component.ts
- src/Web/opencatapultweb/src/app/project/project-deleting/project-deleting.component.html
- src/Web/opencatapultweb/src/app/project/project-detail/project-detail.component.html
- src/Web/opencatapultweb/src/app/project/project/project.component.html
- src/Web/opencatapultweb/src/app/project/project/project.component.ts
- src/Web/opencatapultweb/src/app/shared/components/loading-spinner/loading-spinner.component.css
- src/Web/opencatapultweb/src/app/shared/components/loading-spinner/loading-spinner.component.html
- src/Web/opencatapultweb/src/app/shared/components/loading-spinner/loading-spinner.component.spec.ts
- src/Web/opencatapultweb/src/app/shared/components/loading-spinner/loading-spinner.component.ts
- src/Web/opencatapultweb/src/app/shared/index.ts
- src/Web/opencatapultweb/src/app/shared/shared.module.ts
- src/Web/opencatapultweb/src/app/task-provider/task-provider/task-provider.component.html
- src/Web/opencatapultweb/src/app/task-provider/task-provider/task-provider.component.ts
Add loading indicator for api requests and when lazy loading module
> Add loading indicator for api request and lazy load

- src/Web/opencatapultweb/src/app/project/data-model/data-model/data-model.component.html
- src/Web/opencatapultweb/src/app/project/job-definition/job-definition/job-definition.component.html
- src/Web/opencatapultweb/src/app/project/job-queue/job-queue/job-queue.component.html
- src/Web/opencatapultweb/src/app/project/member/member/member.component.html
- src/Web/opencatapultweb/src/app/project/project-info/project-info.component.html
- src/Web/opencatapultweb/src/styles.css
Add description to each of the tabs in `Project` screen
- Related Issues: #471
> Add summarized context for Project tabs

- src/Web/opencatapultweb/src/app/core/services/project-history.service.ts
- src/Web/opencatapultweb/src/app/project/project-archive-detail/project-archive-detail.component.spec.ts
- src/Web/opencatapultweb/src/app/project/project-archive-detail/project-archive-detail.component.ts
- src/Web/opencatapultweb/src/app/project/project-dashboard/project-dashboard.component.html
- src/Web/opencatapultweb/src/app/project/project-detail/project-detail.component.ts
- Delete project history after deleting a project
- show display name in project history
> Delete project history after deleting a project

- docs/api/provider.md
- docs/summary.md
- docs/task-providers/generic-task-provider.md
- docs/task-providers/task-provider.md
- docs/user-guides/job-definitions.md
Update task providers documentation.
[If it contains multiple changes, list them here. It's useful to show the progress of this PR.]
> [docs] Update task providers docs

- src/Web/opencatapultweb/src/app/header/header.component.css
- src/Web/opencatapultweb/src/app/header/header.component.html
- src/Web/opencatapultweb/src/app/header/header.component.ts
- Hide the menu item and the quick add dropdown button when user does not have sufficient access.
- Fix avatar buble does not appear round when the supplied avatar image does not have square aspect ratio
> Several fixes in Web Header

- builds/make-release.ps1
Add `GenericCommand` in `make-release.ps1` script.
> Add GenericCommand in make-release

- src/API/Polyrific.Catapult.Api.Data/EntityConfigs/TaskProviderConfig.cs
- src/API/Polyrific.Catapult.Api.Data/Migrations/20190418212010_UpdateTo1.0.0-beta4.Designer.cs
- src/API/Polyrific.Catapult.Api.Data/Migrations/20190418212010_UpdateTo1.0.0-beta4.cs
- src/API/Polyrific.Catapult.Api/Polyrific.Catapult.Api.csproj
- src/CLI/Polyrific.Catapult.Cli/Polyrific.Catapult.Cli.csproj
- src/Engine/Polyrific.Catapult.Engine/Polyrific.Catapult.Engine.csproj
- src/Plugins/BuildProvider/Polyrific.Catapult.TaskProviders.DotNetCore/plugin.yml
- src/Plugins/DatabaseProvider/Polyrific.Catapult.TaskProviders.EntityFrameworkCore/plugin.yml
- src/Plugins/GeneratorProvider/Polyrific.Catapult.TaskProviders.AspNetCoreMvc/plugin.yml
- src/Plugins/GenericTaskProvider/Polyrific.Catapult.TaskProviders.GenericCommand/plugin.yml
- src/Plugins/HostingProvider/Polyrific.Catapult.TaskProviders.AzureAppService/plugin.yml
- src/Plugins/Polyrific.Catapult.TaskProviders.Core/Polyrific.Catapult.TaskProviders.Core.nuspec
- src/Plugins/RepositoryProvider/Polyrific.Catapult.TaskProviders.GitHub/plugin.yml
- src/Plugins/TestProvider/Polyrific.Catapult.TaskProviders.DotNetCoreTest/plugin.yml
- src/Shared/Polyrific.Catapult.Shared.Dto/Polyrific.Catapult.Shared.Dto.csproj
- src/Web/opencatapultweb/package.json
- src/Web/opencatapultweb/src/environments/environment.prod.ts
- src/Web/opencatapultweb/src/environments/environment.ts
Update component versions to `1.0.0-beta4`.
> Update to v1.0.0-beta4

- src/API/Polyrific.Catapult.Api/appsettings.json
Add more settings for Seq logging:
- api key
- environment
> Add more settings for Seq logging

- src/Plugins/GeneratorProvider/Polyrific.Catapult.TaskProviders.AspNetCoreMvc/src/ProjectGenerators/MainProjectGenerator.cs
Fix the generated code for AspNetCoreMvc generator after upgrading to dotnet core 2.2. The `dotnet new mvc` is updated in the 2.2 version, which includes the upgrading of bootstrap from v3 to v4.
> Fix generator after updating to dotnet core 2.2

- src/API/Polyrific.Catapult.Api.Core/Services/IJobQueueService.cs
- src/API/Polyrific.Catapult.Api.Core/Services/JobQueueService.cs
- src/API/Polyrific.Catapult.Api/Controllers/JobQueueController.cs
- src/API/Polyrific.Catapult.Api/appsettings.json
- src/API/Polyrific.Catapult.Api/notificationconfig.json
- src/Engine/Polyrific.Catapult.Engine.Core/CatapultEngine.cs
- src/Shared/Polyrific.Catapult.Shared.ApiClient/JobQueueService.cs
- src/Shared/Polyrific.Catapult.Shared.Common/Notification/MessageParameter.cs
- src/Shared/Polyrific.Catapult.Shared.Common/Notification/NotificationConfig.cs
- src/Shared/Polyrific.Catapult.Shared.Common/Notification/Template/JobQueueCompleted.html
- src/Shared/Polyrific.Catapult.Shared.Common/Notification/Template/SmtpEmail/JobQueueCompleted.html
- src/Shared/Polyrific.Catapult.Shared.Common/Polyrific.Catapult.Shared.Common.csproj
- src/Shared/Polyrific.Catapult.Shared.Service/IJobQueueService.cs
- tests/Polyrific.Catapult.Api.UnitTests/Controllers/JobQueueControllerTests.cs
- tests/Polyrific.Catapult.Api.UnitTests/Core/Services/JobQueueServiceTests.cs
Send notification to project member when the engine has finished processing the job queue
> Send notification once the queue has been processed by engine

- src/API/Polyrific.Catapult.Api.Core/AutoMapperProfiles/ProjectTemplateAutoMapperProfile.cs
- src/API/Polyrific.Catapult.Api.Core/Entities/ProjectTemplate.cs
- src/API/Polyrific.Catapult.Api.Core/Services/IJobDefinitionService.cs
- src/API/Polyrific.Catapult.Api.Core/Services/JobDefinitionService.cs
- src/API/Polyrific.Catapult.Api.Core/Services/ProjectService.cs
- src/Web/opencatapultweb/src/app/core/services/yaml.service.ts
Fix export project due to incorrect yaml export and import
> Fix export project

- docs/dev-guides/create-task-provider-4.md
Fix typo in task provider tutorial
> Fix typo in Task provider tutorial

- tests/Polyrific.Catapult.Api.e2eTests/OpenCatapult.jmx
Fix failed e2e test that happens because some changes in the API endpoint
> Fix e2e test due to changes in endpoint

- src/API/Polyrific.Catapult.Api.Data/Identity/CatapultEngineProfile.cs
- src/API/Polyrific.Catapult.Api.Data/Identity/UserProfile.cs
- src/API/Polyrific.Catapult.Api.Data/Migrations/20190502030615_FixEntityWarning.Designer.cs
- src/API/Polyrific.Catapult.Api.Data/Migrations/20190502030615_FixEntityWarning.cs
- src/API/Polyrific.Catapult.Api/Controllers/AccountController.cs
- src/API/Polyrific.Catapult.Api/Controllers/CatapultEngineController.cs
- src/API/Polyrific.Catapult.Api/Controllers/ExternalServiceController.cs
- src/API/Polyrific.Catapult.Api/Controllers/ExternalServiceTypeController.cs
- src/API/Polyrific.Catapult.Api/Controllers/HelpContextController.cs
- src/API/Polyrific.Catapult.Api/Controllers/JobDefinitionController.cs
- src/API/Polyrific.Catapult.Api/Controllers/JobQueueController.cs
- src/API/Polyrific.Catapult.Api/Controllers/ManagedFileController.cs
- src/API/Polyrific.Catapult.Api/Controllers/ProjectController.cs
- src/API/Polyrific.Catapult.Api/Controllers/ProjectDataModelController.cs
- src/API/Polyrific.Catapult.Api/Controllers/ProjectMemberController.cs
- src/API/Polyrific.Catapult.Api/Controllers/TaskProviderController.cs
- src/API/Polyrific.Catapult.Api/Controllers/TokenController.cs
- src/API/Polyrific.Catapult.Api/Controllers/VersionController.cs
- src/API/Polyrific.Catapult.Api/LoggerExtensions.cs
Do some improvement in API logging
- Related Issues: #493
> Some fixes in API logging

- src/Web/opencatapultweb/src/app/app-routing.module.ts
- src/Web/opencatapultweb/src/app/app.module.ts
- src/Web/opencatapultweb/src/app/core/core.module.ts
- src/Web/opencatapultweb/src/app/core/models/version/version-dto.ts
- src/Web/opencatapultweb/src/app/core/services/version.service.spec.ts
- src/Web/opencatapultweb/src/app/core/services/version.service.ts
- src/Web/opencatapultweb/src/app/footer/footer.component.css
- src/Web/opencatapultweb/src/app/footer/footer.component.html
- src/Web/opencatapultweb/src/app/footer/footer.component.spec.ts
- src/Web/opencatapultweb/src/app/footer/footer.component.ts
- src/Web/opencatapultweb/src/app/layouts/home-layout/home-layout.component.css
- src/Web/opencatapultweb/src/app/layouts/home-layout/home-layout.component.html
- src/Web/opencatapultweb/src/app/layouts/home-layout/home-layout.component.spec.ts
- src/Web/opencatapultweb/src/app/layouts/home-layout/home-layout.component.ts
- src/Web/opencatapultweb/src/app/layouts/login-layout/login-layout.component.html
- src/Web/opencatapultweb/src/app/layouts/login-layout/login-layout.component.spec.ts
- src/Web/opencatapultweb/src/app/layouts/login-layout/login-layout.component.ts
- src/Web/opencatapultweb/src/app/version/version.component.css
- src/Web/opencatapultweb/src/app/version/version.component.html
- src/Web/opencatapultweb/src/app/version/version.component.spec.ts
- src/Web/opencatapultweb/src/app/version/version.component.ts
Add version page and modify footer styling
- Related Issues: #485
> Add version page

- builds/build-api.ps1
Fix the SQLite connection string in `build-api.ps1`.
> Fix sqlite connection string

- src/Web/Polyrific.Catapult.Web/Polyrific.Catapult.Web.csproj
Add `npm install` to the pre-build event to prepare the node modules.
> Add npm install to the pre-build event

- src/Web/Polyrific.Catapult.Web/ClientApp/src/app/reset-password/reset-password.component.ts
Fix bug in reset password due to changes in email/username
> Fix bug in reset password

- .gitignore
Add `package-lock.json` file to `.gitignore`.
> Ignore package-lock.json file

- src/Web/Polyrific.Catapult.Web/ClientApp/src/app/external-service/components/external-service-form/external-service-form.component.html
- src/Web/Polyrific.Catapult.Web/ClientApp/src/app/external-service/external-service/external-service.component.spec.ts
Fix error in production build of Polyrific.Catapult.Web
> Fix error in production build

- src/Web/Polyrific.Catapult.Web/ClientApp/src/app/account/account/account.component.html
- src/Web/Polyrific.Catapult.Web/ClientApp/src/app/engine/engine/engine.component.html
- src/Web/Polyrific.Catapult.Web/ClientApp/src/app/external-service/external-service/external-service.component.html
- src/Web/Polyrific.Catapult.Web/ClientApp/src/app/header/header.component.html
- src/Web/Polyrific.Catapult.Web/ClientApp/src/app/header/header.component.ts
- src/Web/Polyrific.Catapult.Web/ClientApp/src/app/help-context-dialog/help-context-dialog.component.html
- src/Web/Polyrific.Catapult.Web/ClientApp/src/app/help-context-dialog/help-context-dialog.component.ts
- src/Web/Polyrific.Catapult.Web/ClientApp/src/app/project/data-model/data-model/data-model.component.html
- src/Web/Polyrific.Catapult.Web/ClientApp/src/app/project/job-definition/job-definition/job-definition.component.html
- src/Web/Polyrific.Catapult.Web/ClientApp/src/app/project/job-queue/job-queue-detail/job-queue-detail.component.html
- src/Web/Polyrific.Catapult.Web/ClientApp/src/app/project/job-queue/job-queue-list/job-queue-list.component.html
- src/Web/Polyrific.Catapult.Web/ClientApp/src/app/project/job-queue/job-queue-log/job-queue-log.component.html
- src/Web/Polyrific.Catapult.Web/ClientApp/src/app/project/member/member/member.component.html
- src/Web/Polyrific.Catapult.Web/ClientApp/src/app/project/project-dashboard/project-dashboard.component.html
- src/Web/Polyrific.Catapult.Web/ClientApp/src/app/project/project-detail/project-detail.component.html
- src/Web/Polyrific.Catapult.Web/ClientApp/src/app/project/project/project.component.html
- src/Web/Polyrific.Catapult.Web/ClientApp/src/app/shared/directives/help-element.directive.ts
- src/Web/Polyrific.Catapult.Web/ClientApp/src/app/shared/shared.module.ts
- src/Web/Polyrific.Catapult.Web/ClientApp/src/app/user-profile/user-profile/user-profile.component.html
Improve the help context UI to show `wizard-like` modal windows:
> Improve Help Context UI

- src/CLI/Polyrific.Catapult.Cli/Templates/sample.yaml
- src/Web/Polyrific.Catapult.Web/ClientApp/src/assets/template/sample.yaml
Set the default job definition for `sample.yaml` template
> Set sample template default job

- docs/home/start.md
- docs/user-guides/create-first-project-web.md
Fix images that are not loaded correctly in the docs.
> [docs] Fix unloaded images

- src/API/Polyrific.Catapult.Api.Data/EntityConfigs/TaskProviderConfig.cs
- src/API/Polyrific.Catapult.Api.Data/Migrations/20190521014929_UpdateTo1.0.0-rc.Designer.cs
- src/API/Polyrific.Catapult.Api.Data/Migrations/20190521014929_UpdateTo1.0.0-rc.cs
- src/API/Polyrific.Catapult.Api.Data/Migrations/CatapultSqliteDb/20190521014846_UpdateTo1.0.0-rc.Designer.cs
- src/API/Polyrific.Catapult.Api.Data/Migrations/CatapultSqliteDb/20190521014846_UpdateTo1.0.0-rc.cs
- src/API/Polyrific.Catapult.Api.Data/Migrations/CatapultSqliteDb/CatapultSqliteDbContextModelSnapshot.cs
- src/API/Polyrific.Catapult.Api/Polyrific.Catapult.Api.csproj
- src/CLI/Polyrific.Catapult.Cli/Polyrific.Catapult.Cli.csproj
- src/Engine/Polyrific.Catapult.Engine/Polyrific.Catapult.Engine.csproj
- src/Plugins/BuildProvider/Polyrific.Catapult.TaskProviders.DotNetCore/plugin.yml
- src/Plugins/DatabaseProvider/Polyrific.Catapult.TaskProviders.EntityFrameworkCore/plugin.yml
- src/Plugins/GeneratorProvider/Polyrific.Catapult.TaskProviders.AspNetCoreMvc/plugin.yml
- src/Plugins/GenericTaskProvider/Polyrific.Catapult.TaskProviders.GenericCommand/plugin.yml
- src/Plugins/HostingProvider/Polyrific.Catapult.TaskProviders.AzureAppService/plugin.yml
- src/Plugins/Polyrific.Catapult.TaskProviders.Core/Polyrific.Catapult.TaskProviders.Core.nuspec
- src/Plugins/RepositoryProvider/Polyrific.Catapult.TaskProviders.GitHub/plugin.yml
- src/Plugins/TestProvider/Polyrific.Catapult.TaskProviders.DotNetCoreTest/plugin.yml
- src/Shared/Polyrific.Catapult.Shared.Dto/Polyrific.Catapult.Shared.Dto.csproj
- src/Web/Polyrific.Catapult.Web/ClientApp/package.json
- src/Web/Polyrific.Catapult.Web/ClientApp/src/environments/environment.prod.ts
- src/Web/Polyrific.Catapult.Web/ClientApp/src/environments/environment.ts
- src/Web/Polyrific.Catapult.Web/Polyrific.Catapult.Web.csproj
Update the project versions to `1.0.0-rc`
> Update version to 1.0.0-rc

- docs/cli/provider.md
- docs/dev-guides/create-task-provider-4.md
- docs/dev-guides/create-task-provider.md
- docs/dev-guides/manual-build.md
- docs/dev-guides/project-template.md
- docs/dev-guides/simple-task-provider.md
- docs/user-guides/task-providers.md
Rename plugin term in documentation
- Related Issues: #562
> Rename plugin term in documentation

- builds/build-all.ps1
- src/Web/Polyrific.Catapult.Web/ClientApp/src/app/project/project-dashboard/project-dashboard.component.html
- Fix build script when including the conn string
- Fix some wording on the project dashboard
> Fix build script and web instruction

- src/TaskProviders/BuildProvider/Polyrific.Catapult.TaskProviders.DotNetCore/src/Builder.cs
- src/TaskProviders/BuildProvider/Polyrific.Catapult.TaskProviders.DotNetCore/src/Program.cs
Include logger in the build provider.
> Include logger in the build provider

- src/API/Polyrific.Catapult.Api/notificationconfig.json
Rename notification subjects form Catapult to OpenCatapult
> API: Rename notification subjects form Catapult to OpenCatapult

- src/Web/Polyrific.Catapult.Web/ClientApp/src/app/project/job-queue/job-queue-detail/job-queue-detail.component.html
- src/Web/Polyrific.Catapult.Web/ClientApp/src/app/project/job-queue/job-queue-detail/job-queue-detail.component.ts
- src/Web/Polyrific.Catapult.Web/ClientApp/src/app/project/job-queue/job-queue-log/job-queue-log.component.html
- src/Web/Polyrific.Catapult.Web/ClientApp/src/app/project/job-queue/job-queue-log/job-queue-log.component.ts
Rename restart button to "Merge & Resume" when the current pending task is a Merge task
> Web UI: Rename restart button to merge & resume

- src/TaskProviders/RepositoryProvider/Polyrific.Catapult.TaskProviders.GitHub/src/GitHubUtils.cs
Fix issue adding collaborators for repositories that is inside an organization
> Repo Provider: Fix adding collaborators for org repository

- src/Shared/Polyrific.Catapult.Shared.Dto/ProjectDataModel/ProjectDataModelDto.cs
- src/Shared/Polyrific.Catapult.Shared.Dto/ProjectDataModel/ProjectDataModelPropertyDto.cs
Add `DatabaseTableName` and `DatabaseColumnName` in the DTO
> Task Provider Core: Include database names property in dto

- src/Web/Polyrific.Catapult.Web/ClientApp/src/app/header/header.component.html
- src/Web/Polyrific.Catapult.Web/ClientApp/src/app/layouts/home-layout/home-layout.component.html
- src/Web/Polyrific.Catapult.Web/ClientApp/src/app/task-provider/task-provider/task-provider.component.html
Fix some wording on Task Providers page.
> Fix some wording on Task Providers page

- src/API/Polyrific.Catapult.Api.Core/Entities/ProjectTemplate.cs
- src/Shared/Polyrific.Catapult.Shared.Dto/ProjectDataModel/CreateProjectDataModelDto.cs
- src/Shared/Polyrific.Catapult.Shared.Dto/ProjectDataModel/CreateProjectDataModelPropertyDto.cs
Add Database Table and Column Names properties in Create dtos. Changes for Update model/property, along with the changes in the UI dialog will be handled on separate PR
> API: Add Database Names properties in Create dtos

- src/Web/Polyrific.Catapult.Web/ClientApp/src/app/core/auth/auth.service.ts
- src/Web/Polyrific.Catapult.Web/ClientApp/src/app/header/header.component.ts
- src/Web/Polyrific.Catapult.Web/ClientApp/src/app/layouts/home-layout/home-layout.component.html
- src/Web/Polyrific.Catapult.Web/ClientApp/src/app/shared/components/alert-box/alert-box.component.css
- src/Web/Polyrific.Catapult.Web/ClientApp/src/app/shared/components/alert-box/alert-box.component.html
- src/Web/Polyrific.Catapult.Web/ClientApp/src/app/shared/components/alert-box/alert-box.component.spec.ts
- src/Web/Polyrific.Catapult.Web/ClientApp/src/app/shared/components/alert-box/alert-box.component.ts
- src/Web/Polyrific.Catapult.Web/ClientApp/src/app/shared/services/alert-box.service.spec.ts
- src/Web/Polyrific.Catapult.Web/ClientApp/src/app/shared/services/alert-box.service.ts
- src/Web/Polyrific.Catapult.Web/ClientApp/src/app/shared/shared.module.ts
- src/Web/Polyrific.Catapult.Web/ClientApp/src/styles.css
Display warning to Admin user if the default user is active. If the default user has been suspended or deleted, the warning should be gone.
- Related Issues: https://github.com/Polyrific-Inc/OpenCatapult/issues/588
> Display warning when default user is active

- src/TaskProviders/RepositoryProvider/Polyrific.Catapult.TaskProviders.GitHub/src/GitHubUtils.cs
- src/TaskProviders/RepositoryProvider/Polyrific.Catapult.TaskProviders.GitHub/src/Program.cs
Create unique branch name for each PR
- Related Issues: #594
> Repo Provider: Create unique branch name for each PR

- src/Web/Polyrific.Catapult.Web/ClientApp/src/app/project/data-model/data-model/data-model.component.html
- src/Web/Polyrific.Catapult.Web/ClientApp/src/app/project/data-model/data-model/data-model.component.ts
Optimize project model load page
- Related Issues: https://github.com/Polyrific-Inc/OpenCatapult/issues/601
> Issue #601 - Optimize project model load page

- src/API/Polyrific.Catapult.Api.Infrastructure/IdentityInjection.cs
Fix the mssql identity provider injection to be the same as sqlite identity provider injection, that cause login issue when using mssql provider
> Hotfix API: Fix adding the identity provider

- src/Web/Polyrific.Catapult.Web/ClientApp/src/app/project/job-queue/job-queue/job-queue.component.ts
- src/Web/Polyrific.Catapult.Web/ClientApp/src/app/project/project-detail/project-detail.component.ts
Force update the job queue list when adding queue in queue list page
- Related Issues: #605
> Web UI: Fix job queue list not updated

- src/TaskProviders/Polyrific.Catapult.TaskProviders.Core/Polyrific.Catapult.TaskProviders.Core.nuspec
Modify the owner and license of Task Provider Core nuspec.
> Modify owner and license of Task Provider Core nuspec

- src/Web/Polyrific.Catapult.Web/ClientApp/src/app/footer/footer.component.html
- src/Web/Polyrific.Catapult.Web/ClientApp/src/app/footer/footer.component.spec.ts
- src/Web/Polyrific.Catapult.Web/ClientApp/src/app/footer/footer.component.ts
- src/Web/Polyrific.Catapult.Web/ClientApp/src/app/layouts/home-layout/home-layout.component.spec.ts
- src/Web/Polyrific.Catapult.Web/ClientApp/src/app/layouts/login-layout/login-layout.component.spec.ts
Display the environment name in the footer to differentiate each instance.
> Display environment name in footer

- src/Web/Polyrific.Catapult.Web/ClientApp/src/app/project/data-model/data-model-property/data-model-property.component.html
Display Related data model on the property list when a property has a related data model
> Display related data model if exist

- src/CLI/Polyrific.Catapult.Cli/Templates/sample-devops.yaml
- src/CLI/Polyrific.Catapult.Cli/Templates/sample.yaml
- src/TaskProviders/GeneratorProvider/Polyrific.Catapult.TaskProviders.AspNetCoreMvc/src/ProjectGenerators/MainProjectGenerator.cs
- src/Web/Polyrific.Catapult.Web/ClientApp/src/assets/template/sample-devops.yaml
- src/Web/Polyrific.Catapult.Web/ClientApp/src/assets/template/sample.yaml
Show Combobox in the create/edit form when a model has a one-to-one relation
> Implement combobox when a model have one-to-one relation

- src/TaskProviders/GeneratorProvider/Polyrific.Catapult.TaskProviders.AspNetCoreMvc/src/ProjectGenerators/CoreProjectGenerator.cs
- src/TaskProviders/GeneratorProvider/Polyrific.Catapult.TaskProviders.AspNetCoreMvc/src/ProjectGenerators/MainProjectGenerator.cs
- Fix the model and view model class to handle optional property
- Fix update on one-to-one property
> Fix optional property in AspNetCoreMvc

- src/API/Polyrific.Catapult.Api.Data/EntityConfigs/TaskProviderAdditionalConfigConfig.cs
- src/API/Polyrific.Catapult.Api.Data/Migrations/20200131093828_GithubAdditionalConfig.Designer.cs
- src/API/Polyrific.Catapult.Api.Data/Migrations/20200131093828_GithubAdditionalConfig.cs
- src/API/Polyrific.Catapult.Api.Data/Migrations/CatapultDbContextModelSnapshot.cs
- src/API/Polyrific.Catapult.Api.Data/Migrations/CatapultSqliteDb/20200131094840_GithubAdditionalConfig.Designer.cs
- src/API/Polyrific.Catapult.Api.Data/Migrations/CatapultSqliteDb/20200131094840_GithubAdditionalConfig.cs
- src/TaskProviders/RepositoryProvider/Polyrific.Catapult.TaskProviders.GitHub/src/GitAutomation.cs
- src/TaskProviders/RepositoryProvider/Polyrific.Catapult.TaskProviders.GitHub/src/GitAutomationConfig.cs
- src/TaskProviders/RepositoryProvider/Polyrific.Catapult.TaskProviders.GitHub/src/GitHubUtils.cs
- src/TaskProviders/RepositoryProvider/Polyrific.Catapult.TaskProviders.GitHub/src/IGitHubUtils.cs
- src/TaskProviders/RepositoryProvider/Polyrific.Catapult.TaskProviders.GitHub/src/Program.cs
- src/TaskProviders/RepositoryProvider/Polyrific.Catapult.TaskProviders.GitHub/taskprovider.yml
Add GitHub additional config to skip configuring member
> [API] [GitHub Task Provider] Add github additional config to skip configuring member

- src/TaskProviders/RepositoryProvider/Polyrific.Catapult.TaskProviders.GitHub/src/GitAutomation.cs
- src/TaskProviders/RepositoryProvider/Polyrific.Catapult.TaskProviders.GitHub/src/GitHubUtils.cs
- src/TaskProviders/RepositoryProvider/Polyrific.Catapult.TaskProviders.GitHub/src/IGitAutomation.cs
- src/TaskProviders/RepositoryProvider/Polyrific.Catapult.TaskProviders.GitHub/src/IGitHubUtils.cs
- src/TaskProviders/RepositoryProvider/Polyrific.Catapult.TaskProviders.GitHub/src/Program.cs
Allow pushing to main branch when using GitHub
> [Github task provider] Allow main branch
