Polyrific-Inc/OpenCatapult

src/API/Polyrific.Catapult.Api.Core/Entities/JobTaskDefinition.cs, src/API/Polyrific.Catapult.Api.Core/Exceptions/PluginAdditionalConfigRequiredException.cs, src/API/Polyrific.Catapult.Api.Core/Services/IPluginAdditionalConfigService.cs, src/API/Polyrific.Catapult.Api.Core/Services/JobDefinitionService.cs, src/API/Polyrific.Catapult.Api.Core/Services/PluginAdditionalConfigService.cs, src/API/Polyrific.Catapult.Api.Core/Specifications/PluginAdditionalConfigFilterSpecification.cs, src/API/Polyrific.Catapult.Api.Data/Migrations/20180924123227_TaskAdditionalConfig.Designer.cs, src/API/Polyrific.Catapult.Api.Data/Migrations/20180924123227_TaskAdditionalConfig.cs, src/API/Polyrific.Catapult.Api/AutoMapperProfiles/JobTaskDefinitionAutoMapperProfile.cs, src/API/Polyrific.Catapult.Api/Controllers/PluginController.cs, src/CLI/Polyrific.Catapult.Cli/Commands/Project/CreateCommand.cs, src/CLI/Polyrific.Catapult.Cli/Commands/Task/AddCommand.cs, src/CLI/Polyrific.Catapult.Cli/Commands/Task/GetCommand.cs, src/CLI/Polyrific.Catapult.Cli/Commands/Task/ListCommand.cs, src/CLI/Polyrific.Catapult.Cli/Commands/Task/UpdateCommand.cs, src/CLI/Polyrific.Catapult.Cli/Extensions/CatapultCliExtensions.cs, src/Shared/Polyrific.Catapult.Shared.ApiClient/PluginService.cs, src/Shared/Polyrific.Catapult.Shared.Dto/JobDefinition/CreateJobTaskDefinitionDto.cs, src/Shared/Polyrific.Catapult.Shared.Dto/JobDefinition/UpdateJobTaskDefinitionDto.cs, src/Shared/Polyrific.Catapult.Shared.Service/IPluginService.cs, tests/Polyrific.Catapult.Api.UnitTests/Core/Services/JobDefinitionServiceTests.cs, tests/Polyrific.Catapult.Api.UnitTests/Core/Services/PluginAdditionalConfigServiceTests.cs, tests/Polyrific.Catapult.Cli.UnitTests/Commands/ProjectCommandTests.cs, tests/Polyrific.Catapult.Cli.UnitTests/Commands/TaskCommandTest.cs
Integrate the plugin's additional config into task
=> Integration additional config into task

src/CLI/Polyrific.Catapult.Cli/Commands/BaseCommand.cs
Fix typo in CLI where it shows welcome message of Catapult engine
=> Fix typo in CLI welcome message

src/Shared/Polyrific.Catapult.Shared.Common/LocalTextWriter.cs
There's error occured in external service POST endpoint when running in production. This is due to WebRootPath returns null. To avoid the error, I add the null checking and provide default value to get the base path
=> Avoid error due to null in WebRootPath

src/Plugins/DatabaseProvider/EntityFrameworkCore/src/DatabaseCommand.cs, src/Plugins/DatabaseProvider/EntityFrameworkCore/src/DatabaseProvider.cs, src/Plugins/DatabaseProvider/EntityFrameworkCore/src/Helpers/CommandHelper.cs, src/Plugins/DatabaseProvider/EntityFrameworkCore/tests/DatabaseProviderTests.cs, src/Plugins/GeneratorProvider/AspNetCoreMvc/src/CodeGenerator.cs, src/Plugins/GeneratorProvider/AspNetCoreMvc/src/Helpers/CommandHelper.cs, src/Plugins/GeneratorProvider/AspNetCoreMvc/src/Helpers/ProjectHelper.cs, src/Plugins/GeneratorProvider/AspNetCoreMvc/src/ProjectGenerators/CoreProjectGenerator.cs, src/Plugins/GeneratorProvider/AspNetCoreMvc/src/ProjectGenerators/DataProjectGenerator.cs, src/Plugins/GeneratorProvider/AspNetCoreMvc/src/ProjectGenerators/InfrastructureProjectGenerator.cs, src/Plugins/GeneratorProvider/AspNetCoreMvc/src/ProjectGenerators/MainProjectGenerator.cs
Use environment variable instead of appsettings.json to get the connection string when running update migration script or db deploy. This way, the generated code that are pushed to the repo will be clean from db credentials.
=> use environment variable for connection string

src/API/Polyrific.Catapult.Api.Core/Services/ExternalServiceTypeService.cs, src/API/Polyrific.Catapult.Api.Core/Services/IExternalServiceTypeService.cs, src/API/Polyrific.Catapult.Api/Controllers/ExternalServiceTypeController.cs, src/CLI/Polyrific.Catapult.Cli/Commands/BaseCommand.cs, src/CLI/Polyrific.Catapult.Cli/Commands/Service/AddCommand.cs, src/CLI/Polyrific.Catapult.Cli/Program.cs, src/CLI/Polyrific.Catapult.Cli/Utility/CatapultHelpTextGenerator.cs, src/Shared/Polyrific.Catapult.Shared.ApiClient/ExternalServiceTypeService.cs, src/Shared/Polyrific.Catapult.Shared.Service/IExternalServiceTypeService.cs
Show available external service types in its properties when user run `service add --help`
Issue: #59
=> Show service types in service add help

src/Engine/Polyrific.Catapult.Engine/Program.cs
Handle CommandParsingException in engine so it does not throw unhandled exception when user input unknown command
Issue #64
=> Handle CommandParsingException in Engine

src/API/Polyrific.Catapult.Api/Identity/ProjectAccessHandler.cs
Fix error in endpoint `/project` that use authorization policy `ProjectMemberAccess`. The error occured because the `ProjectAccessHandler` require `projectId` or `projectName` in the route, when the user is not admin
=> Fix get projects return error when user is not admin

src/API/Polyrific.Catapult.Api.Core/Services/IProjectDataModelService.cs, src/API/Polyrific.Catapult.Api.Core/Services/ProjectDataModelService.cs, src/API/Polyrific.Catapult.Api/AutoMapperProfiles/ProjectDataModelPropertyAutoMapperProfile.cs, src/API/Polyrific.Catapult.Api/Controllers/ProjectDataModelController.cs, src/API/Polyrific.Catapult.Api/Identity/ProjectAccessHandler.cs, src/API/Polyrific.Catapult.Api/Identity/ProjectAccessRequirement.cs, src/API/Polyrific.Catapult.Api/Identity/ProjectEngineAccessHandler.cs, src/API/Polyrific.Catapult.Api/Startup.cs, src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/GenerateTask.cs, src/Engine/Polyrific.Catapult.Engine.Core/TaskRunner.cs, src/Plugins/GeneratorProvider/AspNetCoreMvc/src/AspNetCoreMvc.csproj, src/Plugins/GeneratorProvider/AspNetCoreMvc/src/CodeGenerator.cs, src/Plugins/GeneratorProvider/AspNetCoreMvc/src/CodeGeneratorProvider.cs, src/Plugins/GeneratorProvider/AspNetCoreMvc/src/Helpers/TextHelper.cs, src/Plugins/GeneratorProvider/AspNetCoreMvc/src/ProjectGenerators/MainProjectGenerator.cs, src/Shared/Polyrific.Catapult.Shared.ApiClient/ProjectDataModelService.cs, src/Shared/Polyrific.Catapult.Shared.Common/DirectoryHelper.cs, src/Shared/Polyrific.Catapult.Shared.Service/IProjectDataModelService.cs, tests/Polyrific.Catapult.Api.UnitTests/Core/Services/ProjectDataModelServiceTests.cs, tests/Polyrific.Catapult.Cli.UnitTests/Commands/ModelCommandTests.cs, tests/Polyrific.Catapult.Engine.UnitTests/Core/JobTasks/GenerateTaskTests.cs
Fix several bugs when running engine and generator task
=> Fix several bugs in engine and generator

src/Engine/Polyrific.Catapult.Engine/Commands/StartCommand.cs
Currently when we run `start` command, it'd first wait for the interval (default 30 seconds), before it's checking the queue. I think it's better for UX if it can check immediately
=> Make start command immediately checking for job

src/API/Polyrific.Catapult.Api.Core/Exceptions/RemoveProjectOwnerException.cs, src/API/Polyrific.Catapult.Api.Core/Services/IProjectMemberService.cs, src/API/Polyrific.Catapult.Api.Core/Services/ProjectMemberService.cs, src/API/Polyrific.Catapult.Api/Controllers/AccountController.cs, src/API/Polyrific.Catapult.Api/Controllers/ExternalServiceController.cs, src/API/Polyrific.Catapult.Api/Controllers/ProjectController.cs, src/API/Polyrific.Catapult.Api/Controllers/ProjectMemberController.cs, src/API/Polyrific.Catapult.Api/Controllers/TokenController.cs, src/API/Polyrific.Catapult.Api/Identity/AuthorizationToken.cs, src/API/Polyrific.Catapult.Api/Identity/ClaimPrincipalExtensions.cs, tests/Polyrific.Catapult.Api.UnitTests/Core/Services/ProjectMemberServiceTests.cs
After giving it a thought, I think we should require the user to have Owner Access instead of just Maintainer Access, for modifying the project member. 
Because it'd make less sense if a maintainer can add a member that have the Owner role. Or remove an Owner of a project.
=> Require OwnerAccess to modify project member

src/CLI/Polyrific.Catapult.Cli/Polyrific.Catapult.Cli.csproj, src/Engine/Polyrific.Catapult.Engine/Polyrific.Catapult.Engine.csproj
Rename output assembly for CLI and Engine.
- https://github.com/Polyrific-Inc/OpenCatapult/issues/88
=> Rename output assembly for CLI and Engine

src/API/Polyrific.Catapult.Api/Controllers/AccountController.cs, src/CLI/Polyrific.Catapult.Cli/Commands/Account/Password/ResetCommand.cs, src/CLI/Polyrific.Catapult.Cli/Commands/Account/Password/ResetTokenCommand.cs, src/CLI/Polyrific.Catapult.Cli/Commands/Account/Password/UpdateCommand.cs, src/Shared/Polyrific.Catapult.Shared.ApiClient/AccountService.cs, src/Shared/Polyrific.Catapult.Shared.Dto/User/UpdatePasswordDto.cs, src/Shared/Polyrific.Catapult.Shared.Service/IAccountService.cs, tests/Polyrific.Catapult.Cli.UnitTests/Commands/AccountCommandTests.cs
Adjust the update password and reset password command.
- #94
=> Adjust update password and reset password

src/CLI/Polyrific.Catapult.Cli/Utility/CatapultOptionParser.cs
When setting command option for --property <Key>:<Value>, the value cannot have the colon ( : ) character since it's used as the separator. However, this is needed for value that contains url/directory path (e.g. c:/temp).
This PR fix the above issue
=> CLI: Allow colon to be entered as an option value

Polyrific.Catapult.Cli.sln, appveyor/cli.appveyor.yml, src/CLI/Polyrific.Catapult.Cli/Commands/BaseCommand.cs, src/CLI/Polyrific.Catapult.Cli/Polyrific.Catapult.Cli.csproj
- Cleanup error message to omit the "One ore more errors occurred" part
- Add spaces between commands
=> Clean up CLI output

src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/BaseJobTask.cs, src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/IJobTask.cs, src/Engine/Polyrific.Catapult.Engine.Core/TaskRunner.cs, src/Plugins/GeneratorProvider/AspNetCoreMvc/src/Helpers/ProjectHelper.cs, src/Plugins/Polyrific.Catapult.Plugins.Abstraction/Configs/CloneTaskConfig.cs, src/Plugins/Polyrific.Catapult.Plugins.Abstraction/Configs/PushTaskConfig.cs, src/Plugins/RepositoryProvider/GitHub/src/CodeRepositoryProvider.cs, src/Plugins/RepositoryProvider/GitHub/src/GitAutomation.cs, src/Plugins/RepositoryProvider/GitHub/src/GitHubUtils.cs, src/Plugins/RepositoryProvider/GitHub/src/IGitAutomation.cs, src/Plugins/RepositoryProvider/GitHub/src/IGitHubUtils.cs, src/Plugins/RepositoryProvider/GitHub/tests/CodeRepositoryProviderTests.cs
Fix several issue in engine clone and push
=> Engine: Fix issue in clone and push task

src/API/Polyrific.Catapult.Api.Core/Entities/JobQueue.cs, src/API/Polyrific.Catapult.Api.Core/Services/JobQueueService.cs, src/API/Polyrific.Catapult.Api.Data/Migrations/20181024021024_JobOutputValues.Designer.cs, src/API/Polyrific.Catapult.Api.Data/Migrations/20181024021024_JobOutputValues.cs, src/API/Polyrific.Catapult.Api/AutoMapperProfiles/JobQueueAutoMapperProfile.cs, src/CLI/Polyrific.Catapult.Cli/Commands/Queue/RestartCommand.cs, src/Engine/Polyrific.Catapult.Engine.Core/CatapultEngine.cs, src/Engine/Polyrific.Catapult.Engine.Core/TaskRunner.cs, src/Shared/Polyrific.Catapult.Shared.Dto/JobQueue/JobDto.cs, src/Shared/Polyrific.Catapult.Shared.Dto/JobQueue/UpdateJobDto.cs, tests/Polyrific.Catapult.Engine.UnitTests/Core/TaskRunnerTests.cs
=> Save output values from engine execution

src/CLI/Polyrific.Catapult.Cli/Commands/Member/AddCommand.cs, src/CLI/Polyrific.Catapult.Cli/Commands/Model/AddCommand.cs, src/CLI/Polyrific.Catapult.Cli/Commands/Project/CloneCommand.cs, src/CLI/Polyrific.Catapult.Cli/Commands/Project/CreateCommand.cs, src/CLI/Polyrific.Catapult.Cli/Extensions/CatapultCliExtensions.cs
Change the default value of indentation for `.ToCliString()` extension method to 1. This will make all of the displayed object have indentation as default. This will affect the displayed entities both in `add` and `get` commands.
- #141
=> Rearrange cli output indentation

src/API/Polyrific.Catapult.Api.Core/Services/IJobQueueService.cs, src/API/Polyrific.Catapult.Api.Core/Services/JobQueueService.cs, src/API/Polyrific.Catapult.Api.Core/Specifications/JobQueueFilterSpecification.cs, src/API/Polyrific.Catapult.Api/Controllers/JobQueueController.cs, src/CLI/Polyrific.Catapult.Cli/Commands/Queue/GetCommand.cs, src/CLI/Polyrific.Catapult.Cli/Commands/Queue/LogCommand.cs, src/CLI/Polyrific.Catapult.Cli/Commands/QueueCommand.cs, src/Shared/Polyrific.Catapult.Shared.ApiClient/JobQueueService.cs, src/Shared/Polyrific.Catapult.Shared.Service/IJobQueueService.cs, tests/Polyrific.Catapult.Api.UnitTests/Core/Services/JobQueueServiceTests.cs, tests/Polyrific.Catapult.Cli.UnitTests/Commands/QueueCommandTests.cs
- Add API endpoint `Project/{projectId}/queue/code/{queueCode}`
- Add `queue log` command in CLI
- Update `queue get` command
Note: instead of adding new option "`--code`", I keep the existing "`--number`" option which will allow user to enter either `Id` or `Code`.
- https://github.com/Polyrific-Inc/OpenCatapult/issues/149
=> Update job queue API and CLI

src/API/Polyrific.Catapult.Api.Core/Entities/JobQueue.cs, src/API/Polyrific.Catapult.Api.Core/Services/JobQueueService.cs, src/API/Polyrific.Catapult.Api.Core/Services/ProjectDataModelService.cs, src/API/Polyrific.Catapult.Api.Core/Specifications/JobQueueFilterSpecification.cs, src/API/Polyrific.Catapult.Api.Data/ProjectMemberRepository.cs, src/API/Polyrific.Catapult.Api/AutoMapperProfiles/JobQueueAutoMapperProfile.cs, src/CLI/Polyrific.Catapult.Cli/Commands/Job/AddCommand.cs, src/CLI/Polyrific.Catapult.Cli/Commands/Job/ListCommand.cs, src/CLI/Polyrific.Catapult.Cli/Commands/Member/AddCommand.cs, src/CLI/Polyrific.Catapult.Cli/Commands/Model/AddCommand.cs, src/CLI/Polyrific.Catapult.Cli/Commands/Model/ListCommand.cs, src/CLI/Polyrific.Catapult.Cli/Commands/Plugin/ListCommand.cs, src/CLI/Polyrific.Catapult.Cli/Commands/Project/ListCommand.cs, src/CLI/Polyrific.Catapult.Cli/Commands/Property/AddCommand.cs, src/CLI/Polyrific.Catapult.Cli/Commands/Property/ListCommand.cs, src/CLI/Polyrific.Catapult.Cli/Commands/Queue/AddCommand.cs, src/CLI/Polyrific.Catapult.Cli/Commands/Queue/GetCommand.cs, src/CLI/Polyrific.Catapult.Cli/Commands/Queue/ListCommand.cs, src/CLI/Polyrific.Catapult.Cli/Commands/Service/AddCommand.cs, src/CLI/Polyrific.Catapult.Cli/Commands/Service/GetCommand.cs, src/CLI/Polyrific.Catapult.Cli/Commands/Service/ListCommand.cs, src/CLI/Polyrific.Catapult.Cli/Extensions/CatapultCliExtensions.cs, src/Shared/Polyrific.Catapult.Shared.Dto/JobQueue/JobDto.cs, tests/Polyrific.Catapult.Api.UnitTests/Core/Services/JobQueueServiceTests.cs
- Show name property instead of FK Id for FK property in all commands
- Hide detail properties in list
- Fix add member error
- #142
=> Exclude foreign key/child property in CLI

src/API/Polyrific.Catapult.Api.Core/Services/JobDefinitionService.cs, src/API/Polyrific.Catapult.Api.Core/Services/ProjectDataModelService.cs, src/CLI/Polyrific.Catapult.Cli/Commands/Job/GetCommand.cs, src/CLI/Polyrific.Catapult.Cli/Commands/Job/ListCommand.cs, src/CLI/Polyrific.Catapult.Cli/Commands/JobCommand.cs, src/CLI/Polyrific.Catapult.Cli/Commands/Model/GetCommand.cs, src/CLI/Polyrific.Catapult.Cli/Commands/ModelCommand.cs, src/CLI/Polyrific.Catapult.Cli/Commands/Project/GetCommand.cs, src/CLI/Polyrific.Catapult.Cli/Commands/ProjectCommand.cs, src/CLI/Polyrific.Catapult.Cli/Commands/Task/GetCommand.cs, src/CLI/Polyrific.Catapult.Cli/Commands/Task/ListCommand.cs, src/Shared/Polyrific.Catapult.Shared.Dto/JobDefinition/JobDefinitionDto.cs, tests/Polyrific.Catapult.Cli.UnitTests/Commands/JobCommandTests.cs, tests/Polyrific.Catapult.Cli.UnitTests/Commands/ModelCommandTests.cs, tests/Polyrific.Catapult.Cli.UnitTests/Commands/ProjectCommandTests.cs
Add `get` sub-commands for `job`, `model`, and `project` commands
- #144
=> Add get commands for several entities

src/API/Polyrific.Catapult.Api.Infrastructure/NotificationInjection.cs, src/API/Polyrific.Catapult.Api/Controllers/AccountController.cs, src/Shared/Polyrific.Catapult.Shared.Common/Notification/INotificationProvider.cs, src/Shared/Polyrific.Catapult.Shared.Common/Notification/NotificationProvider.cs, tests/Polyrific.Catapult.Api.UnitTests/Controllers/AccountControllerTests.cs, tests/Polyrific.Catapult.Api.UnitTests/Core/Services/ProjectServiceTests.cs, tests/Polyrific.Catapult.Api.UnitTests/Polyrific.Catapult.Api.UnitTests.csproj, tests/Polyrific.Catapult.Api.UnitTests/Utilities/AutoMapperUtils.cs, tests/Polyrific.Catapult.Api.UnitTests/Utilities/LoggerMock.cs
- https://github.com/Polyrific-Inc/OpenCatapult/issues/162
=> Add unit tests for Account controller

src/CLI/Polyrific.Catapult.Cli/Commands/Task/AddCommand.cs, tests/Polyrific.Catapult.Cli.UnitTests/Commands/TaskCommandTest.cs
Implement the following changes in `task add` command
- Make `type` and `provider` required
- Add the list of types and providers in the help command
- prompt for task config that has not been set in the option
- #146
=> Implement changes in task add command

src/API/Polyrific.Catapult.Api.Core/Exceptions/DuplicateJobTaskDefinitionException.cs, src/API/Polyrific.Catapult.Api.Core/Exceptions/InvalidPluginTypeException.cs, src/API/Polyrific.Catapult.Api.Core/Services/IJobDefinitionService.cs, src/API/Polyrific.Catapult.Api.Core/Services/JobDefinitionService.cs, src/API/Polyrific.Catapult.Api.Core/Services/ProjectService.cs, src/API/Polyrific.Catapult.Api.Core/Specifications/JobTaskDefinitionFilterSpecification.cs, src/API/Polyrific.Catapult.Api/Controllers/JobDefinitionController.cs, src/API/Polyrific.Catapult.Api/Controllers/ProjectController.cs, src/CLI/Polyrific.Catapult.Cli/Commands/Task/UpdateCommand.cs, src/Shared/Polyrific.Catapult.Shared.Dto/JobDefinition/CreateJobDefinitionDto.cs, src/Shared/Polyrific.Catapult.Shared.Dto/JobDefinition/CreateJobTaskDefinitionDto.cs, src/Shared/Polyrific.Catapult.Shared.Dto/JobDefinition/UpdateJobDefinitionDto.cs, src/Shared/Polyrific.Catapult.Shared.Dto/JobDefinition/UpdateJobTaskDefinitionDto.cs, tests/Polyrific.Catapult.Api.UnitTests/Core/Services/JobDefinitionServiceTests.cs
Implement the unique name validation and provider validation against the task type, when adding/updating task in the API
- #147
=> Implement name and provider validation for task API

src/API/Polyrific.Catapult.Api.Data/CatapultEngineRepository.cs, src/API/Polyrific.Catapult.Api.Data/Identity/IdentityAutoMapperProfile.cs
Fix the issue when updating engine's `LastSeen` in `CheckJob` endpoint.
The update catapult engine repository should only be for `LastSeen`, since the `IsActive` is being modified by `Suspend`/`Activate`, and the Engine's name is the Identity username, and should not be changed.
- #167
=> Fix the catapult engine update repo method

src/Shared/Polyrific.Catapult.Shared.Common/FileHelper.cs
Add `FlushAsync` before disposing stream writer as suggested in https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/93e39b8f48169cce4803615519ef87bb2a969c8e/AsyncGuidance.md#always-call-flushasync-on-streamwriters-or-streams-before-calling-dispose
=> add FlushAsync in stream writer

src/CLI/Polyrific.Catapult.Cli/Commands/Task/AddCommand.cs, src/Engine/Polyrific.Catapult.Engine/Commands/StartCommand.cs
- Add remarks in task config prompt ("Leave blank to use default value)")
- Show "Engine is waiting for a job to execute.." message after a job has been executed
- Modify the job completed message when there's an error with the job, or the job is pending
=> Improve console messages in cli and engine

builds/build-api.ps1
Fix `build-api.ps1` does not serialize the appsettings properly because the default depth of ConvertTo-Json is 2.
=> Fix build script api does not properly update appsettings

src/CLI/Polyrific.Catapult.Cli/JobQueueLogListener/SignalRJobQueueLogListener.cs
Fix the error that occured when CLI trying to connect to the SignalR hub and getting the http 404 error. It turns out the url it was trying to connect have additional slash ('/'): e.g. https://localhost:44305//jobQueueHub?jobQueueId=1
- #178
=> Fix cli getting 404 when connecting to SignalR

src/CLI/Polyrific.Catapult.Cli/Commands/Config/GetCommand.cs, src/CLI/Polyrific.Catapult.Cli/Commands/Config/SetCommand.cs, src/Engine/Polyrific.Catapult.Engine/Commands/Config/GetCommand.cs, src/Engine/Polyrific.Catapult.Engine/Commands/Config/SetCommand.cs, tests/Polyrific.Catapult.Cli.UnitTests/Commands/ConfigCommandTests.cs, tests/Polyrific.Catapult.Engine.UnitTests/Commands/ConfigCommandTests.cs
Remove the --all option in config command for CLI and Engine. It should automatically get/set all config when `--name` option is not set
- #190
=> Remove the --all option in config command

src/API/Polyrific.Catapult.Api.Data/EntityConfigs/PluginAdditionalConfigConfig.cs, src/API/Polyrific.Catapult.Api.Data/Migrations/20181106003829_RemoveConnStringAdditionalConfig.Designer.cs, src/API/Polyrific.Catapult.Api.Data/Migrations/20181106003829_RemoveConnStringAdditionalConfig.cs, src/Plugins/GeneratorProvider/AspNetCoreMvc/plugin.yml, src/Plugins/GeneratorProvider/AspNetCoreMvc/src/CodeGenerator.cs, src/Plugins/GeneratorProvider/AspNetCoreMvc/src/CodeGeneratorProvider.cs, src/Plugins/GeneratorProvider/AspNetCoreMvc/src/ProjectGenerators/MainProjectGenerator.cs, src/Plugins/GeneratorProvider/AspNetCoreMvc/tests/CodeGeneratorProviderTests.cs
Since the connection string in the AspNetCoreMvc is only used for generating the migration script, and it's stored on temporary env variable and not appsettings.json, we can just use a dummy conn string, and free the trouble for user of inputting the conn string in the generator task.
=> Remove ConnectionString additional config for AspNetCoreMvc

src/Plugins/Polyrific.Catapult.Plugins.Abstraction/Polyrific.Catapult.Plugins.Abstraction.csproj, src/Plugins/Polyrific.Catapult.Plugins.Abstraction/Polyrific.Catapult.Plugins.Abstraction.nuspec
Add `nuspec` for `Polyrific.Catapult.Plugins.Abstraction`, to be packed as NuGet package.
=> Add nuspec for plugins abstraction

src/Plugins/DatabaseProvider/EntityFrameworkCore/src/DatabaseCommand.cs, src/Plugins/DatabaseProvider/EntityFrameworkCore/src/DatabaseProvider.cs, src/Plugins/DatabaseProvider/EntityFrameworkCore/tests/DatabaseProviderTests.cs
Use published dll instead of the source code to perform update database in DeployDb plugin
=> Use published dll instead of source code when running db update

src/Engine/Polyrific.Catapult.Engine.Core/TaskRunner.cs
- Show error message from job task in the engine log
- Serialize task result before showing it in the engine log
=> Show error message from task and serialize task result to log

src/CLI/Polyrific.Catapult.Cli/Commands/Project/CreateCommand.cs, src/CLI/Polyrific.Catapult.Cli/Templates/sample.yaml
After consideration, I think we should just prompt the user for the project repository, when creating a new project using sample template, instead of having them updating them using `task update`. So I add the logic to prompt `Repository` and `IsPrivateRepository` in Create project when there's a task that require these configs.
=> Prompt for repository info when creating project using template

src/Plugins/Polyrific.Catapult.Plugins.Core/Polyrific.Catapult.Plugins.Core.nuspec
Add `.nuspec` file to be used to pack plugins core lib as NuGet package.
=> Add nuspec file for plugins core lib

src/CLI/Polyrific.Catapult.Cli/Commands/Project/CreateCommand.cs, tests/Polyrific.Catapult.Cli.UnitTests/Commands/ProjectCommandTests.cs
I want to validate plugins and external services up front before any other process when creating new project with template. It makes the user to be aware about the pre-requisites as early as possible.
=> Add validation for plugins and external services when creating project

builds/build-api.ps1, builds/build-cli.ps1, builds/build-engine.ps1
`build-api.ps1`
- add `-noRun` option to not run the api directly after the build process complete
`build-engine.ps1`:
- add `-noConfig` option to skip the config setup
- remove unused `-noPrompt` option
`build-cli.ps1`:
- add `-noConfig` option to skip the config setup
- remove unused `-noPrompt` option
=> Fix build scripts

builds/build-api.ps1, builds/build-prerequisites.ps1, src/API/Polyrific.Catapult.Api/Polyrific.Catapult.Api.csproj, src/API/Polyrific.Catapult.Api/Startup.cs
- add option `-http` and `-https` to `build-api.ps1` script
- set minimum dotnet sdk version to `2.1.301`
- set minimum `Microsoft.AspNetCore.App` package version to `2.1.1`
- set `UseHttpsRedirection` config for `Production` environment only
=> Some adjustments for development

builds/build-prerequisites.ps1, src/API/Polyrific.Catapult.Api/Polyrific.Catapult.Api.csproj
Apparently Asp.Net version `2.1.1 (sdk 2.1.301)` is known to have vulnerability. This PR updates the version to `2.1.4 (sdk 2.1.402)`.
=> Update to recommended dotnet version

src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/BuildTask.cs, src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/CloneTask.cs, src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/DeployDbTask.cs, src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/DeployTask.cs, src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/GenerateTask.cs, src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/MergeTask.cs, src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/PublishArtifactTask.cs, src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/PushTask.cs, src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/TestTask.cs, src/Engine/Polyrific.Catapult.Engine.Core/PluginItem.cs, src/Engine/Polyrific.Catapult.Engine.Core/PluginManager.cs, tests/Polyrific.Catapult.Engine.UnitTests/Core/PluginManagerTests.cs
We need to allow the plugin manager to invoke either `.exe` or `.dll` file as the plugin start file.
=> Enable exe file as plugin start file

builds/build-api.ps1, src/API/Polyrific.Catapult.Api/Dockerfile, src/API/Polyrific.Catapult.Api/Polyrific.Catapult.Api.csproj
I'd like to rename the API assembly to `ocapi.dll`. This is done to maintain consistency with other component's assembly, i.e. `occli.dll` and `ocengine.dll`.
=> Rename API assembly to ocapi.dll

builds/build-api.ps1
Add `-environment` parameter to the API build script which will set the `ASPNETCORE_ENVIRONMENT` env var.
=> Add `-environment` parameter to the build script

src/Engine/Polyrific.Catapult.Engine.Core/PluginManager.cs, src/Plugins/RepositoryProvider/Polyrific.Catapult.Plugins.GitHub/src/Polyrific.Catapult.Plugins.GitHub.csproj
- Upgrade the library to version 0.26.0-preview-0070. ref: https://github.com/terrajobst/git-istage/issues/13
- Fix issue in composing the command argument when running plugin
=> Change libgit2sharp version to fix issue in ubuntu

src/CLI/Polyrific.Catapult.Cli/Commands/Project/CreateCommand.cs, src/CLI/Polyrific.Catapult.Cli/Commands/Task/AddCommand.cs, src/CLI/Polyrific.Catapult.Cli/Commands/Task/UpdateCommand.cs, src/CLI/Polyrific.Catapult.Cli/Extensions/ConsoleExtension.cs, src/Shared/Polyrific.Catapult.Shared.Dto/Constants/ConfigType.cs, tests/Polyrific.Catapult.Cli.UnitTests/Commands/TaskCommandTest.cs
- Allow user to enter (y/n) when inputting boolean value in task config and additional config. 
- Show the [y/n] hint in the input prompt
=> Use y/n input for boolean config

src/Plugins/GeneratorProvider/Polyrific.Catapult.Plugins.AspNetCoreMvc/src/CodeGenerator.cs, src/Plugins/GeneratorProvider/Polyrific.Catapult.Plugins.AspNetCoreMvc/src/Helpers/ProjectHelper.cs
Skip running `dotnet new` for exsisting project or solution, so generator plugin does not throw error when it's restarting a previously failed generate task.
=> skip dotnet new for existing project/solution

src/Plugins/GeneratorProvider/Polyrific.Catapult.Plugins.AspNetCoreMvc/src/Helpers/ProjectHelper.cs
There's an error in generator related to failing to copy the logo.png into `workingfolder/Project/wwwroot/image` folder. I have not been able to reproduce this even after cloning the opencatapult from scratch. I figure it might be related to VM environment, but I haven't been able to successfully download it.
I push a commit to possibly fix the issue based on the error message in the log.
=> Fix possible error occured on copying logo

src/Plugins/Polyrific.Catapult.Plugins.Core/Polyrific.Catapult.Plugins.Core.nuspec
When testing a plugin that uses dotnet core, I got the runtime error that Newtonsoft.Json is not found. I think it's because the library is not specified in the dependencies, so it's not installed when the `Polyrific.Catapult.Plugins.Core` is installed. 
This PR modify the `.nuspec` file to include the dependencies
=> Add dependencies to plugins.core nuspec

src/Plugins/BuildProvider/Polyrific.Catapult.Plugins.DotNetCore/src/Program.cs, src/Plugins/DatabaseProvider/Polyrific.Catapult.Plugins.EntityFrameworkCore/src/Program.cs, src/Plugins/GeneratorProvider/Polyrific.Catapult.Plugins.AspNetCoreMvc/src/Program.cs, src/Plugins/HostingProvider/Polyrific.Catapult.Plugins.AzureAppService/src/Program.cs, src/Plugins/Polyrific.Catapult.Plugins.Core/BuildProvider.cs, src/Plugins/Polyrific.Catapult.Plugins.Core/CodeGeneratorProvider.cs, src/Plugins/Polyrific.Catapult.Plugins.Core/DatabaseProvider.cs, src/Plugins/Polyrific.Catapult.Plugins.Core/HostingProvider.cs, src/Plugins/Polyrific.Catapult.Plugins.Core/RepositoryProvider.cs, src/Plugins/Polyrific.Catapult.Plugins.Core/StorageProvider.cs, src/Plugins/Polyrific.Catapult.Plugins.Core/TaskLogger.cs, src/Plugins/Polyrific.Catapult.Plugins.Core/TaskProvider.cs, src/Plugins/Polyrific.Catapult.Plugins.Core/TestProvider.cs, src/Plugins/RepositoryProvider/Polyrific.Catapult.Plugins.GitHub/src/Program.cs, src/Plugins/TestProvider/Polyrific.Catapult.Plugins.DotNetCoreTest/src/Program.cs, tests/Polyrific.Catapult.Engine.UnitTests/Core/PluginManagerTests.cs
Plugin provider has had ability to send a message log back to the `PluginManager`. This PR adds exception stack trace to the log message to improve traceability.
=> Add stack trace to the plugin log

src/API/Polyrific.Catapult.Api.Core/Specifications/PluginFilterSpecification.cs
The query to get plugin by name is using `contains`. It should use equal (==) instead to make sure it get the correct plugin
=> Fix GetPluginByName API

src/CLI/Polyrific.Catapult.Cli/Commands/Service/ListCommand.cs
Fix issue where the Properties is not hidden in service list
- #253
=> Exclude Properties in service list

builds/build-prerequisites.ps1
Since our docs uses the opencatapult folder as the root when running the build command, I change the message in `build-prerequisites.ps1` to include the `.\builds` folder path, to avoid confusion for the user when following the build instruction in our docs.
=> Fix folder path in the build-prerequisites message

builds/build-prerequisites.ps1, builds/dotnet-install.ps1
In build-prerequisites script, inform user that we need to install dotnet sdk version 2.1. If user confirm, perform the instalation automatically
- #263
=> Automatically install dotnet in build-prerequisites script

src/Engine/Polyrific.Catapult.Engine.Core/PluginManager.cs
In addition to showing it in the engine console, we should also log the plugin's command arguments for traceability, so we can still see it after the engine shell window is closed.
=> Log the plugin command arguments for traceability

src/Plugins/HostingProvider/Polyrific.Catapult.Plugins.AzureAppService/src/AzureUtils.cs
There's an issue occured where the connection string in azure app service is not set, but the deploy task does not log any error. I made it so it'd throw exception if the app service is not having the set connection string.
=> Log setting connection string failed

src/CLI/Polyrific.Catapult.Cli/Commands/Queue/AddCommand.cs, src/CLI/Polyrific.Catapult.Cli/Commands/Queue/GetCommand.cs
- Improve the `queue add` response to add description that the job will be picked up shortly by a running engine
- Improve the `queue get` response to accentuate the part about job task status
- #296
=> Improve the queue cli response

builds/build-all.ps1, builds/build-api.ps1
Add message when running build script API, so user is aware that the terminal window should remain open for catapult to work. Also add link to learn more about catapult components
- #294
=> Improve build script response

src/Engine/Polyrific.Catapult.Engine.Core/PluginManager.cs
Since we already write the plugin trace command into the log, I think we don't need to show it in the engine console, since the trace can contain a huge json object that is hard to read anyway.
- #295
=> Remove plugin trace in engine console

src/API/Polyrific.Catapult.Api/Startup.cs, src/API/Polyrific.Catapult.Api/appsettings.json
Enable CORS in the API so the angular website can invoke it
- #320
=> Enable CORS for angular website

builds/make-release.ps1
I created a script which can be used to generate zip packages of every OpenCatapult component. It is meant to be used by OpenCatapult maintainers when releasing a new version of OpenCatapult.
**Usage**
```sh
.\builds\make-release.ps1 -version 1.0.0-beta1 -runtime win-x64
```
The output of this process will be the zip packages of the three main components: API, CLI, and Engine, as well as the six built-in Task Providers.
=> Add make-release.ps1 script

src/API/Polyrific.Catapult.Api.Core/Services/ProjectService.cs
Fix the GET `project` API where the result returns duplicate project entries when it has several members
=> Fix duplicate projects

src/Web/opencatapultweb/package.json
Add `build-prod` script to Web's package.json. It is required by the CI setup.
=> Add `build-prod` script to package.json

src/Web/opencatapultweb/src/karma.conf.js
Add `cobertura` report for the test coverage. It is required by the CI to display the coverage report in Azure Pipeline.
=> Add cobertura report for code coverage

builds/build-prerequisites.ps1
There was issue in the `build-prerequisites.ps1` script where the checking of SDK version was failed when the version contained some string values, e.g. `2.1.600-preview-009497`. In this PR I fix the issue by parsing the simple format only (e.g. `2.1.600`) to be compared with the required minimum SDK version.
=> Fix issue when parsing the installed dotnet SDK version

src/API/Polyrific.Catapult.Api/Controllers/JobQueueController.cs, src/API/Polyrific.Catapult.Api/Program.cs, tests/Polyrific.Catapult.Api.UnitTests/Controllers/JobQueueControllerTests.cs
Fix issue where a removed Engine was still able to access API. The focus of this fix is only on the controllers which require Engine role authorization (`[Authorize(Policy = AuthorizePolicy.UserRoleEngineAccess)]`). I don't think we need to apply the same checking for controllers with other user role authorization because it has had preventive mechanism through user login.
- Related Issues: https://github.com/Polyrific-Inc/OpenCatapult/issues/319
=> Fix access issue for unregistered engines

builds/build-api.ps1, builds/build-cli.ps1, builds/build-engine.ps1, src/API/Polyrific.Catapult.Api/Program.cs, src/CLI/Polyrific.Catapult.Cli/Commands/BaseCommand.cs, src/CLI/Polyrific.Catapult.Cli/Extensions/ConsoleExtension.cs, src/Engine/Polyrific.Catapult.Engine/Commands/BaseCommand.cs, src/Engine/Polyrific.Catapult.Engine/Extensions/ConsoleExtension.cs
Set title of the console window (PowerShell) when running OpenCatapult components. Apparently this fixes will only set the title when the app is running, not permanently. However I think this behavior is appropriate because when the app stops, the process is detached from the console (hence it won't make sense to keep the title for detached processes).
- Related Issues: https://github.com/Polyrific-Inc/OpenCatapult/issues/321
=> Set console window titles

src/API/Polyrific.Catapult.Api.Data/EntityConfigs/BaseEntityConfig.cs, src/CLI/Polyrific.Catapult.Cli/Extensions/CatapultCliExtensions.cs
Currently the date time for created and updated dates are displayed in UTC. It should be displayed in the local time instead. Setting the datetime kind to utc would allow the web ui to automatically display the local time as well.
=> Fix timezone issue for Created and Updated date

src/API/Polyrific.Catapult.Api.Core/Services/IJobQueueService.cs, src/API/Polyrific.Catapult.Api.Core/Services/JobQueueService.cs, src/API/Polyrific.Catapult.Api.Core/Specifications/JobQueueFilterSpecification.cs, src/API/Polyrific.Catapult.Api/Controllers/JobQueueController.cs, src/API/Polyrific.Catapult.Api/Hubs/JobQueueHub.cs, src/CLI/Polyrific.Catapult.Cli/Commands/Queue/LogCommand.cs, src/CLI/Polyrific.Catapult.Cli/JobQueueLogListener/IJobQueueLogListener.cs, src/CLI/Polyrific.Catapult.Cli/JobQueueLogListener/SignalRJobQueueLogListener.cs, src/Engine/Polyrific.Catapult.Engine.Core/CatapultEngine.cs, src/Engine/Polyrific.Catapult.Engine.Core/JobLogger/IJobLogWriter.cs, src/Engine/Polyrific.Catapult.Engine.Core/JobLogger/JobLoggerProvider.cs, src/Engine/Polyrific.Catapult.Engine.Core/JobLogger/JobScope.cs, src/Engine/Polyrific.Catapult.Engine.SignalRLogger/SignalRJobLogWriter.cs, src/Shared/Polyrific.Catapult.Shared.Dto/Constants/JobQueueLog.cs, tests/Polyrific.Catapult.Api.UnitTests/Controllers/JobQueueControllerTests.cs, tests/Polyrific.Catapult.Api.UnitTests/Core/Services/JobQueueServiceTests.cs, tests/Polyrific.Catapult.Cli.UnitTests/Commands/QueueCommandTests.cs
This PR fixes issue where the logs of queues from different projects got mixed when being queried with the wrong `project name` and `queue id` combination.
- Related Issues: https://github.com/Polyrific-Inc/OpenCatapult/issues/322
=> Include Project Id when retrieving Queue

builds/build-all.ps1
Fix build script arguments where the `-configuration` is not passed to the CLI and Engine scripts.
=> Fix build script arguments

builds/build-all.ps1, builds/build-prerequisites.ps1
Fix `build-all.ps1` script so it can be run on `pwsh` (PowerShell 6). Note that `Get-WmiObject` is deprecated, so I change it with `Get-CimInstance`.
=> Fix build-all.ps1 script for pwsh

builds/build-web.ps1
Add build script for Web UI. This is just a naive version, which only runs `npm install` and `npm run start`. It doesn't have API URL setting, and it has not been included in the `build-all.ps1` script, which we'll do it later in separate PRs.
=> Add build-web.ps1 script

builds/build-web.ps1, src/API/Polyrific.Catapult.Api/Startup.cs, src/API/Polyrific.Catapult.Api/appsettings.json
Fix cors policy to allow multiple origins.
=> Fix cors policy to allow multiple origins

src/Web/opencatapultweb/src/app/core/services/project-history.service.spec.ts, src/Web/opencatapultweb/src/app/core/services/project-history.service.ts, src/Web/opencatapultweb/src/app/project/components/project-info-form/project-info-form.component.ts, src/Web/opencatapultweb/src/app/project/project-archive-detail/project-archive-detail.component.spec.ts, src/Web/opencatapultweb/src/app/project/project-archive-detail/project-archive-detail.component.ts, src/Web/opencatapultweb/src/app/project/project-clone/project-clone.component.html, src/Web/opencatapultweb/src/app/project/project-clone/project-clone.component.ts, src/Web/opencatapultweb/src/app/project/project-dashboard/project-dashboard.component.spec.ts, src/Web/opencatapultweb/src/app/project/project-detail/project-detail.component.spec.ts, src/Web/opencatapultweb/src/app/project/project-detail/project-detail.component.ts, src/Web/opencatapultweb/src/app/project/project-error/project-error.component.html, src/Web/opencatapultweb/src/app/project/project-error/project-error.component.spec.ts, src/Web/opencatapultweb/src/app/project/project-error/project-error.component.ts, src/Web/opencatapultweb/src/app/project/project-info/project-info.component.html, src/Web/opencatapultweb/src/app/project/project-info/project-info.component.spec.ts, src/Web/opencatapultweb/src/app/project/project-info/project-info.component.ts, src/Web/opencatapultweb/src/app/project/project-routing.module.ts, src/Web/opencatapultweb/src/app/project/project.module.ts, src/Web/opencatapultweb/src/app/project/services/project-resolver.service.spec.ts, src/Web/opencatapultweb/src/app/project/services/project-resolver.service.ts
- Show error page when trying to open project that does not exist
- Bugfix in project dashboard
=> Show error when project is not found

docs/home/intro.md, docs/home/start.md, docs/task-providers/build-provider.md, docs/task-providers/database-provider.md, docs/task-providers/generator-provider.md, docs/task-providers/hosting-provider.md, docs/task-providers/repository-provider.md, docs/task-providers/task-provider.md, docs/task-providers/test-provider.md, docs/user-guides/job-definitions.md
Rename the remaining docs and guide that still use `Plugins.` namespace and rename it to `TaskProviders.`
=> Docs: Rename Plugins to TaskProviders

src/Web/opencatapultweb/src/app/project/job-queue/job-queue-detail/job-queue-detail.component.spec.ts, src/Web/opencatapultweb/src/app/project/job-queue/job-queue-detail/job-queue-detail.component.ts, src/Web/opencatapultweb/src/app/project/job-queue/job-queue-error/job-queue-error.component.html, src/Web/opencatapultweb/src/app/project/job-queue/job-queue-error/job-queue-error.component.spec.ts, src/Web/opencatapultweb/src/app/project/job-queue/job-queue-error/job-queue-error.component.ts, src/Web/opencatapultweb/src/app/project/job-queue/job-queue-log/job-queue-log.component.spec.ts, src/Web/opencatapultweb/src/app/project/job-queue/job-queue-log/job-queue-log.component.ts, src/Web/opencatapultweb/src/app/project/job-queue/job-queue-routing.module.ts, src/Web/opencatapultweb/src/app/project/job-queue/job-queue.module.ts, src/Web/opencatapultweb/src/app/project/job-queue/services/job-queue-resolver.service.spec.ts, src/Web/opencatapultweb/src/app/project/job-queue/services/job-queue-resolver.service.ts
Refactor job queue detail and job queue log page to use route resolver, so we can redirect to error page when data is not found, without rendering the page first
=> Show error when job queue is not found 

src/API/Polyrific.Catapult.Api.Core/Entities/JobDefinition.cs, src/API/Polyrific.Catapult.Api.Core/Exceptions/JobQueueInProgressException.cs, src/API/Polyrific.Catapult.Api.Core/Exceptions/JobTaskDefinitionTypeException.cs, src/API/Polyrific.Catapult.Api.Core/Exceptions/MultipleDeletionJobException.cs, src/API/Polyrific.Catapult.Api.Core/Services/IJobDefinitionService.cs, src/API/Polyrific.Catapult.Api.Core/Services/JobDefinitionService.cs, src/API/Polyrific.Catapult.Api.Core/Services/ProjectService.cs, src/API/Polyrific.Catapult.Api.Core/Specifications/JobDefinitionFilterSpecification.cs, src/API/Polyrific.Catapult.Api.Core/Specifications/JobTaskDefinitionFilterSpecification.cs, src/API/Polyrific.Catapult.Api.Data/Migrations/20190319073105_JobDefinitionDeletion.Designer.cs, src/API/Polyrific.Catapult.Api.Data/Migrations/20190319073105_JobDefinitionDeletion.cs, src/API/Polyrific.Catapult.Api/Controllers/JobDefinitionController.cs, src/Shared/Polyrific.Catapult.Shared.Dto/Constants/JobTaskDefinitionType.cs, src/Shared/Polyrific.Catapult.Shared.Dto/JobDefinition/CreateJobDefinitionDto.cs, src/Shared/Polyrific.Catapult.Shared.Dto/JobDefinition/JobDefinitionDto.cs, tests/Polyrific.Catapult.Api.UnitTests/Controllers/JobDefinitionControllerTests.cs, tests/Polyrific.Catapult.Api.UnitTests/Core/Services/JobDefinitionServiceTests.cs
Implement the changes in API to support job definition for resource deletion. Changes in UI (CLI/Web) will be done in separate PR
- Related Issues: #310
=> Implement API for deletion job definition

src/API/Polyrific.Catapult.Api.Data/Migrations/20190228050357_RenameDotNetCoreAndTest.cs
Fix the issue in migration script where it does not have the script to update the `Plugins.DotNetCore` to `TaskProviders.DotNetCore`. 
Note that this only fix the data when the migration is performed from scratch. It won't update the data when it's running the existing database that have previously run the script `20190228050357_RenameDotNetCoreAndTest`. Manual fix would have to be done for this scenario
=> Fix migration script where it does not properly rename the DotNetCore Plugin

docs/home/start.md
Modify the quick start document to add notes about skipping web build, in case the user does not want to install node.js during quick start
=> docs: add note if user want to skip web build

src/Web/opencatapultweb/angular.json, src/Web/opencatapultweb/src/app/app.module.ts, src/Web/opencatapultweb/src/app/config/config.service.provider.ts, src/Web/opencatapultweb/src/app/config/config.service.spec.ts, src/Web/opencatapultweb/src/app/config/config.service.ts, src/Web/opencatapultweb/src/app/core/auth/auth.service.ts, src/Web/opencatapultweb/src/app/core/interceptors/jwt.interceptor.ts, src/Web/opencatapultweb/src/app/core/services/api.service.ts, src/Web/opencatapultweb/src/app/core/services/signalr.service.ts, src/Web/opencatapultweb/src/app/project/project-clone/project-clone.component.spec.ts, src/Web/opencatapultweb/src/app/project/project-dashboard/project-dashboard.component.spec.ts, src/Web/opencatapultweb/src/config.json, src/Web/opencatapultweb/src/environments/environment.prod.ts, src/Web/opencatapultweb/src/environments/environment.ts
In order to separate between app and config, I move out some configs from `environment.ts` to `config.json`. This way, the configs will not be compiled as part of the app and can be modified on the fly when being deployed to different environments.
- Related Issues: https://github.com/Polyrific-Inc/OpenCatapult/issues/409
- Other links:
- https://www.jvandemo.com/how-to-use-environment-variables-to-configure-your-angular-application-without-a-rebuild/
- https://juristr.com/blog/2018/01/ng-app-runtime-config/
=> Move env config to config.json

docs/dev-guides/manual-build.md, docs/home/intro.md, docs/home/start.md
Move the guide to manually build the components into its own section, and make reference to it from Quick Start.
=> [Docs] Move manual build guide out from quick start

docs/summary.md
Previously I moved the manual build guide out from the quick start into its own section. This PR adds the new section into the summary file so it's shown up in the left nav panel.
=> Add manual build guide to summary

src/API/Polyrific.Catapult.Api/SecurityRequirementsOperationFilter .cs, src/API/Polyrific.Catapult.Api/Startup.cs
Add Authorize functionality to API swagger. It adds the `Authorize` button to the Swagger UI, which allow the user to enter the bearer token.
=> Add Authorize functionality to API swagger

src/API/Polyrific.Catapult.Api/Startup.cs
As swagger only makes sense for development, I enable it only on the environment.
=> Enable swagger on development env only

builds/build-all.ps1, docs/dev-guides/build-scripts.md
Currently when running `build-all` script, there's occasional error happened in build CLI or Build Engine window, because the .dll is being used by another process. This PR try to mitigate this by adding a thread sleep after opening the CLI window, so that it does not clash with Build Engine.
=> Sleep the build-all script after opening cli window

docs/user-guides/create-first-project-web.md
Fix typo **Job Queues** should be **Job Definitions** on `create-first-project-web.md` page, section **Queue the job**
=> [Doc] Fix typo `Job Queues` should be `Job Definitions`

docs/dev-guides/project-template.md, docs/task-providers/hosting-provider.md, docs/user-guides/sample-project.md
* Fix typo `AzureAppService` should be `Azure` on create required external services in the sample project section.
=> [Doc] Fix typo `AzureAppService` should be `Azure`

Polyrific.Catapult.Engine.sln, src/API/Polyrific.Catapult.Api.Core/Exceptions/DeletionJobDefinitionNotFound.cs, src/API/Polyrific.Catapult.Api.Core/Exceptions/JobTaskDefinitionTypeException.cs, src/API/Polyrific.Catapult.Api.Core/Exceptions/MultipleDeletionJobException.cs, src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/DeleteHostingTask.cs, src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/DeleteRepositoryTask.cs, src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/IDeleteHostingTask.cs, src/Engine/Polyrific.Catapult.Engine.Core/JobTasks/IDeleteRepositoryTask.cs, src/Plugins/GenericTaskProvider/Polyrific.Catapult.TaskProviders.GenericCommand/plugin.yml, src/Plugins/GenericTaskProvider/Polyrific.Catapult.TaskProviders.GenericCommand/src/CommandProviders/CommandHelper.cs, src/Plugins/GenericTaskProvider/Polyrific.Catapult.TaskProviders.GenericCommand/src/CommandProviders/CommandTextHelper.cs, src/Plugins/GenericTaskProvider/Polyrific.Catapult.TaskProviders.GenericCommand/src/Polyrific.Catapult.TaskProviders.GenericCommand.csproj, src/Plugins/GenericTaskProvider/Polyrific.Catapult.TaskProviders.GenericCommand/src/Program.cs, src/Plugins/GenericTaskProvider/Polyrific.Catapult.TaskProviders.GenericCommand/tests/GenericTaskProviderTests.cs, src/Plugins/GenericTaskProvider/Polyrific.Catapult.TaskProviders.GenericCommand/tests/Polyrific.Catapult.TaskProviders.GenericCommand.UnitTests.csproj, src/Plugins/Polyrific.Catapult.TaskProviders.Core/Configs/DeleteRepositoryTaskConfig.cs, src/Plugins/Polyrific.Catapult.TaskProviders.Core/GenericTaskProvider.cs, src/Plugins/Polyrific.Catapult.TaskProviders.Core/RepositoryProvider.cs, src/Shared/Polyrific.Catapult.Shared.Dto/Constants/PluginType.cs
- Create generic task providers base class
- Implement a built-in generic task providers that run generic commands
- Related Issues: #400
=> Implement generic task provider

builds/build-all.ps1, builds/build-cli.ps1, builds/build-engine.ps1
This is an attempt to fix the race condition issue when executing `build-all.ps1` script. In this fix, I differentiate between the publishing process and opening new shell windows. All publishing processes are done in the main shell window so they are executed sequentially. Opening new shell windows after publishing won't raise the race condition issue.
=> Fix race condition issue when executing build scripts

builds/build-all.ps1, builds/build-api.ps1, builds/build-cli.ps1, builds/build-engine.ps1, docs/dev-guides/build-scripts.md
- The `build-engine` and `build-cli` when run individually does not change the directory to its published folder. This PR fixes this.
- Avoid issue #412 by using the IsNullOrWhitespace function
- Related Issues: #412
=> Several build script improvement

src/API/Polyrific.Catapult.Api/Polyrific.Catapult.Api.csproj, src/API/Polyrific.Catapult.Api/notificationconfig.json
Add a predefined `notificationconfig.json` file so it doesn't have to be created on startup. This is a temporary workaround for https://github.com/Polyrific-Inc/OpenCatapult/issues/458.
- Related Issues: https://github.com/Polyrific-Inc/OpenCatapult/issues/458
=> Add a predefined notificationconfig.json

src/Web/opencatapultweb/angular.json, src/Web/opencatapultweb/src/web.config
Add `web.config` to Web UI to map JSON file as static content. This mapping is required when hosting the Web UI in Azure App Service. Without this mapping, the `config.json` file is failed to be served.
=> Add `web.config` to Web UI

builds/build-api.ps1, builds/build-web.ps1
- Allow retry inputting connection string when db migration failed
- Try fix mac error related to certificate in build web
- Related Issues: #436
=> Build script - Allow retry connection string

src/API/Polyrific.Catapult.Api/Controllers/ProjectController.cs, src/Web/opencatapultweb/src/web.config
- When a basic user that has not been assigned to any project tried to login, it'll get 403 error because she does not have a project access in his claim when trying to invoke `GET /project`. My proposal is to change the authorization policy to use `Authorize` so the project claim does not need to be checked. The logic inside the `GET /project` is already getting the project that the current user is a member.
- The current azure app service deployment does not seem to be able to handle angular router properly. This PR also tried to fix this by adding a rewrite rule in the web.config (ref: https://stackoverflow.com/questions/42321275/need-to-fix-routing-issue-with-angular-2-running-on-an-azure-app-service/42872500). However it haven't been tested in real azure app service deployment
=> Fix user basic error & angular route issue in azure

src/Web/opencatapultweb/src/web.config
Fix 404 error that happened in Web in AzureAppService deployment when trying to request for yaml file, e.g. `sample.yaml` template file
=> Fix azure web deployment could not load yaml file

builds/build-all.ps1, builds/build-api.ps1
At the moment, `publishing API` process is put as the last step in the `build-all.ps1` script. It often makes the user miss the step to enter connection string value because the main window is hidden under the newly opened windows. This PR separate the `Publishing API` and `Running API` steps so the user won't miss the required actions during the build process.
=> Fix component builds order

src/Web/opencatapultweb/src/app/project/job-queue/job-queue-detail/job-queue-detail.component.css, src/Web/opencatapultweb/src/app/project/job-queue/job-queue-detail/job-queue-detail.component.ts
Fix styling issue in job queue detail page.
Before:
After:
=> Fix styling in job queue detail

src/API/Polyrific.Catapult.Api.Core/Services/IProjectMemberService.cs, src/API/Polyrific.Catapult.Api.Core/Services/ProjectMemberService.cs, src/API/Polyrific.Catapult.Api/Controllers/ProjectMemberController.cs, tests/Polyrific.Catapult.Api.UnitTests/Controllers/ProjectMemberControllerTests.cs, tests/Polyrific.Catapult.Api.UnitTests/Core/Services/ProjectMemberServiceTests.cs
Currently when we're adding a new user in Project Member page, the new user would not get the registration email to confirm her account. I fix this for now by copying the code in `POST account/register` into the create project member controller. 
Later when implementing the #469, we can then move the `Create User` logic, including the notification, into the service, so it can be called both in `account/register` and `project/member`.
=> Fix issue email not sent when adding new user via project member

src/API/Polyrific.Catapult.Api/Startup.cs, src/API/Polyrific.Catapult.Api/wwwroot/Default.html
Show a default html static file when opening API website hosted not in Development enviroment
=> API: Show default html file when not in Development

src/API/Polyrific.Catapult.Api/Controllers/JobDefinitionController.cs
Fix the api method for bulk creating task where the request body does not properly deserialized.
=> Fix the API method for bulk task create

src/Web/opencatapultweb/package.json, src/Web/opencatapultweb/src/app/core/constants/property-data-types.ts, src/Web/opencatapultweb/src/app/core/enums/property-data-type.ts, src/Web/opencatapultweb/src/app/project/data-model/components/data-model-form/data-model-form.component.spec.ts, src/Web/opencatapultweb/src/app/project/data-model/components/data-model-form/data-model-form.component.ts, src/Web/opencatapultweb/src/app/project/data-model/components/data-model-property-form/data-model-property-form.component.html, src/Web/opencatapultweb/src/app/project/data-model/components/data-model-property-form/data-model-property-form.component.spec.ts, src/Web/opencatapultweb/src/app/project/data-model/components/data-model-property-form/data-model-property-form.component.ts
- Automatically update label when entering model and property name
- Suggest Data Type and Control type based on entered property name
- Suggest control type based on selected data type
- Update property name & label to related entity name when related entity is selected
- modify property name & label to plural/singular when relational type is selected
=> Improve data model web UI to display suggestion

src/Web/opencatapultweb/src/app/shared/components/additional-config-form/additional-config-form.component.spec.ts, src/Web/opencatapultweb/src/app/shared/components/additional-config-form/additional-config-form.component.ts, src/Web/opencatapultweb/src/app/shared/components/pull-task-config-form/pull-task-config-form.component.spec.ts, src/Web/opencatapultweb/src/app/shared/components/pull-task-config-form/pull-task-config-form.component.ts, src/Web/opencatapultweb/src/app/shared/components/push-task-config-form/push-task-config-form.component.spec.ts, src/Web/opencatapultweb/src/app/shared/components/push-task-config-form/push-task-config-form.component.ts, src/Web/opencatapultweb/src/app/shared/components/task-config-form/task-config-form.component.spec.ts, src/Web/opencatapultweb/src/app/shared/services/utility.service.spec.ts, src/Web/opencatapultweb/src/app/shared/services/utility.service.ts, src/Web/opencatapultweb/src/app/shared/shared.module.ts
Fix the checkbox in task config and additional config always get checked due to the config object is deserialized from `Dictionary<string, string>` type, and the `'false'` string in javascript is truthy
=> Fix checkbox task config always checked

src/Engine/Polyrific.Catapult.Engine.Core/CatapultEngine.cs
Make the project deletion run last in engine when running deletion job. This is to avoid error when calling SendNotification endpoint, which still require the current Project/Job to be in the database
=> Modify the order of deleting a project in engine

src/Web/opencatapultweb/src/app/project/job-queue/job-queue-log/job-queue-log.component.ts
After investigation, I think the job queue log got hang because the connection is closed prematurely.
This is happened because there's so many message in the queue that there's actually a delay between what is currently sent by the engine, and what is received by the client. The connection closed prematurely because the engine is already in the closing state, and it had sent the event of  `EndJob`, which will make the signalr client to be closed.
My solution is to retrieve all of the log from the API using `queue/{id}/logs` endpoint when the `EndJob` event is received. 
Note that this will need testing in the azure deployment, since I cannot reproduce the same issue in the local. However, I've tested that the changes does not affect the workflow in the local environment.
=> Fix job queue log hang

src/Web/opencatapultweb/src/app/core/services/job-queue.service.ts, src/Web/opencatapultweb/src/app/project/job-queue/job-queue-detail/job-queue-detail.component.html, src/Web/opencatapultweb/src/app/project/job-queue/job-queue-detail/job-queue-detail.component.ts, src/Web/opencatapultweb/src/app/project/job-queue/job-queue-list/job-queue-list.component.html, src/Web/opencatapultweb/src/app/project/job-queue/job-queue-list/job-queue-list.component.spec.ts, src/Web/opencatapultweb/src/app/project/job-queue/job-queue-list/job-queue-list.component.ts, src/Web/opencatapultweb/src/app/project/job-queue/job-queue-log/job-queue-log.component.css, src/Web/opencatapultweb/src/app/project/job-queue/job-queue-log/job-queue-log.component.html, src/Web/opencatapultweb/src/app/project/job-queue/job-queue-log/job-queue-log.component.ts, src/Web/opencatapultweb/src/app/project/job-queue/job-queue-routing.module.ts, src/Web/opencatapultweb/src/app/project/job-queue/job-queue/job-queue.component.html, src/Web/opencatapultweb/src/app/project/job-queue/job-queue/job-queue.component.spec.ts, src/Web/opencatapultweb/src/app/project/job-queue/job-queue/job-queue.component.ts
- Add restart and cancel button in queue log page
- remove output values from job queue detail fields
-  use routing in job queue tabs so when user `back` from job queue detail, it is shown the job queue list containing the opened job queue
=> Several bugfix in job queue

src/API/Polyrific.Catapult.Api.Infrastructure/NotificationInjection.cs, src/API/Polyrific.Catapult.Api/Program.cs, src/API/Polyrific.Catapult.Api/notificationconfig.json, src/Shared/Polyrific.Catapult.Shared.Common/Notification/NotificationConfig.cs
Fix issue in `notificationconfig.json` that cannot be created in restricted environment. Instead, make the `notificationconfig.json` similar to appsettings.json, that can be deserialized into `IConfiguration` class
- Modify service injection of `NotificationConfig`
- Modify the structure of `notificationconfig.json`
- Related Issues: #458
=> use notification config like appsettings.json

src/Web/opencatapultweb/src/app/layouts/home-layout/home-layout.component.css, src/Web/opencatapultweb/src/app/layouts/home-layout/home-layout.component.html, src/Web/opencatapultweb/src/app/layouts/home-layout/home-layout.component.ts, src/Web/opencatapultweb/src/app/layouts/login-layout/login-layout.component.css, src/Web/opencatapultweb/src/app/layouts/login-layout/login-layout.component.html, src/Web/opencatapultweb/src/app/layouts/login-layout/login-layout.component.ts
Add a current web version used on footer Web UI
- Related Issues: https://github.com/Polyrific-Inc/OpenCatapult/issues/485
- Related Work Items:
- Other links:
=> Add Version Page in Web UI

src/Web/opencatapultweb/src/app/project/data-model/data-model-property/data-model-property.component.ts, src/Web/opencatapultweb/src/app/project/data-model/data-model/data-model.component.ts, src/Web/opencatapultweb/src/app/project/job-definition/job-definition/job-definition.component.ts, src/Web/opencatapultweb/src/app/project/job-definition/job-task-definition/job-task-definition.component.ts, src/Web/opencatapultweb/src/app/project/project-archive-detail/project-archive-detail.component.ts, src/Web/opencatapultweb/src/app/project/project-deleting/project-deleting.component.ts, src/Web/opencatapultweb/src/app/project/project-detail/project-detail.component.ts
Add resource name in the delete confirmation text, to ease the deletion process
- Related Issues: #508
=> Add resource name in delete confirmation

src/API/Polyrific.Catapult.Api.Core/Services/ProjectService.cs, tests/Polyrific.Catapult.Api.UnitTests/Core/Services/ProjectServiceTests.cs
Fix issue in clone project where the property with `RelatedDataModelId` is still referencing the model from the source project, instead of the new cloned project.
=> Fix issue in clone project

src/API/Polyrific.Catapult.Api.Core/Entities/JobQueue.cs, src/API/Polyrific.Catapult.Api.Core/Services/JobQueueService.cs, src/API/Polyrific.Catapult.Api.Data/Migrations/20190507025653_RemoveRelationJobQueueDefinition.Designer.cs, src/API/Polyrific.Catapult.Api.Data/Migrations/20190507025653_RemoveRelationJobQueueDefinition.cs, src/API/Polyrific.Catapult.Api/AutoMapperProfiles/JobQueueAutoMapperProfile.cs, src/Web/opencatapultweb/src/app/layouts/home-layout/home-layout.component.css, src/Web/opencatapultweb/src/app/login/login.component.css, tests/Polyrific.Catapult.Api.UnitTests/Core/Services/JobQueueServiceTests.cs
Remove the foreign key reference from `JobQueue` to `JobDefinition`, so that a job definition can still be deleted even it has a previously run queue
- Related Issues: #499
=> Fix job queue reference so it does not tied to job definition

src/API/Polyrific.Catapult.Api.Data/Polyrific.Catapult.Api.Data.csproj
This PR fixes the `package downgrade` issue when publishing the API with `win-x64` runtime.
=> Fix package downgrade issue

src/Web/Polyrific.Catapult.Web/ClientApp/src/app/shared/components/confirmation-with-input-dialog/confirmation-with-input-dialog.component.html
Remove scrollbar on confirm delete popup
- Related Issues: #524
=> Remove scrollbar on confirm delete popup

src/API/Polyrific.Catapult.Api.Core/Services/IJobDefinitionService.cs, src/API/Polyrific.Catapult.Api.Core/Services/JobDefinitionService.cs, src/API/Polyrific.Catapult.Api.Core/Services/ProjectService.cs, src/API/Polyrific.Catapult.Api.Core/Specifications/TaskProviderAdditionalConfigFilterSpecification.cs
I found an issue where the job definition cannot be expanded after creating a new project. It turns out it's because the secret config was not properly encrypted. The PR fixes this issue
=> Fix issue occured after setting secret config in create project

src/API/Polyrific.Catapult.Api.Core/Exceptions/TaskProviderAdditionalConfigAllowedValuesException.cs, src/API/Polyrific.Catapult.Api.Core/Services/JobDefinitionService.cs, src/API/Polyrific.Catapult.Api/Controllers/JobDefinitionController.cs, src/Web/Polyrific.Catapult.Web/ClientApp/src/app/shared/components/additional-config-field/additional-config-field.component.html, src/Web/Polyrific.Catapult.Web/ClientApp/src/app/shared/components/additional-config-field/additional-config-field.component.spec.ts, src/Web/Polyrific.Catapult.Web/ClientApp/src/app/shared/components/additional-config-form/additional-config-form.component.spec.ts, src/Web/Polyrific.Catapult.Web/ClientApp/src/app/shared/components/build-task-config-form/build-task-config-form.component.spec.ts, src/Web/Polyrific.Catapult.Web/ClientApp/src/app/shared/components/deploy-db-task-config-form/deploy-db-task-config-form.component.spec.ts, src/Web/Polyrific.Catapult.Web/ClientApp/src/app/shared/components/deploy-task-config-form/deploy-task-config-form.component.spec.ts, src/Web/Polyrific.Catapult.Web/ClientApp/src/app/shared/components/generate-task-config-form/generate-task-config-form.component.spec.ts, src/Web/Polyrific.Catapult.Web/ClientApp/src/app/shared/components/merge-task-config-form/merge-task-config-form.component.spec.ts, src/Web/Polyrific.Catapult.Web/ClientApp/src/app/shared/components/pull-task-config-form/pull-task-config-form.component.spec.ts, src/Web/Polyrific.Catapult.Web/ClientApp/src/app/shared/components/push-task-config-form/push-task-config-form.component.spec.ts, src/Web/Polyrific.Catapult.Web/ClientApp/src/app/shared/components/test-task-config-form/test-task-config-form.component.spec.ts, tests/Polyrific.Catapult.Api.UnitTests/Core/Services/JobDefinitionServiceTests.cs
When an additional config have allowed values, the web ui should use select control, instead of plain textbox.
=> Use select control for additional config with allowed values

src/API/Polyrific.Catapult.Api.Core/Entities/JobTaskDefinition.cs, src/API/Polyrific.Catapult.Api.Core/Services/IJobDefinitionService.cs, src/API/Polyrific.Catapult.Api.Core/Services/JobDefinitionService.cs, src/API/Polyrific.Catapult.Api.Core/Services/JobQueueService.cs, src/API/Polyrific.Catapult.Api.Data/EntityConfigs/JobTaskDefinitionConfig.cs, src/API/Polyrific.Catapult.Api/Controllers/JobDefinitionController.cs, src/Shared/Polyrific.Catapult.Shared.Dto/JobDefinition/JobTaskDefinitionDto.cs, src/Web/Polyrific.Catapult.Web/ClientApp/src/app/core/models/job-definition/job-task-definition-dto.ts, src/Web/Polyrific.Catapult.Web/ClientApp/src/app/core/services/job-definition.service.ts, src/Web/Polyrific.Catapult.Web/ClientApp/src/app/project/job-definition/job-definition/job-definition.component.html, src/Web/Polyrific.Catapult.Web/ClientApp/src/app/project/job-definition/job-definition/job-definition.component.spec.ts, src/Web/Polyrific.Catapult.Web/ClientApp/src/app/project/job-definition/job-definition/job-definition.component.ts, src/Web/Polyrific.Catapult.Web/ClientApp/src/app/project/job-definition/job-task-definition/job-task-definition.component.css, src/Web/Polyrific.Catapult.Web/ClientApp/src/app/project/job-definition/job-task-definition/job-task-definition.component.html, src/Web/Polyrific.Catapult.Web/ClientApp/src/app/project/job-definition/job-task-definition/job-task-definition.component.spec.ts, src/Web/Polyrific.Catapult.Web/ClientApp/src/app/project/project-detail/project-detail.component.html, src/Web/Polyrific.Catapult.Web/ClientApp/src/app/project/project-detail/project-detail.component.ts, tests/Polyrific.Catapult.Api.UnitTests/Controllers/JobDefinitionControllerTests.cs, tests/Polyrific.Catapult.Api.UnitTests/Core/Services/JobQueueServiceTests.cs
Highlight the task have incorrect configurations in job definition list
- Related Issues: #527
=> Highlight task that have incorrect configuration

src/API/Polyrific.Catapult.Api.Core/Services/ProjectDataModelService.cs, src/API/Polyrific.Catapult.Api/Controllers/JobQueueController.cs, src/API/Polyrific.Catapult.Api/LoggerExtensions.cs, src/Shared/Polyrific.Catapult.Shared.Common/FileHelper.cs
Fix occasional issue where we got the error `The process cannot access the file 'log file' because it is being used by another process.` in SignalR engine log
=> Fix signalr file lock

src/API/Polyrific.Catapult.Api.Data/Migrations/CatapultSqliteDb/20190507060100_SqliteInitMigration.cs, src/API/Polyrific.Catapult.Api.Data/ProjectRepository.cs
When using sqlite, I get an error when trying to delete a project: `SQLite Error 19: 'FOREIGN KEY constraint failed'`
After investigating, the issue occured because there's often foreign key conflict in `ProjectDataModels.RelatedDataModelId`. It seems the `mssql` handles this more intelligently, so that the execution order of a deletion process does not have the same error.  
My solution here is to modify the `20190507060100_SqliteInitMigration` migration file so that the `RelatedDataModelId` foreign key is `Cascade` on delete. I did not create a new migration file bacause it would result in error since sqlite does not really support modifying the foreign key property:
`https://github.com/aspnet/EntityFramework.Docs/issues/32`
Note: If you currently have existing database file, you would …
=> Fix issue in delete project when using sqlite

src/API/Polyrific.Catapult.Api/CustomWebHostService.cs, src/API/Polyrific.Catapult.Api/Polyrific.Catapult.Api.csproj, src/API/Polyrific.Catapult.Api/Program.cs, src/API/Polyrific.Catapult.Api/WebHostExtensions.cs, tools/api/install-service.bat
Allow API to run as Windows service. The `install-service.bat` script will help the users to install the API to the Windows Service. This script will be copied to the root folder of the published package.
=> Run API as windows service

src/Web/Polyrific.Catapult.Web/ClientApp/src/app/external-service/components/external-service-info-dialog/external-service-info-dialog.component.ts, src/Web/Polyrific.Catapult.Web/ClientApp/src/app/external-service/components/external-service-new-dialog/external-service-new-dialog.component.ts, src/Web/Polyrific.Catapult.Web/ClientApp/src/app/project/data-model/components/data-model-info-dialog/data-model-info-dialog.component.spec.ts, src/Web/Polyrific.Catapult.Web/ClientApp/src/app/project/data-model/components/data-model-info-dialog/data-model-info-dialog.component.ts, src/Web/Polyrific.Catapult.Web/ClientApp/src/app/project/data-model/components/data-model-new-dialog/data-model-new-dialog.component.spec.ts, src/Web/Polyrific.Catapult.Web/ClientApp/src/app/project/data-model/components/data-model-new-dialog/data-model-new-dialog.component.ts, src/Web/Polyrific.Catapult.Web/ClientApp/src/app/project/data-model/components/data-model-property-info-dialog/data-model-property-info-dialog.component.spec.ts, src/Web/Polyrific.Catapult.Web/ClientApp/src/app/project/data-model/components/data-model-property-info-dialog/data-model-property-info-dialog.component.ts, src/Web/Polyrific.Catapult.Web/ClientApp/src/app/project/data-model/components/data-model-property-new-dialog/data-model-property-new-dialog.component.spec.ts, src/Web/Polyrific.Catapult.Web/ClientApp/src/app/project/data-model/components/data-model-property-new-dialog/data-model-property-new-dialog.component.ts, src/Web/Polyrific.Catapult.Web/ClientApp/src/app/project/job-definition/components/job-definition-new-dialog/job-definition-new-dialog.component.spec.ts, src/Web/Polyrific.Catapult.Web/ClientApp/src/app/project/job-definition/components/job-definition-new-dialog/job-definition-new-dialog.component.ts, src/Web/Polyrific.Catapult.Web/ClientApp/src/app/project/job-definition/components/job-task-definition-info-dialog/job-task-definition-info-dialog.component.ts, src/Web/Polyrific.Catapult.Web/ClientApp/src/app/project/job-definition/components/job-task-definition-new-dialog/job-task-definition-new-dialog.component.ts, src/Web/Polyrific.Catapult.Web/ClientApp/src/app/shared/services/utility.service.ts
Some form in the web ui is not showing the validation error after clicking submit. This is because the form is nested in the child form, and the validators does not trigger it recursively. This PR fixes this by manually setting the flag as `touched` so the validation message is triggered.
Note: For editing Job Task Definition, I make the validation error shown after user clicking `Edit`, to highlight the required configs immediately, since in the list page we've already notify user that there's validation error for the task.
=> Trigger validation when clicking submit

src/API/Polyrific.Catapult.Api.Core/Repositories/IProjectDataModelPropertyRepository.cs, src/API/Polyrific.Catapult.Api.Core/Services/IJobDefinitionService.cs, src/API/Polyrific.Catapult.Api.Core/Services/IProjectDataModelService.cs, src/API/Polyrific.Catapult.Api.Core/Services/JobDefinitionService.cs, src/API/Polyrific.Catapult.Api.Core/Services/ProjectDataModelService.cs, src/API/Polyrific.Catapult.Api.Data/ProjectDataModelPropertyRepository.cs, src/API/Polyrific.Catapult.Api/Controllers/JobDefinitionController.cs, src/API/Polyrific.Catapult.Api/Controllers/ProjectDataModelController.cs, src/API/Polyrific.Catapult.Api/Program.cs, src/Shared/Polyrific.Catapult.Shared.Dto/ProjectDataModel/CreateProjectDataModelPropertyDto.cs, tests/Polyrific.Catapult.Api.UnitTests/Controllers/JobDefinitionControllerTests.cs, tests/Polyrific.Catapult.Api.UnitTests/Controllers/ProjectDataModelControllerTests.cs, tests/Polyrific.Catapult.Api.UnitTests/Core/Services/ProjectDataModelServiceTests.cs
- Fix error in build-api script: `Unable to create an object of type 'CatapultDbContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728`. This is fixed by refactoring the `CreateWebHostBuilder` in `Program.cs` to only accept one argument. Though I'm not sure why that fixes thing. I was just trying to compare it with previous code.
- Assign proper property sequence when adding property
- Fix error reordering task when there's invalid task
=> Several bugfix api

src/CLI/Polyrific.Catapult.Cli/Utility/CliConfig.cs, src/Engine/Polyrific.Catapult.Engine.Core/CatapultEngineConfig.cs, tests/Polyrific.Catapult.Cli.UnitTests/CliConfigTests.cs, tests/Polyrific.Catapult.Engine.UnitTests/Core/CatapultEngineConfigTest.cs
Change default API Url in Engine and CLI to `https://localhost:44305`. This is to help users to run the components locally for the first time.
=> Change default API Url in Engine and CLI

tools/scripts/run-cli.bat, tools/scripts/run-engine.bat
Some small adjustments to the intro message in run scripts: remove `.exe` so it matches with the usage guide.
=> Small adjustment to the intro message in run scripts

src/Web/Polyrific.Catapult.Web/ClientApp/src/app/project/job-definition/job-definition/job-definition.component.ts, src/Web/Polyrific.Catapult.Web/ClientApp/src/app/project/project-detail/project-detail.component.ts
Fix incorrect error message when trying to queue a job and there's already running job in the project. Now it's showing as if there's some issue in the task definition instead.
=> Fix incorrect error message when there's already queued job

src/Engine/Polyrific.Catapult.Engine.Core/PluginManager.cs, src/Engine/Polyrific.Catapult.Engine.Core/TaskRunner.cs, src/Plugins/BuildProvider/Polyrific.Catapult.TaskProviders.DotNetCore/src/Program.cs, src/Plugins/GeneratorProvider/Polyrific.Catapult.TaskProviders.AspNetCoreMvc/src/Program.cs, src/Plugins/HostingProvider/Polyrific.Catapult.TaskProviders.AzureAppService/src/Program.cs, src/Plugins/Polyrific.Catapult.TaskProviders.Core/BuildProvider.cs, src/Plugins/Polyrific.Catapult.TaskProviders.Core/CodeGeneratorProvider.cs, src/Plugins/Polyrific.Catapult.TaskProviders.Core/DatabaseProvider.cs, src/Plugins/Polyrific.Catapult.TaskProviders.Core/GenericTaskProvider.cs, src/Plugins/Polyrific.Catapult.TaskProviders.Core/HostingProvider.cs, src/Plugins/Polyrific.Catapult.TaskProviders.Core/RepositoryProvider.cs, src/Plugins/Polyrific.Catapult.TaskProviders.Core/StorageProvider.cs, src/Plugins/Polyrific.Catapult.TaskProviders.Core/TestProvider.cs, src/Plugins/TestProvider/Polyrific.Catapult.TaskProviders.DotNetCoreTest/src/Program.cs, tests/Polyrific.Catapult.Engine.UnitTests/Core/PluginManagerTests.cs, tests/Polyrific.Catapult.Engine.UnitTests/SkipOnNonWindowsFact.cs, tools/scripts/run.bat
Fix some issue in engine task provider release
=> Fix engine Task Provider

tools/scripts/run.bat
There was an issue when running "run.bat" script from a drive other than `C:\`. This PR should fix it.
=> Fix run.bat if being run from drive other than "c"

src/API/Polyrific.Catapult.Api.Core/Services/IJobDefinitionService.cs, src/API/Polyrific.Catapult.Api.Core/Services/JobDefinitionService.cs, src/API/Polyrific.Catapult.Api.SecretVault/SecretVault.cs, src/API/Polyrific.Catapult.Api/Controllers/JobDefinitionController.cs, tests/Polyrific.Catapult.Api.UnitTests/Controllers/JobDefinitionControllerTests.cs, tests/Polyrific.Catapult.Api.UnitTests/Core/Services/JobQueueServiceTests.cs
Fix error that occured after modifying the order of the job task definition, and after queueing a job
=> Hotfix: Fix issue related to job task definition side effect

src/Web/Polyrific.Catapult.Web/ClientApp/src/app/project/data-model/components/data-model-property-form/data-model-property-form.component.html, src/Web/Polyrific.Catapult.Web/ClientApp/src/app/project/data-model/components/data-model-property-form/data-model-property-form.component.ts, src/Web/Polyrific.Catapult.Web/ClientApp/src/app/project/data-model/components/data-model-property-info-dialog/data-model-property-info-dialog.component.html, src/Web/Polyrific.Catapult.Web/ClientApp/src/app/project/data-model/components/data-model-property-info-dialog/data-model-property-info-dialog.component.ts
Allow setting related data model to empty after being selected in the data model property popup
=> Web UI: Allow set related data model to empty after being selected

src/API/Polyrific.Catapult.Api.Core/Entities/ProjectTemplate.cs
Fix export project does not include IsDefault flag
=> API: Fix export project does not include IsDefault flag

src/TaskProviders/BuildProvider/Polyrific.Catapult.TaskProviders.DotNetCore/src/Helpers/TextHelper.cs, src/TaskProviders/BuildProvider/Polyrific.Catapult.TaskProviders.DotNetCore/src/Polyrific.Catapult.TaskProviders.DotNetCore.csproj, src/TaskProviders/BuildProvider/Polyrific.Catapult.TaskProviders.DotNetCore/src/Program.cs, src/TaskProviders/DatabaseProvider/Polyrific.Catapult.TaskProviders.EntityFrameworkCore/src/Helpers/TextHelper.cs, src/TaskProviders/DatabaseProvider/Polyrific.Catapult.TaskProviders.EntityFrameworkCore/src/Polyrific.Catapult.TaskProviders.EntityFrameworkCore.csproj, src/TaskProviders/DatabaseProvider/Polyrific.Catapult.TaskProviders.EntityFrameworkCore/src/Program.cs
Fix issue in `Polyrific.Catapult.TaskProviders.DotNetCore` & `Polyrific.Catapult.TaskProviders.EntityFrameworkCore` when there's hyphen character in the project name
=> Hotfix - Fix build error when project name contains hyphen

src/API/Polyrific.Catapult.Api.Core/Services/JobQueueService.cs, src/API/Polyrific.Catapult.Api/notificationconfig.json, src/Shared/Polyrific.Catapult.Shared.Common/Notification/NotificationConfig.cs, src/Shared/Polyrific.Catapult.Shared.Common/Notification/Template/ProjectResourceDeleted.html, src/Shared/Polyrific.Catapult.Shared.Common/Notification/Template/SmtpEmail/ProjectResourceDeleted.html, src/Shared/Polyrific.Catapult.Shared.Common/Polyrific.Catapult.Shared.Common.csproj
When a resource deletion job is completed, currently it sends the same email template as the usual job queue, which include the link to the job status web UI. The link will be broken in resource deletion jobs, because the project is deleted once the resource deletion is complete.
To fix this, I created a separate template to notify when a resource deletion job is completed, which does not include link to the job status web UI
=> API: Add email template for resource deletion

src/TaskProviders/DatabaseProvider/Polyrific.Catapult.TaskProviders.EntityFrameworkCore/src/DatabaseCommand.cs
Fix migration error in DB provider due to incorrect EF version
=> Hotfix: Fix migration error in DB provider due to incorrect EF version

docs/api/api.md
- Fix the link to `Project` endpoint docs
- Fix wording on the note
=> Fix link and some wording

src/API/Polyrific.Catapult.Api/Controllers/TaskProviderController.cs, src/Web/Polyrific.Catapult.Web/ClientApp/src/app/core/interceptors/error.interceptor.ts
Prevent basic user from getting logged out when adding task
Issue #593
=> Prevent basic user from getting logged out when adding task

src/Engine/Polyrific.Catapult.Engine/ConsoleWindow.cs, src/Engine/Polyrific.Catapult.Engine/Polyrific.Catapult.Engine.csproj, src/Engine/Polyrific.Catapult.Engine/Program.cs
Disable the Quick Edit mode in windows console app to prevent the engine from freezing the process
- Related Issues: #598
=> Engine: Disable Quick Edit mode to avoid process freeze

src/Shared/Polyrific.Catapult.Shared.Dto/JobQueue/JobDto.cs, src/Web/Polyrific.Catapult.Web/ClientApp/src/app/core/models/job-queue/job-queue-dto.ts, src/Web/Polyrific.Catapult.Web/ClientApp/src/app/project/components/data-model-property/data-model-property.component.css, src/Web/Polyrific.Catapult.Web/ClientApp/src/app/project/components/job-list-form/job-list-form.component.css, src/Web/Polyrific.Catapult.Web/ClientApp/src/app/project/components/job-list-form/job-list-form.component.html, src/Web/Polyrific.Catapult.Web/ClientApp/src/app/project/job-queue/job-queue-list/job-queue-list.component.html, src/Web/Polyrific.Catapult.Web/ClientApp/src/app/project/job-queue/job-queue-list/job-queue-list.component.ts
- Add update date column in job queue grid
- Fix some styling in create project to make it consistent with Model and Job Definition tab
=> Web UI: Add updated date in job queue list

src/Shared/Polyrific.Catapult.Shared.Common/FileHelper.cs, src/Shared/Polyrific.Catapult.Shared.Common/Polyrific.Catapult.Shared.Common.csproj
Mimic the implementation of `AppendAllTextAsync` as in dotnet core to be able to handle asynchronous file write operation properly
- Related Issues: #602
=> API: Fix job queue log does not saved

src/Web/Polyrific.Catapult.Web/ClientApp/src/app/account/components/user-set-role-dialog/user-set-role-dialog.component.ts
Fix role dropdown not showing on set user role. The issue was caused by different property name of `role`, so mapping process is not working between `userRoleForm` and `user`
- Related Issues: https://github.com/Polyrific-Inc/OpenCatapult/issues/604
=> Issue #604 - Fix role dropdown not showing on set user role
